### PR TITLE
Removing unnecessary parser error output

### LINKED ISSUE #14768: Misleading/unnecessary "The type initializer for 'Microsoft.DotNet.Cli.Parser' threw an exception."
The following error is caused by _"C:\testAsset.props" was not found_. However, the extra text in bold is misleading/unnecessary. We don't need to display them. We should handle GracefulException specially (I believe we used to do that) so that only the message from GracefulException is displayed.

--------------------

**System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.Parser' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.Cli.AddProjectToProjectReferenceParser' threw an exception.
 ---> Microsoft.DotNet.Cli.Utils.GracefulException:** Project `C:\Users\wul\Downloads\testfolder\VSTestCore.csproj` could not be evaluated. Evaluation failed with following error:
The imported project "C:\testAsset.props" was not found. Confirm that the expression in the Import declaration "\testAsset.props" is correct, and that the file exists on disk.  C:\Users\wul\Downloads\testfolder\VSTestCore.csproj.
   at Microsoft.DotNet.Tools.MsbuildProject.GetEvaluatedProject() in C:\work\sdk\src\Cli\dotnet\MsbuildProject.cs:line 234
   at Microsoft.DotNet.Tools.MsbuildProject.GetTargetFrameworks() in C:\work\sdk\src\Cli\dotnet\MsbuildProject.cs:line 171
   at Microsoft.DotNet.Cli.Suggest.TargetFrameworksFromProjectFile()+MoveNext() in C:\work\sdk\src\Cli\dotnet\commands\dotnet-complete\Suggest.cs:line 23
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Cli.AddProjectToProjectReferenceParser..cctor() in C:\work\sdk\src\Cli\dotnet\commands\dotnet-add\dotnet-add-reference\AddProjectToProjectReferenceParser.cs:line 19
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Cli.AddProjectToProjectReferenceParser.GetCommand() in C:\work\sdk\src\Cli\dotnet\commands\dotnet-add\dotnet-add-reference\AddProjectToProjectReferenceParser.cs:line 31
   at Microsoft.DotNet.Cli.AddCommandParser.GetCommand() in C:\work\sdk\src\Cli\dotnet\commands\dotnet-add\AddCommandParser.cs:line 23
   at Microsoft.DotNet.Cli.Parser..cctor() in C:\work\sdk\src\Cli\dotnet\Parser.cs:line 23
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Cli.Parser.get_Instance() in C:\work\sdk\src\Cli\dotnet\Parser.cs:line 90
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient) in C:\work\sdk\src\Cli\dotnet\Program.cs:line 111
   at Microsoft.DotNet.Cli.Program.Main(String[] args) in C:\work\sdk\src\Cli\dotnet\Program.cs:line 65

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/sdk/issues/14768

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-complete/Suggest.cs [hunk 1]
```diff
@@ -13,37 +13,55 @@ internal static class Suggest
     {
         public static IEnumerable<string> TargetFrameworksFromProjectFile()
         {
-            var msBuildProject = GetMSBuildProject();
-
-            if (msBuildProject == null)
+            try
             {
-                yield break;
+                return GetMSBuildProject()?.GetTargetFrameworks().Select(tf => tf.GetShortFolderName()) ?? Empty<string>();
```
Comment (wli3) [inline src/Cli/dotnet/commands/dotnet-complete/Suggest.cs:18]: Thanks for the quick turnaround. Although I don't know how that worked. Why the change is in dotnet-complete? Isn't that only for auto competition?

Comment (sfoslund) [reply src/Cli/dotnet/commands/dotnet-complete/Suggest.cs:18]: The problem was with generating argument suggestions when the project file isn't valid, which occurs regardless of which command is called when the parser is instantiated. Here's an example of how these methods are used: https://github.com/dotnet/sdk/blob/master/src/Cli/dotnet/CommonOptions.cs#L39

**Review by wli3 — APPROVED** [review]
