### PR TITLE
Parser for actual MSBuild Property option syntax

### LINKED ISSUE #27059: dotnet build parameters (-p) don't work when joined by semicolon (;) in dotnet 6.0.400
### Describe the bug
Using multiple MSBuild parameters joined by a semicolon in a `dotnet build` command don't work anymore in dotnet 6.0.400.

### To Reproduce

Executing the following command doesn't work anymore:
```
dotnet build -p:propertyA=valueA;propertyB=valueB
```
But changing it to this does:
```
dotnet build -p:propertyA=valueA -p:propertyB=valueB
```

In my case, the command:
```
dotnet build -p:Version=1.1.1.1;AdditionalConstants=Beta
```
resulted in the following error:
```
Error NETSDK1018: Invalid NuGet version string: '1.1.1.1;AdditionalConstants=Beta'.
```

### Exceptions (if any)

N/A

### Further technical details
- Using dotnet version 6.0.400 (previously worked in version 6.0.302)
- Command being executed as part of an Azure DevOps build pipeline

### PR DESCRIPTION
**Pull request by baronfel**
## Description

Fix issues forwarding a complex variation of allowable input for the MSBuild `-p` (Property) option, which is parsed, escaped, and forwarded to MSBuild as a feature of the SDK.

## Customer Impact

In AzDO (and likely other scenarios), users-defined properties are passed with a single `-p` option, in a semicolon-delimited list of key/value pairs. Enforcement/unification of the property option in the 6.0.3xx series of SDKs introduced a regression in this parsing that resulted in malformed key/value pairs being passed to user builds. The most common effect of this was to prevent the build from running due to invalid CLI argument syntax.

Closes https://github.com/dotnet/sdk/issues/27059

The SDK property option didn't know about the semicolon- and comma-delimited forms of MSBuild properties. This adds an actual parser to validate this shaping, so that we can intelligently do the semi-colon escaping that we aimed to do originally, without also inadvertently escaping the semicolon-delimited property list use case for `-p`.

The core tension here is the SDK wants to do escaping of semicolons inside property _values_ so that those properties aren't interpreted incorrectly by the MSBuild CLI parser. This is a historical pain point for users, which is why we started doing this back in the day.  This has been done through the Property Option in the SDK, and over time our parsing of the value portions of this CLI flag has grown.

## Regression

Yes

## Risk

Medium. The fix was to create a new parser for the syntax of the MSBuild Property option, versus the naïve string splitting that was done in the past. This is a nontrivial amount of code.

## Testing

The new tests for this forwarding now cover a few additional cases that I verified with Rainer and Ben - quoted property values that contain semicolons and spaces, and unquoted values signaling a new property name. Automated testing was done with all known variants of the `-p` argument syntax. The existing cases were:

* single key/value (X=Y)
* single key with quoted value (X="Y")
* single key with quoted semicolon delimited value (X="A;B;C")

And the following cases were added:

* single key with whitespace values (x=" a y value")
* multiple key/value pairs, semicolon delimited, with values being of all of the above types (x=y;x2="y";x3="a;b;c";x4="a ;b ;")

### CODE REVIEW

File: src/Cli/dotnet/OptionForwardingExtensions.cs [hunk 1]
```diff
@@ -18,10 +19,45 @@ public static class OptionForwardingExtensions
...
+            }
+        }
+        public static IResult<(string key, string value)[]> ParseKeyValues(string msbuildKeyValue) => KeyValueParser.TryParse(msbuildKeyValue);
+
         public static ForwardedOption<string[]> ForwardAsProperty(this ForwardedOption<string[]> option) => option
             .SetForwardingFunction((optionVals) =>
                 optionVals
-                    .Select(optionVal => optionVal.Replace(";", "%3B")) // must escape semicolon-delimited property values when forwarding them to MSBuild
+                    .Select(ParseKeyValues)
+                    .SelectMany(result => {
```
Comment (baronfel) [inline src/Cli/dotnet/OptionForwardingExtensions.cs:52]: should talk about how we want to handle parsing errors here - right now I'm swallowing malformed parses.

File: src/Cli/dotnet/dotnet.csproj [hunk 2]
```diff
@@ -12,6 +12,7 @@
     <PackageId>Microsoft.DotNet.Cli</PackageId>
     <UseAppHost>false</UseAppHost>
     <IsPackable>true</IsPackable>
+    <NoWarn>$(NoWarn);CS8002</NoWarn>
```
Comment (baronfel) [inline src/Cli/dotnet/dotnet.csproj:15]: Sprache isn't strong named. This is likely going to be an issue. @marcpopMSFT any pointers on how this should be handled?

File: src/Cli/dotnet/dotnet.csproj [hunk 3]
```diff
@@ -95,6 +96,7 @@
     <PackageReference Include="Microsoft.Deployment.DotNet.Releases" Version="$(MicrosoftDeploymentDotNetReleasesVersion)" />
     <PackageReference Include="System.ServiceProcess.ServiceController" Version="$(SystemServiceProcessServiceControllerVersion)" />
     <PackageReference Include="Microsoft.VisualStudio.Setup.Configuration.Interop" Version="$(MicrosoftVisualStudioSetupConfigurationInteropVersion)" PrivateAssets="All" ExcludeAssets="Runtime"/>
+    <PackageReference Include="Sprache" Version="$(SpracheVersion)" />
```
Comment (marcpopMSFT) [inline src/Cli/dotnet/dotnet.csproj:99]: @MichaelSimons is Sprache source build compliant? This is only for 6.0.4xx so maybe not as risky if source build stays on 6.0.1xx.

The license is MIT.  @richlander @leecow on the question of process for pulling in a new open source library.

File: src/Cli/dotnet/dotnet.csproj (hunk 2 above)
Comment (marcpopMSFT) [reply src/Cli/dotnet/dotnet.csproj:15]: @leecow do we have any strong name signing requirements for .net core?

File: src/Cli/dotnet/dotnet.csproj (hunk 3 above)
Comment (MichaelSimons) [reply src/Cli/dotnet/dotnet.csproj:99]: Even if this is only going into 6.0.4xx it still would impact source-build when it reached 7.0.

Sprache is not something included in source-build today.  I would suggest reading through the [documentation](https://github.com/dotnet/source-build/blob/main/Documentation/sourcebuild-in-repos/new-dependencies.md) on adding new source-build dependencies.  It appears to only have a [dependency on source-link](https://github.com/sprache/Sprache/blob/develop/src/Sprache/Sprache.csproj) therefore it could be handled via an [external repository that we source-build](https://github.com/dotnet/source-build-externals).

File: src/Cli/dotnet/dotnet.csproj (hunk 2 above)
Comment (leecow) [reply src/Cli/dotnet/dotnet.csproj:15]: Yes, I'm pretty sure sn signing is required across windows DLLs. @mmitche to confirm that we're doing this elsewhere.

Comment (mmitche) [reply src/Cli/dotnet/dotnet.csproj:15]: From @jkotas a bit back:

> Strong name signing does not matter in .NET Core. Nothing ever looks or verifies the signatures .NET Core, that includes crossgen. Ideally, we would be public-signing all .NET binaries that are not meant to run on desktop. https://github.com/dotnet/runtime/blob/main/docs/project/public-signing.md

File: src/Cli/dotnet/OptionForwardingExtensions.cs [hunk 4]
```diff
@@ -18,10 +19,45 @@ public static class OptionForwardingExtensions
...
+                var valueParser = 
+                    Parse.XOr(quotedValueParser, Parse.CharExcept(';').AtLeastOnce().Text()).Named("value");
+                var keyValueParser = 
+                    from key in keyParser
+                    from _equals in Parse.Char('=')
+                    from value in valueParser
+                    select (key, value);
+                var semiOrCommaParser = Parse.Chars(new[]{';', ','});
+                var keyValues = Parse.DelimitedBy(keyValueParser.Named("key/value"), Parse.Char(';')).Select(pairs => pairs.ToArray()).Named("key/value list");
+                return keyValues;
```
Comment (jkotas) [inline src/Cli/dotnet/OptionForwardingExtensions.cs:43]: What are the performance characteristics of this? This feels like a very expensive way to create a simple parser.

File: src/Cli/dotnet/dotnet.csproj (hunk 2 above)
Comment (baronfel) [reply src/Cli/dotnet/dotnet.csproj]: I've sidestepped the issue by using a hand-rolled parser here instead of Sprache.

File: src/Cli/dotnet/dotnet.csproj (hunk 3 above)
Comment (baronfel) [reply src/Cli/dotnet/dotnet.csproj]: I sidestepped the source-build conversation by removing Sprache in favor of a hand-rolled parser.

File: src/Cli/dotnet/OptionForwardingExtensions.cs (hunk 4 above)
Comment (baronfel) [reply src/Cli/dotnet/OptionForwardingExtensions.cs]: I was very hesitant to roll my own parser - I'm not an expert at doing that, and using a library to handle the combinations adds nice guardrails.

However I've rolled a new one that I'll need to test the heck out of now to sidestep the issue.

File: src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+        void ParseQuotedValue() {
+            TryConsume(out var leadingQuote); // consume the leading quote, which we know is there
+            currentValue += leadingQuote;
+            while(TryConsume(out char? c)) {
+                if (c == '"') {
+                    currentValue += c;
+                    // we're done
+                    return;
+                }
+                currentValue += c;
```
Comment (jkotas) [inline src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs:51]: Use StringBuilder?

Building strings by adding one character at a time is an inefficient quadratic operation. StringBuilder is designed for that.

Comment (baronfel) [reply src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs]: Good spot, I've swapped it out for StringBuilders that get cleared when the key/value pairs are emitted.

File: src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs [hunk 6]
```diff
@@ -9,14 +10,14 @@ namespace Microsoft.DotNet.Cli.Utils;
...
         
         (string key, string value) EmitAndReset() {
-            var key = currentKey!;
-            var value= currentValue!;
-            currentKey = null;
-            currentValue = null;
+            var key = currentKey.ToString();
+            var value= currentValue.ToString();
+            currentKey = currentKey.Clear();
+            currentValue = currentValue.Clear();
```
Comment (jkotas) [inline src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs:20]:
```suggestion
            currentKey.Clear();
            currentValue.Clear();
```
Unnecessary.

File: src/Cli/dotnet/OptionForwardingExtensions.cs [hunk 7]
```diff
@@ -18,10 +19,45 @@ public static class OptionForwardingExtensions
 
         public static ForwardedOption<T> ForwardAsSingle<T>(this ForwardedOption<T> option, Func<T, string> format) => option.SetForwardingFunction(format);
 
+        private static Parser<(string key, string value)[]> KeyValueParser {
+            get {
+                bool IsValidMSBuildPropertyChar (char c) => Char.IsLetterOrDigit(c) || (c == '_') || (c == '-');
```
[the remark this answers is not in the document]
Comment (baronfel) [reply src/Cli/dotnet/OptionForwardingExtensions.cs]: Got Rainer to look at the manual parser and his feedback was

> I don't like it but it's not that much code, seems to do the job, and is a reasonable path forward IMO

which is basically all any of us can really hope for

File: src/Tests/dotnet.Tests/ParserTests/MSBuildArgumentCommandLineParserTests.cs [hunk 8]
```diff
@@ -49,6 +49,9 @@ public void MSBuildArgumentsAreForwardedCorrectly(string[] arguments, bool build
         [InlineData(new string[] { "-p:teamcity_buildConfName=\"Build, Test and Publish\"" }, new string[] { "--property:teamcity_buildConfName=\"Build, Test and Publish\"" })]
         [InlineData(new string[] { "-p:prop1=true", "-p:prop2=false" }, new string[] { "--property:prop1=true", "--property:prop2=false" })]
         [InlineData(new string[] { "-p:prop1=\".;/opt/usr\"" }, new string[] { "--property:prop1=\".%3B/opt/usr\"" })]
+        [InlineData(new string[] { "-p:prop1=true;prop2=false;prop3=\"wut\";prop4=\"1;2;3\"" }, new string[]{ "--property:prop1=true", "--property:prop2=false", "--property:prop3=\"wut\"", "--property:prop4=\"1%3B2%3B3\""})]
+        [InlineData(new string[] { "-p:prop4=\"1;2;3\"" }, new string[]{ "--property:prop4=\"1%3B2%3B3\""})]
+        [InlineData(new string[] { "-p:prop4=\"1 ;2 ;3 \"" }, new string[]{ "--property:prop4=\"1 %3B2 %3B3 \""})]
         public void Can_pass_msbuild_properties_safely(string[] tokens, string[] forwardedTokens) {
```
Comment (nagilson) [inline src/Tests/dotnet.Tests/ParserTests/MSBuildArgumentCommandLineParserTests.cs:55]: Might be helpful to add these tests and show it works with different aliases and also that it works with values wraped in ' instead of just ". That could also be overkill. 


     [InlineData(new string[] { "/p:BuildDir=\"C:\\users\\foo\\folder;\""}, new string[] {"--property:BuildDir=\"C:\\users\\foo\\folder%3B\""})]
        [InlineData(new string[] { "/property:BuildDir=\"C:\\users\\foo\\folder;\"" }, new string[] { "--property:BuildDir=\"C:\\users\\foo\\folder%3B\"" })]
        [InlineData(new string[] { "/property:BuildDir=\'C:\\users\\foo\\folder'" }, new string[] { "--property:BuildDir=\'C:\\users\\foo\\folder'" })]
        [InlineData(new string[] { "/p:Configuration='Release';" }, new string[] { "--property:Configuration='Release'" })]

**Review by nagilson — APPROVED** [review]
I tried to break it from many different angles and could not break it. If Rainer has validated it from the MSBuild syntax side, LGTM. Not sure if you need approval from a servicing person as well.

**Review by dsplaisted — APPROVED** [review]
LGTM 👍

File: src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs [hunk 9]
```diff
@@ -0,0 +1,90 @@
+using System.Collections.Generic;
```
Comment (joeloff) [inline src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs:1]: This file is missing the MIT license header. Probably should run Ctrl+K+D to fix up formatting :)

File: src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs [hunk 10]
```diff
@@ -0,0 +1,90 @@
...
+            return (key, value);
+        }
+
+        char? Peek() => currentPos < input.Length ? input[currentPos] : null;
+
+        bool TryConsume(out char? consumed) {
+            if(input.Length > currentPos) {
+                consumed = input[currentPos];
+                currentPos++;
+                return true;
```
Comment (joeloff) [inline src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs:30]: Can probably move the returns outside the if/else and just do `return consumed != null`

File: src/Cli/dotnet/OptionForwardingExtensions.cs [hunk 11]
```diff
@@ -21,8 +21,9 @@ public static class OptionForwardingExtensions
         public static ForwardedOption<string[]> ForwardAsProperty(this ForwardedOption<string[]> option) => option
             .SetForwardingFunction((optionVals) =>
                 optionVals
-                    .Select(optionVal => optionVal.Replace(";", "%3B")) // must escape semicolon-delimited property values when forwarding them to MSBuild
-                    .Select(optionVal => $"{option.Aliases.FirstOrDefault()}:{optionVal}")
+                    .SelectMany(Microsoft.DotNet.Cli.Utils.MSBuildPropertyParser.ParseProperties)
+                    // must escape semicolon-delimited property values when forwarding them to MSBuild
+                    .Select(optionVal => $"{option.Aliases.FirstOrDefault()}:{optionVal.key}={optionVal.value.Replace(";", "%3B")}")
```
Comment (joeloff) [inline src/Cli/dotnet/OptionForwardingExtensions.cs:26]: Is `;` the only value that needs to be encoded? And can `FirstOrDefault` ever return a `null` result here?

Comment (baronfel) [reply src/Cli/dotnet/OptionForwardingExtensions.cs:26]: Yeah, semicolon is the only thing we need to escape - it comes from the meaning of `:` in an MSbuild Item context as a collection delimiter :)

The FirstOrDefault will never throw a null here - it's grabbing the 'best' alias of the property option which is `--property`.

File: src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs (hunk 9 above)
Comment (baronfel) [reply src/Cli/Microsoft.DotNet.Cli.Utils/MSBuildPropertyParser.cs:4]: Thanks for the spot - updated.
