### PR TITLE
NuGetPackageDownloader: Stop verifying the package signature on Mac and queue off of the environment on Linux

### LINKED ISSUE #46857: dotnet tool restore started failing on macOS with NU3037 and NU3028 errors after 11th February
### Describe the bug

Since February 13th (👻), the CI in Polly when running on macOS has [stopped working](https://github.com/App-vNext/Polly/actions/runs/13313926654/job/37214156995?pr=2492#step:6:15) with the error shown below.

The strange thing is this doesn't seem to correlate with any specific code change to Polly itself. We had a successful build on February 11th after updating to the .NET 9.0.200 SDK [here](https://github.com/App-vNext/Polly/actions/runs/13271535970), so it doesn't seem to correlate nicely with a change in SDK behaviour.

The runner version doesn't appear to differ either, so that would presumably rule out a change in GitHub Actions:

```text
Current runner version: '2.322.0'
Operating System
  macOS
  14.7.2
  23H311
```

I don't have access to a physical MacBook but two colleagues can replicate the failure on their machines by cloning the repo and running `dotnet tool restore`.

The things I don't really understand are:

- Why now, when the countersignature timestamp expired last year?
- Why only on macOS?

I've experimented with a few things in this PR to try and get more information, but with no success: https://github.com/App-vNext/Polly/pull/2496. Check out the commit history and workflow run logs for more detail. For example, setting `DOTNET_NUGET_SIGNATURE_VERIFICATION=false` hasn't helped.

Seems like either it's failing on macOS when it shouldn't _or_ it should be consistently failing on macOS, Linux and Windows if there is a genuine certificate trust issue.

I've also reported this here against the tool itself in case they've genuinely revoked a certificate or something, but again if that's the case I'd expect it to fail on all OSs: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/1698

### To Reproduce

Clone [App-vNext/Poll](https://github.com/App-vNext/Polly) on a MacBook and run `dotnet tool restore` from the root of the repository.

### Exceptions (if any)

```text
> dotnet tool restore --no-http-cache --verbosity diagnostic
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/cake.tool/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/cake.tool/index.json 75ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/cake.tool/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/cake.tool/index.json 30ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/cake.tool/5.0.0/cake.tool.5.0.0.nupkg
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/cake.tool/5.0.0/cake.tool.5.0.0.nupkg 3ms
Verified that the NuGet package "cake.tool.5.0.0" has a valid signature.
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/docfx/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/docfx/index.json 39ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/docfx/page/0.0.1-alpha-1517061409/2.10.2.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/docfx/page/0.0.1-alpha-1517061409/2.10.2.json 31ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/docfx/page/2.11.0/2.40.0.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/docfx/page/2.11.0/2.40.0.json 30ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/docfx/page/2.40.1/2.63.1.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/docfx/page/2.40.1/2.63.1.json 38ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/docfx/page/2.64.0/2.78.2.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/docfx/page/2.64.0/2.78.2.json 30ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/docfx/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/docfx/index.json 29ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/docfx/2.78.2/docfx.2.78.2.nupkg
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/docfx/2.78.2/docfx.2.78.2.nupkg 2ms
Verified that the NuGet package "docfx.2.78.2" has a valid signature.
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-validate/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-validate/index.json 38ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/dotnet-validate/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/dotnet-validate/index.json 29ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/dotnet-validate/0.0.1-preview.304/dotnet-validate.0.0.1-preview.304.nupkg
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/dotnet-validate/0.0.1-preview.304/dotnet-validate.0.0.1-preview.304.nupkg 3ms
Failed to validate package signing.
Verifying dotnet-validate.0.0.1-preview.304
Signature type: Author
  Subject Name: CN=NuGet Package Explorer (.NET Foundation), O=NuGet Package Explorer (.NET Foundation), L=Redmond, S=Washington, C=US, SERIALNUMBER=603 389 068
  SHA256 hash: 7726640A0DCAB8252F40C73B2FE5C5F38C137E756C0B62521C07DF390288CDAB
  Valid from: 4/25/2021 12:00:00 AM to 7/22/2024 11:59:59 PM
Signature type: Repository
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA256 hash: 5A2901D6ADA3D18260B9C6DFE2[133](https://github.com/App-vNext/Polly/actions/runs/13326053490/job/37219456977?pr=2496#step:5:134)C95D74B9EEF6AE0E5DC334C8454D1477DF4
  Valid from: 2/16/2021 12:00:00 AM to 5/15/2024 11:59:59 PM
warn : NU3018: The repository countersignature found a chain building issue: RevocationStatusUnknown: An incomplete certificate revocation check occurred.
error: NU3037: The repository countersignature validity period has expired.
error: NU3028: The repository countersignature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.
Package signature validation failed.
```

### Further technical details

```text
.NET SDK:
 Version:           9.0.200
 Commit:            90e8b202f2
 Workload version:  9.0.200-manifests.b4a8049f
 MSBuild version:   17.13.8+cbc39bea8
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.7
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /Users/runner/.dotnet/sdk/9.0.200/
.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.
Host:
  Version:      9.0.2
  Architecture: arm64
  Commit:       80aa709f5d
.NET SDKs installed:
  7.0.102 [/Users/runner/.dotnet/sdk]
  7.0.202 [/Users/runner/.dotnet/sdk]
  7.0.[30](https://github.com/App-vNext/Polly/actions/runs/13326053490/job/37219456977?pr=2496#step:5:31)6 [/Users/runner/.dotnet/sdk]
  7.0.410 [/Users/runner/.dotnet/sdk]
  8.0.101 [/Users/runner/.dotnet/sdk]
  8.0.204 [/Users/runner/.dotnet/sdk]
  8.0.303 [/Users/runner/.dotnet/sdk]
  8.0.405 [/Users/runner/.dotnet/sdk]
  8.0.406 [/Users/runner/.dotnet/sdk]
  9.0.102 [/Users/runner/.dotnet/sdk]
  9.0.200 [/Users/runner/.dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.2 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.12 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.13 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.1 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.2 [/Users/runner/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.2 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.12 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.13 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.1 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.2 [/Users/runner/.dotnet/shared/Microsoft.NETCore.App]
Other architectures found:
  None
Environment variables:
  DOTNET_ROOT       [/Users/runner/.dotnet]
global.json file:
  /Users/runner/work/Polly/Polly/global.json
Learn more:
  https://aka.ms/dotnet/info
Download .NET:
  https://aka.ms/dotnet/download
```

### PR DESCRIPTION
**Pull request by edvilme**
Fixes #46857 
**Customer Scenario**
dotnet tool install/restore is checking the package signature on Mac with 9.0.200. However, we shouldn't be doing that as macos doesn't fully support the signature store that nuget uses to verify signatures. This is already disabled for nuget restore.

**Fix**
Match the logic NuGet uses where we are always on for windows, default off for Mac, default on for Linux, and honor the env variable to override the values.

**Justification**
There are half a dozen customer comments on the linked issues saying they are blocked in 9.0.200.

### CODE REVIEW

File: src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs [hunk 1]
```diff
@@ -131,7 +135,6 @@ public async Task<string> DownloadPackageAsync(PackageId packageId,
             }
 
             await VerifySigning(nupkgPath, repository);
```
Comment (joeloff) [inline src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:137]: Wonder if we should delete the package if verification failed.

**Review by joeloff — APPROVED** [review]

File: src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs [hunk 2]
```diff
@@ -65,7 +69,7 @@ public NuGetPackageDownloader(
             _restoreActionConfig = restoreActionConfig ?? new RestoreActionConfig();
             _retryTimer = timer;
             _sourceRepositories = new();
-            _verifySignatures = verifySignatures;
+            _verifySignatures = OperatingSystem.IsWindows() && verifySignatures; // This is temporarily disabled for macOS and Linux.
```
Comment (marcpopMSFT) [inline src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:72]: @dtivel should signature verification on linux be kept and only Mac disabled?

**Review by Forgind — APPROVED** [review]
...other than the linux thing

**Review by nagilson — APPROVED** [review]

File: src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs (hunk 2 above)
Comment (nagilson) [reply src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:72]: It looks like we should enable it on Linux based on this doc https://learn.microsoft.com/en-us/dotnet/core/tools/nuget-signed-package-verification#linux. However, there is also an environment variable which seems to control this, so maybe we should base the check off the environment variable. I assume this is OFF by default on Mac. `DOTNET_NUGET_SIGNATURE_VERIFICATION`.

Comment (nagilson) [reply src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:72]: Ok this code ignores the env var if its not linux, did this environment variable never work correctly? We'd still have to respect it on Linux, though

Comment (dtivel) [reply src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:72]: Matching NuGet's signed package verification support is sensible.

1.  Always enabled on Windows.  `DOTNET_NUGET_SIGNATURE_VERIFICATION` is ignored.
2.  Enabled on Linux by default.  Users can opt out by setting `DOTNET_NUGET_SIGNATURE_VERIFICATION` to `false`.
3.  Disabled on macOS by default.  Users can opt in by setting `DOTNET_NUGET_SIGNATURE_VERIFICATION` to `true`, but this is neither recommended nor supported.

https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/NuGetSignatureVerificationEnabler.cs does the work of enabling on Linux by default.

https://github.com/NuGet/NuGet.Client/blob/594bfe4554893a7364d9ec1d31a22574fba3115c/src/NuGet.Core/NuGet.Packaging/PackageArchiveReader.cs#L519-L557 is where NuGet respects the environment variable.  The problem is that [`FirstPartyNuGetPackageSigningVerifier`](https://github.com/dotnet/sdk/blob/b1d1a0d44487a18a0989ced4fb4c23530da3744f/src/Cli/dotnet/NugetPackageDownloader/FirstPartyNuGetPackageSigningVerifier.cs#L45) opens a package and verifies its signature without checking if it's safe to verify signatures.

You should perform this "can verify signatures" check before deciding that you to verify signatures or you risk deviating from what NuGet supports.

**Review by dtivel — APPROVED** [review]

File: src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs (hunk 2 above)
Comment (dtivel) [reply src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:72]: Yes, that seems reasonable.

`PackageArchiveReader.CanVerifySignedPackages(...)` is a bit inconvenient.  It doesn't access instance members and could have been a static method somewhere.  You could open an issue on NuGet/Home for a more convenient "is signed package verification enabled" method.

Comment (marcpopMSFT) [reply src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:72]: Sounds good. I just didn't want to disable this check on Linux if it were working as that would be a security takeback.

**Review by nagilson — APPROVED** [review]

File: src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs [hunk 3]
```diff
@@ -65,7 +69,9 @@ public NuGetPackageDownloader(
             _restoreActionConfig = restoreActionConfig ?? new RestoreActionConfig();
             _retryTimer = timer;
             _sourceRepositories = new();
-            _verifySignatures = verifySignatures;
+            // If windows or env variable is set, verify signatures
+            _verifySignatures = verifySignatures && (OperatingSystem.IsWindows() ? true 
+                : string.Equals(Environment.GetEnvironmentVariable(NuGetSignatureVerificationEnabler.DotNetNuGetSignatureVerification), bool.TrueString, StringComparison.OrdinalIgnoreCase) ?? OperatingSystem.IsLinux());
```
Comment (nagilson) [inline src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:74]:
```suggestion
                : string.Equals(Environment.GetEnvironmentVariable(NuGetSignatureVerificationEnabler.DotNetNuGetSignatureVerification), bool.FalseString, StringComparison.OrdinalIgnoreCase) ?  false : OperatingSystem.IsLinux());
```

Comment (nagilson) [reply src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:74]: ?? Can't be used on a boolean value like that in C#. The best thing to do imo is check if its explicitly disabled. If it's not explicitly disabled, then check if its linux, so that its enabled by default on linux and not enabled by default on Mac. The windows case is already handled.

File: src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs [hunk 4]
```diff
@@ -65,7 +69,9 @@ public NuGetPackageDownloader(
             _restoreActionConfig = restoreActionConfig ?? new RestoreActionConfig();
             _retryTimer = timer;
             _sourceRepositories = new();
-            _verifySignatures = verifySignatures;
+            // If windows or env variable is set, verify signatures
+            _verifySignatures = verifySignatures && (OperatingSystem.IsWindows() ? true 
+                : string.Equals(Environment.GetEnvironmentVariable(NuGetSignatureVerificationEnabler.DotNetNuGetSignatureVerification), bool.FalseString, StringComparison.OrdinalIgnoreCase) ?  false : OperatingSystem.IsLinux());
```
Comment (Forgind) [inline src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs:74]:
```suggestion
                : bool.TryParse(Environment.GetEnvironmentVariable(NuGetSignatureVerificationEnabler.DotNetNuGetSignatureVerification), out var shouldVerifySignature) ? shouldVerifySignature : OperatingSystem.IsLinux());
```

File: src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs (hunk 3 above)
Comment (Forgind) [reply src/Cli/dotnet/NugetPackageDownloader/NuGetPackageDownloader.cs]: That isn't quite correct, though. And Environment.GetEnvironmentVariable returns a bool?

**Review by Forgind — APPROVED** [review]
Looks good! 🚢
