### PR TITLE
No drive enumerations Fixes #38050

### LINKED ISSUE #38050: Error when working directory is drive root
We have seen multiple cases where `dotnet restore` times out with an unrecoverable error when the user places an app at OS root. This is easy to do in containers/Dockerfile and is hard to diagnose. It's also not a useful pattern.

`dotnet build` and friends (`restore`, `publish`, `test`, ...) should fail when run at drive root. We can offer a `--force` command to override this case, however, that may not be necessary.

Context: https://github.com/NuGet/Home/issues/13131

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #38050

~I'm not particularly attached to this implementation at the moment. Here's how I came up with it and why it's useful along with its most noteworthy drawbacks:~
 - ~I tried a few commands, and it doesn't seem like the SDK does any glob expansion itself. I suspected that would be in MSBuild, and my testing seemed to confirm that.~
 - ~This means that all commands that ultimately fall into this "drive enumeration" camp go through MSBuildForwardingApp. In particular, they go through its constructor.~
 - ~That means that this is the only place where I can make a single change and have it affect all of dotnet build, dotnet restore, dotnet pack, etc.~
 - ~Drive enumeration happens when we're at the root directory and try to build a project there. Or we can just try to build a project at the root directory. I cover both cases by having one check for an explicit project or solution specified and check if it is a project sitting in the root directory (i.e., Parent == null). I have a second check that we either found an explicit project/sln or we are not sitting in the root directory. (Note that in MSBuild, all arguments should start with a - unless they are a project or solution, and those arguments would escape from the try statement without throwing the Exception.~
 - ~That means this is a surgical change that covers all possible cases of throwing a drive enumeration problem at MSBuild.~

~What's bad?~
 - ~First off, this code probably needs a comment. That's fixable.~
 - ~This involves a try/catch in a loop that is expected to throw often. That's not ideal. I can probably make it better if I only enter the try if !arg.StartsWith('-'). Also fixable.~
 - ~This feels...icky...I don't know how to explain it...but this isn't my favorite change despite the positive things I said above. I'm curious if others have a concrete reason to not like this as opposed to a vague "something smells"~
 - ~I can add a check for --force-enumeration later if people like this design~
 - ~I can also add localization. I chose a couple random reasonable strings, but I can probably make those a good bit clearer, too.~

No further concerns about this PR! It now just uses a pre-built MSBuild feature to prevent drive enumerations. The results look like this:
```
C:\GitHub\sdk\artifacts\bin\redist\Debug\dotnet\sdk\9.0.100-dev\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Defaul
tItems.props(30,14): error MSB5029: The value "**/*.cs" of the "Include" attribute in element <ItemGroup> in file "C:\G
itHub\sdk\artifacts\bin\redist\Debug\dotnet\sdk\9.0.100-dev\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultIte
ms.props (30,14)" is a wildcard that results in enumerating all files on the drive, which was likely not intended. Chec
k that referenced properties are always defined. [C:\C.csproj]
```

Though that error message might be improved, that's very difficult outside the MSBuild repo.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs [hunk 1]
```diff
@@ -40,6 +41,25 @@ private static IEnumerable<string> ConcatTelemetryLogger(IEnumerable<string> arg
 
         public MSBuildForwardingApp(IEnumerable<string> argsToForward, string msbuildPath = null)
         {
+            var foundDir = false;
+            foreach (var arg in argsToForward)
```
Comment (baronfel) [inline src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: The core question I have is - why wouldn't we try to fix this in MSBuild itself? I could imagine a new CLI flag to `--fail-on-root-drive-enumeration` that the CLI could pass, and that would allow MSBuild to accurately parse and check the problem once, for all callers. 

cc @rainersigwald @ladipro for thoughts? The core problem we're trying to fix is that enumerating a path glob from drive root (which is common with SDK-style projects and containers) takes _forever_ in MSBuild and you only get a warning after it's happened, if at all. It would be good to have a stricter mode here.

Comment (rainersigwald) [reply src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: > you only get a warning after it's happened, if at all

We're fixing that: https://github.com/dotnet/msbuild/issues/9818.

There's an existing opt-into-quick-failure for this case: `MSBUILDFAILONDRIVEENUMERATINGWILDCARD=1`. I wouldn't be super opposed to setting this in the SDK.

Containerized build environments are a potential case where someone might intentionally have a project at the root, but even then it's not great--you still need the SDK and enough tools to use it inside the container so it's best to (and our samples do) copy your code into `/build/` or similar.

Comment (baronfel) [reply src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: Oh excellent - @Forgind can you trial using this flag? The idea would be we'd always set this environment variable unless a user passed a `--force-enumeration` (or equivalent) SDK flag.

Comment (Forgind) [reply src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: That sounds 1000% better than my ugly hacky thing, thanks! Will try it out and see what happens.

Comment (Forgind) [reply src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: I tried out MSBUILDFAILONDRIVEENUMERATINGWILDCARD=1, and it worked like a charm! Well, at least in the sense that it correctly detected the drive enumeration and through an error. It pointed to a specific Item Include, and I think a naive user might have no idea why that MSBuild code executed, but if they read a bit further, it says something about a wildcard that results in enumerating all files on the drive, so I call that a win?

```
C:\Program Files\dotnet\sdk\8.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.props(30,14): error M
SB5029: The value "**/*.cs" of the "Include" attribute in element <ItemGroup> in file "C:\Program Files\dotnet\sdk\8.0.
200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.props (30,14)" is a wildcard that results in enumerat
ing all files on the drive, which was likely not intended. Check that referenced properties are always defined. [C:\C.c
sproj]
```

@baronfel, what would you think of setting that unconditionally if it isn't already set (i.e., instead of --force-enumeration, have the user set MSBUILDFAILONDRIVEENUMERATINGWILDCARD=0)? --force-enumeration is probably fine but a bit more difficult.

Comment (baronfel) [reply src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: I'm fine with setting that unconditionally if it isn't already set - we can document the workaround of the environment variable. From a user experience point of view, I'd _love_ to see if we could massage that message a bit - can the CLI tell the user more forcefully when this error occurs to stop doing the bad thing of building in the drive root? Can you drop a screenshot of what this looks like in-context, both in the console logger and in terminal logger?

Comment (Forgind) [reply src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: Sorry this is underwhelming, but this is literally all there is in my console:
image

Comment (Forgind) [reply src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: After a brief flash (too fast for me to tell what was happening), tl gave me this:
image

Comment (baronfel) [reply src/Cli/dotnet/commands/dotnet-msbuild/MSBuildForwardingApp.cs:45]: @Forgind I was thinking similarly - the CLI has a logger that it adds to builds - maybe we could detect that build-failed condition and emit something to the stdout after the build has failed that's more...clean to a user?

**Review by marcpopMSFT — APPROVED** [review]
