### PR TITLE
Check that SDK and app archs match before setting `DOTNET_ROOT` when using `dotnet run`

### LINKED ISSUE #19743: Preview 7 UX for Arm64/x64 co-existence on macOS
Let's take a look at the experience that is offered for Arm64/x64 coexistence on macOS.

I will use this app for the test. https://github.com/dotnet/core/tree/main/samples/dotnet-runtimeinfo

## Installing .NET (correctly)

We haven't updated the installers yet, so I had to take some special steps to setup my machine as if they did. Here's what I did.

- Delete .NET from my machine
- Install various x64 .NET versions (whichever ones I want).
- Move all the files in `dotnet` to `dotnet\x64`
- Install .NET 6 Arm64.

That gets me a working install.

Here are the actual commands I used (skipping over the `.pkg` installs).

```bash
rich@MacBook-Air-M1-2020 share % pwd
/usr/local/share
rich@MacBook-Air-M1-2020 share % sudo -r dotnet
# install x64 versions
rich@MacBook-Air-M1-2020 share % sudo mv dotnet x64
rich@MacBook-Air-M1-2020 share % sudo mkdir dotnet
rich@MacBook-Air-M1-2020 share % sudo mv x64 dotnet
# install .NET 6 Arm64
```

## Running Arm64 apps

```bash
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % pwd 
/Users/rich/git/core/samples/dotnet-runtimeinfo
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % cat dotnet-runtimeinfo.csproj | grep Target
    <TargetFramework>net6.0</TargetFramework>
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo %
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % dotnet run
**.NET information
Version: 6.0.0
FrameworkDescription: .NET 6.0.0-preview.7.21377.19
Libraries version: 6.0.0-preview.7.21377.19
Libraries hash: 91ba01788d4d83475fec3aea7c830376e08585da

**Environment information
OSDescription: Darwin 21.0.0 Darwin Kernel Version 21.0.0: Thu Jul 22 19:52:32 PDT 2021; root:xnu-8019.0.72.141.3~2/RELEASE_ARM64_T8101
OSVersion: Unix 12.0.0
OSArchitecture: Arm64
ProcessorCount: 8
```

That's good. That's expected.

## Running x64 apps -- take one

```bash
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % pwd
/Users/rich/git/core/samples/dotnet-runtimeinfo
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % cat dotnet-runtimeinfo.csproj | grep Target
    <TargetFramework>net5.0</TargetFramework>
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % 
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % dotnet run   
Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.7.21377.19/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.7.21377.19/libhostfxr.dylib, 0x0001): tried: '/usr/local/share/dotnet/host/fxr/6.0.0-preview.7.21377.19/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libhostfxr.dylib' (no such file), '/usr/lib/libhostfxr.dylib' (no such file)
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.7.21377.19/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
```

Oooh. You'll see that the .NET 5.0 app is being built as x64. That's good. That's an improvement over earlier .NET 6 builds.

Nothing in the system yet knows AFAIK that it should be looking for .NET 6 in the x64 directory. Let's try some more tricks (the equivalent of what will be automatic).

```bash
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % export DOTNET_ROOT=/usr/local/share/dotnet/x64
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % ./bin/Debug/net5.0/dotnet-runtimeinfo
**.NET information
Version: 5.0.9
FrameworkDescription: .NET 5.0.9
Libraries version: 5.0.9
Libraries hash: 208e377a5329ad6eb1db5e5fb9d4590fa50beadd

**Environment information
OSDescription: Darwin 21.0.0 Darwin Kernel Version 21.0.0: Thu Jul 22 19:52:32 PDT 2021; root:xnu-8019.0.72.141.3~2/RELEASE_ARM64_T8101
OSVersion: Unix 11.0.0
OSArchitecture: X64
ProcessorCount: 8
```

That's good.

## Running x64 apps -- take two

Let's apply the new guidance: https://github.com/dotnet/sdk/issues/19743#issuecomment-899094680.

```bash
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % cat /etc/dotnet/install_location 
/usr/local/share/dotnet/x64
arm64=/usr/local/share/dotnet
x64=/usr/local/share/dotnet/x64
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % rm -r obj bin
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % cat dotnet-runtimeinfo.csproj 
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Displays .NET version and environment information.</Description>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RollForward>LatestMajor</RollForward>
    <VersionPrefix>1.0.4</VersionPrefix>
    <PackageProjectUrl>https://github.com/dotnet/core/blob/main/samples/dotnet-runtimeinfo/README.md</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>.NET Foundation</Copyright>
    <Authors>.NET Team</Authors>
    <PackAsTool>true</PackAsTool>
  </PropertyGroup>

</Project>
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % dotnet run
Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.7.21377.19/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.7.21377.19/libhostfxr.dylib, 0x0001): tried: '/usr/local/share/dotnet/host/fxr/6.0.0-preview.7.21377.19/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libhostfxr.dylib' (no such file), '/usr/lib/libhostfxr.dylib' (no such file)
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.7.21377.19/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
rich@MacBook-Air-M1-2020 dotnet-runtimeinfo % ./bin/Debug/net5.0/dotnet-runtimeinfo
**.NET information
Version: 5.0.9
FrameworkDescription: .NET 5.0.9
Libraries version: 5.0.9
Libraries hash: 208e377a5329ad6eb1db5e5fb9d4590fa50beadd

**Environment information
OSDescription: Darwin 21.0.0 Darwin Kernel Version 21.0.0: Thu Jul 22 19:52:32 PDT 2021; root:xnu-8019.0.72.141.3~2/RELEASE_ARM64_T8101
OSVersion: Unix 11.0.0
OSArchitecture: X64
ProcessorCount: 8
```

Looks like we have the right apphost and it is doing the right thing but that the CLI is not with `dotnet run`. I tried adding the `UseAppHost` property but that didn't change the behavior.

## Using the Arm64 SDK to target x64

That's actually what I demonstrated above.

I tried using the new `-a` syntax, separately. It doesn't quite work correctly yet. See: https://github.com/dotnet/sdk/issues/19706

## Installing tools

Let's see how .NET tools works.

```bash
rich@MacBook-Air-M1-2020 ~ % dotnet tool list -g
Package Id      Version      Commands
rich@MacBook-Air-M1-2020 ~ % dotnet tool install -g dotnet-runtimeinfo
rich@MacBook-Air-M1-2020 ~ % export PATH="$PATH:/Users/rich/.dotnet/tools"
rich@MacBook-Air-M1-2020 ~ % dotnet-runtimeinfo                           
zsh: killed     dotnet-runtimeinfo
rich@MacBook-Air-M1-2020 ~ % which dotnet-runtimeinfo
/Users/rich/.dotnet/tools/dotnet-runtimeinfo
rich@MacBook-Air-M1-2020 ~ % codesign -s - /Users/rich/.dotnet/tools/dotnet-runtimeinfo
rich@MacBook-Air-M1-2020 ~ % dotnet-runtimeinfo       
**.NET information
Version: 6.0.0
FrameworkDescription: .NET 6.0.0-preview.7.21377.19
Libraries version: 6.0.0-preview.7.21377.19
Libraries hash: 91ba01788d4d83475fec3aea7c830376e08585da

**Environment information
OSDescription: Darwin 21.0.0 Darwin Kernel Version 21.0.0: Thu Jul 22 19:52:32 PDT 2021; root:xnu-8019.0.72.141.3~2/RELEASE_ARM64_T8101
OSVersion: Unix 12.0.0
OSArchitecture: Arm64
ProcessorCount: 8
rich@MacBook-Air-M1-2020 ~ % cat /Users/rich/.dotnet/tools/.store/dotnet-runtimeinfo/1.0.4/dotnet-runtimeinfo/1.0.4/tools/netcoreapp3.1/any/dotnet-runtimeinfo.runtimeconfig.json 
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "rollForward": "LatestMajor",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    }
  }
}
                                              
```

I was expecting this app to run on x64 since it targets .NET 3.1. I didn't validate this with an app that doesn't specify `LatestMajor` rollforward, but I assume that property is not being consulted/honored.

At present, I'm consider this incorrect behavior. That's a dupe of https://github.com/dotnet/sdk/issues/17241.

### PR DESCRIPTION
**Pull request by mateoatr**
Fixes #19743. I tested this locally. The steps for reproing the fix are already in the above issue. For checking the app's architecture, this first checks for the `RuntimeIdentifier` property of the project to run, if not set, it'll grab the architecture from the `DefaultAppHostRuntimeIdentifier` prop.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-run/RunCommand.cs [hunk 1]
```diff
@@ -254,10 +255,15 @@ private ICommand GetTargetCommand()
...
                 .WorkingDirectory(runWorkingDirectory);
 
-            var rootVariableName = Environment.Is64BitProcess ? "DOTNET_ROOT" : "DOTNET_ROOT(x86)";
-            if (Environment.GetEnvironmentVariable(rootVariableName) == null)
+            if ((TryGetTargetArchitecture(project.GetPropertyValue("RuntimeIdentifier"), out var targetArchitecture) ||
+                TryGetTargetArchitecture(project.GetPropertyValue("DefaultAppHostRuntimeIdentifier"), out targetArchitecture)) &&
+                targetArchitecture == RuntimeInformation.ProcessArchitecture)
             {
-                command.EnvironmentVariable(rootVariableName, Path.GetDirectoryName(new Muxer().MuxerPath));
+                var rootVariableName = Environment.Is64BitProcess ? "DOTNET_ROOT" : "DOTNET_ROOT(x86)";
```
Comment (vitek-karas) [inline src/Cli/dotnet/commands/dotnet-run/RunCommand.cs:262]: Have you considered setting `DOTNET_ROOT_arch` for net6.0+ projects? (I know it's not necessary, but would be quite nice).

**Review by vitek-karas — APPROVED** [review]
Looks good - please wait for SDK owners to also review this.

File: src/Assets/TestProjects/TestAppEchoDotnetRoot/Program.cs [hunk 2]
```diff
@@ -2,15 +2,18 @@
...
 using System;
+using System.Runtime.InteropServices;
 
 namespace ConsoleApplication
 {
     public class Program
     {
         public static void Main(string[] args)
         {
+            var processArchitecture = $"DOTNET_ROOT_{RuntimeInformation.ProcessArchitecture.ToString().ToUpper()}";
```
Comment (richlander) [inline src/Assets/TestProjects/TestAppEchoDotnetRoot/Program.cs:13]: Does this work in globalization invariant mode?

Comment (richlander) [reply src/Assets/TestProjects/TestAppEchoDotnetRoot/Program.cs:13]: I guess this is just a test so it probably doesn't matter.

**Comment by richlander** [comment]
Can/will enthusiastically test this as soon as there is a build.

**Review by sfoslund — APPROVED** [review]

File: src/Assets/TestProjects/TestAppEchoDotnetRoot/Program.cs (hunk 2 above)
Comment (mateoatr) [reply src/Assets/TestProjects/TestAppEchoDotnetRoot/Program.cs:13]: Note that this is also done in RunCommand. I changed to `Enum.GetName` in both places.

Comment (vitek-karas) [reply src/Assets/TestProjects/TestAppEchoDotnetRoot/Program.cs]: This will change the casing though - will the host work correctly with that?
I think on Windows environment variables are case insensitive, while on Linux they are case sensitive. The host asks for upper case - always. So I think this will effectively break on mac, right?

Would it be a problem to use ToUpperInvariant() instead?

**Comment by Algorithman** [comment]
Question: Is this already in the release/when will this be in the installer?

**Comment by vitek-karas** [comment]
This fix is in .NET 6 GA - so if you download the final release of .NET 6, it should be there.

**Comment by Algorithman** [comment]
Thx. Correct if i'm wrong, i need to uninstall .net5 then?

**Comment by vitek-karas** [comment]
You should not need to uninstall .NET 5. The SDKs are side by side - so both can be installed. By default commands like `dotnet run` should pick the latest version (so if you have .NET6 it should use .NET 6). Unless you're using `global.json` files which can specify exact SDK version to use.

You can try this by running `dotnet --info` from the directory where you would run `dotnet run`. It should print out something like:
```console
.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.21573.3
 Commit:    a2bb0dde82
```

Which will contain the exact SDK version used by the command (and `dotnet run` should use the same version).
