### PR TITLE
Override default properties with custom file-level directives

### LINKED ISSUE #49177: `dotnet project convert` works incorrectly for target framework other than default base framework `net10.0`
### Describe the bug
`dotnet project convert` works incorrectly for target framework other than default base framework `net10.0`

### To Reproduce

A WinForms sample and it works correctly with `dotnet run Forms.cs` (assuming the file is saved as Forms.cs)

```cs
#:property TargetFramework net10.0-windows
#:property UseWindowsForms true
#:property OutputType WinExe

Application.Run(new Form() { Text = "Hello C#" });
```

When tried to convert it to a project with the command `dotnet project convert Forms.cs`, the output contains duplicated content.

The default property of the base target framework is always included which is incorrect and it should be based on the file input.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

</Project>
```

### Exceptions (if any)

None.

### Further technical details
- 10.0.100-preview.4.25258.110
- CLI

### PR DESCRIPTION
**Pull request by jjonescz**
Resolves https://github.com/dotnet/sdk/issues/49177.

I've also consolidated the project writing logic so each "section" is responsible for its own trailing blank line.

### CODE REVIEW

File: src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs [hunk 1]
```diff
@@ -61,6 +61,18 @@ internal sealed class VirtualProjectBuildingCommand : CommandBase
         "MSBuild.rsp",
     ];
 
+    /// <remarks>
+    /// Kept in sync with the default <c>dotnet new console</c> project file (enforced by <c>DotnetProjectAddTests.SameAsTemplate</c>).
+    /// </remarks>
+    private static readonly FrozenDictionary<string, string> s_defaultProperties = FrozenDictionary.Create<string, string>(StringComparer.OrdinalIgnoreCase,
+    [
+        new("OutputType", "Exe"),
+        new("TargetFramework", "net10.0"),
```
Comment (MiYanni) [inline src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs:70]: Any reason we can't use `ToolsetInfo.CurrentTargetFramework` here? I think that's the right value.

File: test/dotnet.Tests/CommandTests/Project/Convert/DotnetProjectConvertTests.cs [hunk 2]
```diff
@@ -670,6 +669,44 @@ public void Directives()
...
+    /// </summary>
+    [Fact]
+    public void Directives_AllDefaultOverridden()
+    {
+        VerifyConversion(
+            inputCSharp: """
+                #!/program
+                #:sdk Microsoft.NET.Web.Sdk
+                #:property OutputType=Exe
+                #:property TargetFramework=net11.0
```
Comment (MiYanni) [inline test/dotnet.Tests/CommandTests/Project/Convert/DotnetProjectConvertTests.cs]: `main` for the SDK is not `net11` yet.

File: test/dotnet.Tests/CommandTests/Project/Convert/DotnetProjectConvertTests.cs [hunk 3]
```diff
@@ -670,6 +669,44 @@ public void Directives()
...
+                #:property Custom=1
+                #:property ImplicitUsings=disable
+                Console.WriteLine();
+                """,
+            expectedProject: """
+                <Project Sdk="Microsoft.NET.Web.Sdk">
+
+                  <PropertyGroup>
+                    <OutputType>Exe</OutputType>
+                    <TargetFramework>net11.0</TargetFramework>
```
Comment (MiYanni) [inline test/dotnet.Tests/CommandTests/Project/Convert/DotnetProjectConvertTests.cs]: Same here.

**Review by MiYanni — APPROVED** [review]

File: src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs (hunk 1 above)
Comment (jjonescz) [reply src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs:70]: `ToolsetInfo` is only available in tests. I'm introducing a product equivalent in https://github.com/dotnet/sdk/pull/49528 and once that's merged I expect it to be used here (there will be conflicts that will remind me to do that).

File: test/dotnet.Tests/CommandTests/Project/Convert/DotnetProjectConvertTests.cs (hunk 2 above)
Comment (jjonescz) [reply test/dotnet.Tests/CommandTests/Project/Convert/DotnetProjectConvertTests.cs]: I know, this is supposed to be a different version for testing, I can probably use something like `net472` to make that clearer.

**Review by RikkiGibson — APPROVED** [review]

**Comment by jjonescz** [comment]
@jaredpar for a review, thanks

**Comment by jjonescz** [comment]
@333fred for a review, thanks

File: src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs [hunk 4]
```diff
@@ -645,33 +657,37 @@ public static void WriteProjectFile(
...
-                <OutputType>Exe</OutputType>
-                <TargetFramework>net10.0</TargetFramework>
-                <ImplicitUsings>enable</ImplicitUsings>
-                <Nullable>enable</Nullable>
-                <PublishAot>true</PublishAot>
-              </PropertyGroup>
-            """);
+        // Write default properties unless they are overridden by custom directives.
+        var propertyDirectiveNames = propertyDirectives.Select(d => d.Name).ToHashSet(StringComparer.OrdinalIgnoreCase);
+        if (!s_defaultProperties.Keys.All(propertyDirectiveNames.Contains))
```
Comment (333fred) [inline src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs]: Honestly, this feels pretty complicated. It took me a few seconds to even understand what this line was doing. Why do we need to have many different property groups? Why not just open a property group, write the default ones (unless the user specified them), then EnableDefaultCompileItems, then any user-defined properties, all in one group?

Comment (333fred) [reply src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs]: At the very least, I'd remove this check, and do something more like this, for clarity:

```cs
bool openedDefaultGroup = false;
foreach (var (name, value) in s_defaultProperties)
{
    if (!propertyDirectiveNames.Contains(name))
    {
        if (!openedDefaultGroup)
        {
            openedDefaultGroup = true;
            writer.WriteLine("  <PropertyGroup>");
        }

        writer.WriteLine($"""
            <{name}>{EscapeValue(value)}</{name}>
        """);
    }
}
if (openedDefaultGroup)
{
    writer.WriteLine("  </PropertyGroup>");
    writer.WriteLine();
}
```

File: src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs [hunk 5]
```diff
@@ -645,33 +657,37 @@ public static void WriteProjectFile(
...
+                        """);
+                }
+            }
+            writer.WriteLine("  </PropertyGroup>");
+            writer.WriteLine();
+        }
 
         if (isVirtualProject)
         {
             writer.WriteLine("""
```
[the remark this answers is not in the document]
Comment (333fred) [reply src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs]: Personally, I would also agree with copilot here.

[the remark this answers is not in the document]
Comment (jjonescz) [reply src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs]: > either always use raw string literals or always use WriteLine with interpolated strings

I'm not sure what is being suggested here. Why would I use WriteLine with interpolated strings when I don't need anything interpolated? And when I'm using interpolated strings, they _are_ raw string literals.

File: src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs (hunk 4 above)
Comment (jjonescz) [reply src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs]: > Why do we need to have many different property groups? Why not just open a property group, write the default ones (unless the user specified them), then EnableDefaultCompileItems, then any user-defined properties, all in one group?

Sounds good to me, I will simplify like that.

File: src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (333fred) [reply src/Cli/dotnet/Commands/Run/VirtualProjectBuildingCommand.cs]: Oh, the suggested fix is bogus. I'm talking about the mix of raw vs non-raw

**Review by 333fred — APPROVED** [review]
