### PR TITLE
Ensure case-insensitive web.config file name is used

### LINKED ISSUE #14853: [Linux-only] aspnetcore publish can produce 2 web.configs
# Description

Asp net core projects being published on linux have the possibility to publish 2 disjoint web.config files. This happens when the project references `Web.config`. It appears that the publish task ignores this file, resulting in both `Web.config` and `web.config` in the publish directory.

e.g.
image

Web.config:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <system.web>
    </system.web>
</configuration>
```

web.config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="dotnet" arguments=".\dotnet-linux-publish-example.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
    </system.webServer>
  </location>
<configuration>
```

Note this behavior is not observed on Windows or OSX

# Downstream affects

Due to this behavior, any configuration in `Web.config` will not be available in `web.config`. Following that - if the published artifacts are deployed (say to azure app services), i've noticed that `web.config` is discarded, resulting in a corrupt deployment

# How to reproduce

This can be reproduced by publishing an example web api project in the .net 5.0 sdk docker container

https://github.com/scott-the-programmer/dotnet-linux-publish-example

```bash
docker build . -t example
docker run -it example bash
```

observe that there are 2 web.configs in the publish dir

### PR DESCRIPTION
**Pull request by scott-the-programmer**
## Description

This PR attempts to resolve [issue 14853](https://github.com/dotnet/sdk/issues/14853)

Currently, linux environments will fail to retrieve a `Web.config` file if the case does not match `web.config`. This results in the users version of `Web.config` from not being loaded and passed to `WebConfigTransform`, producing an incorrect result.

This PR fixes the issue by searching for the web.config file in the project directory, before passing it to the WebConfigTransform step

## Tests

* Added a series of "integration" tests for the TransformWebConfig task ✅ 
* Test for regression on an OSX System ✅ 
* Compile and test this on a Linux system (Kernel 5.4.78-1-lts) ✅ 
* Test for regression on a Linux System ✅ 
* Test for regression on a Windows System ✅

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=14854) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=14854) before we can accept your contribution.<br/><br/>:x: scott-the-programmer [sign now](https://cla.dotnetfoundation.org/dotnet/sdk?pullRequest=14854)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/sdk?pullRequest=14854) it.</sub>

**Comment by scott-the-programmer** [comment]
Hey @vijayrkn - would you be able to review this PR please? Thanks!

**Comment by scott-the-programmer** [comment]
@vijayrkn bump :)

File: src/WebSdk/Publish/Tasks/Tasks/TransformWebConfig.cs [hunk 1]
```diff
@@ -138,5 +144,23 @@ public override bool Execute()
...
+        /// Searches for an existing (case-insensitive) `Web.config` file. Otherwise defaults to defaultWebConfigName
+        /// </summary>
+        /// <param name="projectPath">Full path to project file</param>
+        /// <param name="defaultWebConfigName">Web Config file name to search for i.e. `web.config`</param> 
+        /// <returns></returns>
+        public string GetWebConfigFileOrDefault(string projectPath, string defaultWebConfigName)
+        {
+            var projectDirectory = Path.GetDirectoryName(projectPath);
+            var currentWebConfigFileName = Directory.EnumerateFiles(projectDirectory)
+                .FirstOrDefault(file => string.Equals(Path.GetFileName(file), defaultWebConfigName, StringComparison.CurrentCultureIgnoreCase));
```
Comment (vijayrkn) [inline src/WebSdk/Publish/Tasks/Tasks/TransformWebConfig.cs:158]: Thanks for making this change. it would be best to change this to [StringComparison.OrdinalIgnoreCase](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison#system-stringcomparison-ordinalignorecase) instead.

**Review by vijayrkn — CHANGES_REQUESTED** [review]
I have left one minor comment and once it is fixed, I will approve the change.

**Comment by scott-the-programmer** [comment]
> I have left one minor comment and once it is fixed, I will approve the change.

Thanks for reviewing @vijayrkn! Made the string comparison change and confirmed that the fix still works (tested on `EndeavourOS Linux x86_64`)

**Review by vijayrkn — APPROVED** [review]

**Comment by vijayrkn** [comment]
@scott-the-programmer - All the tests have passed & I have merged the changes. Thank you for your contribution!
