### PR TITLE
Fix duplicate resolved files to publish

### LINKED ISSUE #3257: Double write during publish
Publishing a self-contained WPF template app writes some files twice because `ResolvedFileToPublish` has the same dll from different runtime packs (for example, Microsoft.Win32.Registry.dll comes from both netcoreapp and the windowsdesktop pack).
This causes crossgen failures when used together with `PublishReadyToRun=true`.

Looks very similar to https://github.com/dotnet/sdk/issues/3035 which was addressed in https://github.com/dotnet/sdk/pull/3021, but I'm still seeing this with version `3.0.100-preview6-012031`.

/cc @fadimounir @nguerrera @peterhuene 

edit: it fails during `PublishReadyToRun=true` only when used together with the linker. Without linking, the duplicates are already crossgen'd, and so they don't hit the failure. In any case, `ResolvedFileToPublish` has duplicates that shouldn't be there, and we end up with `DoubleWrites` of some files.

image

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #3257 

There were two issues.

1. A misunderstanding of msbuild batching rules and unqualified metadata caused satellite assemblies to be included twice (from same source location) into the publish list. (See https://github.com/microsoft/msbuild/issues/4429)
2. There are assemblies with the same name and version in multiple frameworks. We have to choose one arbitrarily.

### CODE REVIEW

File: src/Tasks/Common/ConflictResolution/ConflictResolver.cs [hunk 1]
```diff
@@ -349,6 +349,25 @@ private TConflictItem ResolveConflict(TConflictItem item1, TConflictItem item2,
...
+                //
+                // We choose ordinal string comparison of package id as a final tie-breaker for this case. 
+                // We will get here in the real case of frameworks with overlapping assemblies (including 
+                // version) and self-contained apps. The assembly we choose here is not guaranteed to match
+                // the assembly that would be chosen by the host for a framework-dependent app. The host
+                // is free to make its own deterministic but arbitrary choice.
+                int cmp = string.CompareOrdinal(item1.PackageId, item2.PackageId);
+                if (cmp != 0)
+                {
+                    return cmp < 0 ? item1 : item2;
```
Comment (nguerrera) [inline src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: There should probably be logging here, but I want to make a pass over all the logging in this task: see #3319

File: src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets [hunk 2]
```diff
@@ -553,8 +553,8 @@ Copyright (c) .NET Foundation. All rights reserved.
     <ItemGroup>
       <_ResolvedCopyLocalPublishAssets Include="@(ReferenceCopyLocalPaths)"
                                        Exclude="@(_ResolvedCopyLocalBuildAssets);@(RuntimePackAsset)"
-                                       Condition="'$(PublishReferencesDocumentationFiles)' == 'true' or '%(Extension)' != '.xml'">
-        <DestinationSubPath>%(ReferenceCopyLocalPaths.DestinationSubDirectory)%(Filename)%(Extension)</DestinationSubPath>
+                                       Condition="'$(PublishReferencesDocumentationFiles)' == 'true' or '%(ReferenceCopyLocalPaths.Extension)' != '.xml'">
+        <DestinationSubPath>%(ReferenceCopyLocalPaths.DestinationSubDirectory)%ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)</DestinationSubPath>
```
Comment (peterhuene) [inline src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets]: Is this not missing a `(`?

```suggestion
        <DestinationSubPath>%(ReferenceCopyLocalPaths.DestinationSubDirectory)%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)</DestinationSubPath>
```

Comment (nguerrera) [reply src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets]: No idea how the test passed. Will investigate. Correction applied.

Comment (peterhuene) [reply src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets]: It looks like `DestinationSubPath` isn't used, and `RelativePath` is set based on `DestinationSubDirectory` [here](https://github.com/dotnet/sdk/blob/c561c3f7e1ad8da7db424c75338c9d81623b2d99/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L410).

Comment (peterhuene) [reply src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets]: That is to say, it isn't being used by the targets that follow.  I think it would get used for deps file generation, but that doesn't depend on this target.

File: src/Tasks/Common/ConflictResolution/ConflictResolver.cs [hunk 3]
```diff
@@ -349,6 +349,25 @@ private TConflictItem ResolveConflict(TConflictItem item1, TConflictItem item2,
...
+                // one of them can be copied locally. The policy here must be deterministic, but it can
+                // be chosen arbitrarily. The assumption is that the assemblies are fully semantically 
+                // equivalent.
+                //
+                // We choose ordinal string comparison of package id as a final tie-breaker for this case. 
+                // We will get here in the real case of frameworks with overlapping assemblies (including 
+                // version) and self-contained apps. The assembly we choose here is not guaranteed to match
+                // the assembly that would be chosen by the host for a framework-dependent app. The host
+                // is free to make its own deterministic but arbitrary choice.
+                int cmp = string.CompareOrdinal(item1.PackageId, item2.PackageId);
```
Comment (dsplaisted) [inline src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: Is it worth first comparing the length for perf?

File: src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs [hunk 4]
```diff
@@ -501,8 +501,11 @@ public void It_fails_if_nobuild_was_requested_but_build_was_invoked()
                 .HaveStdOutContaining("NETSDK1085");
         }
 
-        [Fact]
-        public void It_contains_no_duplicates_in_resolved_publish_assets()
+        [Theory]
+        [InlineData("windows")]
```
Comment (dsplaisted) [inline src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs]: The "windows" test needs to be under a `WindowsOnlyFact`

File: src/Tasks/Common/ConflictResolution/ConflictResolver.cs [hunk 5]
```diff
@@ -349,6 +349,25 @@ private TConflictItem ResolveConflict(TConflictItem item1, TConflictItem item2,
                 return item2;
             }
 
+            if (item1.ItemType == ConflictItemType.CopyLocal && item2.ItemType == ConflictItemType.CopyLocal)
```
Comment (dsplaisted) [inline src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: I'm wondering if it's possible to have 3 items conflict, where the first one is not CopyLocal, and the second two ones are CopyLocal.  Then the CopyLocal items would not be compared against each other, and you could still have double writes.

**Review by dsplaisted — APPROVED** [review]

File: src/Tasks/Common/ConflictResolution/ConflictResolver.cs (hunk 3 above)
Comment (nguerrera) [reply src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: I decided not to bother. I will be doing some perf measurements.

File: src/Tasks/Common/ConflictResolution/ConflictResolver.cs (hunk 5 above)
Comment (nguerrera) [reply src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: Do you know how I might repro that?

File: src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs (hunk 4 above)
Comment (nguerrera) [reply src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs]: I put a sloppy, if + return in this: https://github.com/dotnet/sdk/compare/f0a30eecf14d6b93e656aed045a907525e5342ee..925903a4c3ff5a1ad2651d2f784ac062e63d9e04

I can refactor to a WindowsOnlyFact.

File: src/Tasks/Common/ConflictResolution/ConflictResolver.cs (hunk 5 above)
Comment (dsplaisted) [reply src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: No, I'm not sure if it's actually possible.  If it looks like it won't happen based on code inspection then we can leave it be.

File: src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs (hunk 4 above)
Comment (dsplaisted) [reply src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs]: Either way is fine with me.

File: src/Tasks/Common/ConflictResolution/ConflictResolver.cs (hunk 5 above)
Comment (nguerrera) [reply src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: It appears to be possible if you have a `Reference` to this file and two copy local items. Trying to repro.

Comment (nguerrera) [reply src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: I think it would have to be a Reference without Private=false, which would never come from a package.  Even so, not managing to repro.

Comment (nguerrera) [reply src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: It still ends up comparing the two CopyLocal items in this case, still trying to understand if that's guaranteed.

Comment (nguerrera) [reply src/Tasks/Common/ConflictResolution/ConflictResolver.cs]: It can't happen for the publish case because we inky pass _ResolvedCopyLocalPublishAssets to ResolvePackageFileConflicts and they will all be CopyLocal and we will pick a winner among them. So it's definitely sufficient for the bug this claims to fix for publish. If you have a file reference to the exact same file version without Private="false", then there will be duplicates in ReferenceCopyLocalPaths when RAR finishes, though. I think this is edge enough to leave for another fight. I can't construct a real scenario.

File: src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs (hunk 4 above)
Comment (nguerrera) [reply src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishAHelloWorldProject.cs]: I went ahead and cleaned it up in aaa271b

**Review by peterhuene — APPROVED** [review]
