### PR TITLE
Fix Hot Reload profile detection for web apps

### LINKED ISSUE #48898: dotnet watch on the AppHost regularly breaks with a Blazor WASM project
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I have a simple aspnetcore backend and blazor wasm standalone frontend setup with aspire.

<details><summary>AppHost Program.cs</summary>
<p>

```
var builder = DistributedApplication.CreateBuilder(args);

var api = builder.AddProject<Projects.Debtware_Client_Portal_Api>("api");

var ui = builder.AddProject<Projects.Debtware_Client_Portal>("ui").WithReference(api).WaitFor(api);

builder.Build().Run();
```

</p>
</details> 

I am running the whole application using `dotnet watch` on Aspire AppHost project.

<details><summary>dotnet watch startup output</summary>
<p>

PS [REDACTED_PATH]> dotnet watch --property WarningLevel=0
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch ⌚ Building [REDACTED_PATH]\Revive.AppHost.csproj ...
dotnet watch 🔨 Build succeeded: [REDACTED_PATH]\Revive.AppHost.csproj
Using launch settings from [REDACTED_PATH]\Properties\launchSettings.json...
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 9.2.0+0fcb1e9885266c1700c49c16513a6d97480bb058
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: [REDACTED_PATH]
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: https://localhost:17243
info: Aspire.Hosting.DistributedApplication[0]
      Login to the dashboard at https://localhost:17243/login?t=78a9e160d0643e70a21fc9a73be7c4cc
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.
Using launch settings from [REDACTED_PATH]\Properties\launchSettings.json...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:54175
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: [REDACTED_PATH]

</p>
</details> 

However, when making standard hot reload changes to the WASM project (not dirty, or dirty), then the change succeeds, and follows up immediately crashing the whole program.

See the output & stacktrace here

```
dotnet watch ⌚ File updated: [REDACTED_PATH]\IACustomerPackSection.razor
dotnet watch 🔥 [Debtware.Client.Portal.Api (net9.0)] Hot reload succeeded.
dotnet watch 🔥 [Debtware.Client.Portal (net9.0)] Hot reload succeeded.
dotnet watch ❌ [Debtware.Client.Portal.Api (net9.0)] Exited with error code -1
dotnet watch ❌ [Debtware.Client.Portal (net9.0)] Exited with error code -1
dotnet watch ❌ [Revive.AppHost (net9.0)] Exited with error code -1
dotnet watch ❌ System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Watch.BlazorWebAssemblyDeltaApplier.Apply(ImmutableArray`1 updates, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.BlazorWebAssemblyHostedDeltaApplier.Apply(ImmutableArray`1 updates, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.CompilationHandler.<>c__DisplayClass20_0.<<HandleFileChangesAsync>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Watch.CompilationHandler.HandleFileChangesAsync(Func`3 restartPrompt, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.Program.RunAsync()
dotnet watch ❌ An unexpected error occurred

```

### Expected Behavior

The hot reload succeeds without crashing the entire apphost process.

### Steps To Reproduce

I got an even earlier error while setting up a minimal repro.

I created this project https://github.com/Hona/AspireWasmCrash
Then - `dotnet run` on the host starts fine and the UI is responsive.
Then - `dotnet watch` on the host errors immediately.

Here is the output of both combined.

<details><summary>run vs watch output</summary>
<p>

PS C:\Repos\AspireWasmCrash\AspireWasmCrash> dotnet watch --property WarningLevel=0

dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch ⌚ Building C:\Repos\AspireWasmCrash\AspireWasmCrash\AspireWasmCrash.csproj ...
dotnet watch 🔨 Build succeeded: C:\Repos\AspireWasmCrash\AspireWasmCrash\AspireWasmCrash.csproj
dotnet watch ❌ [AspireWasmCrash (net9.0)] Exited with error code -1
dotnet watch ❌ System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Watch.BlazorWebAssemblyDeltaApplier.WaitForProcessRunningAsync(CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.RunningProject.WaitForProcessRunningAsync(CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.Program.RunAsync()
dotnet watch ❌ An unexpected error occurred
PS C:\Repos\AspireWasmCrash\AspireWasmCrash> dotnet run
Using launch settings from C:\Repos\AspireWasmCrash\AspireWasmCrash\Properties\launchSettings.json...
Building...
info: Aspire.Hosting.DistributedApplication[0]
      Aspire version: 9.0.0+01ed51919f8df692ececce51048a140615dc759d
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application starting.
info: Aspire.Hosting.DistributedApplication[0]
      Application host directory is: C:\Repos\AspireWasmCrash\AspireWasmCrash
info: Aspire.Hosting.DistributedApplication[0]
      Now listening on: https://localhost:17078
info: Aspire.Hosting.DistributedApplication[0]
      Login to the dashboard at https://localhost:17078/login?t=d86d6d466f55d44a04ccffb4fedee39e
info: Aspire.Hosting.DistributedApplication[0]
      Distributed application started. Press Ctrl+C to shut down.

</p>
</details> 

### Exceptions (if any)

_No response_

### .NET Version info

```
PS C:\Repos\Revive2\src\Hosting\Revive.AppHost> dotnet --info
.NET SDK:
 Version:           9.0.203
 Commit:            dc7acfa194
 Workload version:  9.0.200-manifests.1e5233e8
 MSBuild version:   17.13.20+a4ef1e90f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.203\

.NET workloads installed:
 [aspire]
   Installation Source: SDK 9.0.200, VS 17.13.35806.99
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: SDK 9.0.200
   Manifest Version:    9.0.4/9.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100\microsoft.net.workload.mono.toolchain.current\9.0.4\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.4
  Architecture: x64
  Commit:       f57e6dc747

.NET SDKs installed:
  8.0.311 [C:\Program Files\dotnet\sdk]
  8.0.408 [C:\Program Files\dotnet\sdk]
  9.0.105 [C:\Program Files\dotnet\sdk]
  9.0.200 [C:\Program Files\dotnet\sdk]
  9.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Repos\Revive2\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tmat**
dotnet-watch logic that distinguishes between hosted and standalone Blazor projects should not be applied to non-web projects (e.g. Aspire).

Fixes https://github.com/dotnet/sdk/issues/48898

### CODE REVIEW

**Comment by tmat** [comment]
@DustinCampbell @phil-allen-msft ptal

File: src/BuiltInTools/dotnet-watch/Internal/IReporter.cs [hunk 1]
```diff
@@ -48,36 +48,47 @@ public bool TryGetMessage(string? prefix, object?[] args, [NotNullWhen(true)] ou
...
+        public static readonly MessageDescriptor FileAdditionTriggeredReEvaluation = new("File addition triggered re-evaluation.", WatchEmoji, MessageSeverity.Verbose, s_id++);
+        public static readonly MessageDescriptor NoCSharpChangesToApply = new("No C# changes to apply.", WatchEmoji, MessageSeverity.Output, s_id++);
+        public static readonly MessageDescriptor Exited = new("Exited", WatchEmoji, MessageSeverity.Output, s_id++);
+        public static readonly MessageDescriptor ExitedWithUnknownErrorCode = new("Exited with unknown error code", ErrorEmoji, MessageSeverity.Error, s_id++);
+        public static readonly MessageDescriptor ExitedWithErrorCode = new("Exited with error code {0}", ErrorEmoji, MessageSeverity.Error, s_id++);
+        public static readonly MessageDescriptor SkippingConfiguringBrowserRefresh_SuppressedViaEnvironmentVariable = new("kipping configuring browser-refresh middleware since its refresh server suppressed via environment variable {0}.", WatchEmoji, MessageSeverity.Verbose, s_id++);
```
Comment (Hona) [inline src/BuiltInTools/dotnet-watch/Internal/IReporter.cs:89]:
```suggestion
        public static readonly MessageDescriptor SkippingConfiguringBrowserRefresh_SuppressedViaEnvironmentVariable = new("Skipping configuring browser-refresh middleware since its refresh server suppressed via environment variable {0}.", WatchEmoji, MessageSeverity.Verbose, s_id++);
```

File: src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfileReader.cs [hunk 2]
```diff
@@ -11,44 +11,48 @@ internal static class HotReloadProfileReader
...
-                            return HotReloadProfile.BlazorHosted;
+                            aspnetCoreProject = currentNode.ProjectInstance;
+                            break;
                         }
 
-                        reporter.Verbose("HotReloadProfile: BlazorWebAssembly.", emoji: "🔥");
-                        return HotReloadProfile.BlazorWebAssembly;
+                        if (item.EvaluatedInclude == "WebAssembly")
+                        {
+                            // We saw a previous project that was AspNetCore. This must he a blazor hosted app.
```
Comment (phil-allen-msft) [inline src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfileReader.cs:38]: What if you receive the nodes in the opposite order (WebAssembly is in the list, and later AspNetCore)?

File: src/BuiltInTools/dotnet-watch/Internal/IReporter.cs [hunk 3]
```diff
@@ -48,36 +48,47 @@ public bool TryGetMessage(string? prefix, object?[] args, [NotNullWhen(true)] ou
...
+        public static readonly MessageDescriptor UpdatesApplied = new("Updates applied: {0} out of {1}.", HotReloadEmoji, MessageSeverity.Verbose, s_id++);
         public static readonly MessageDescriptor WaitingForFileChangeBeforeRestarting = new("Waiting for a file to change before restarting ...", "⏳", MessageSeverity.Warning, s_id++);
-        public static readonly MessageDescriptor WatchingWithHotReload = new("Watching with Hot Reload.", "⌚", MessageSeverity.Verbose, s_id++);
+        public static readonly MessageDescriptor WatchingWithHotReload = new("Watching with Hot Reload.", WatchEmoji, MessageSeverity.Verbose, s_id++);
         public static readonly MessageDescriptor RestartInProgress = new("Restart in progress.", "🔄", MessageSeverity.Output, s_id++);
         public static readonly MessageDescriptor RestartRequested = new("Restart requested.", "🔄", MessageSeverity.Output, s_id++);
         public static readonly MessageDescriptor ShutdownRequested = new("Shutdown requested. Press Ctrl+C again to force exit.", "🛑", MessageSeverity.Output, s_id++);
```
Comment (phil-allen-msft) [inline src/BuiltInTools/dotnet-watch/Internal/IReporter.cs:74]: One more emoji for the "Red Circle"?

File: src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfileReader.cs (hunk 2 above)
Comment (tmat) [reply src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfileReader.cs:38]: It doesn't matter since the condition `aspnetCoreProject is not null && aspnetCoreProject != currentNode.ProjectInstance` would exclude projects that have both capabilities anyways.

Comment (tmat) [reply src/BuiltInTools/dotnet-watch/HotReload/HotReloadProfileReader.cs:38]: I'll follow up with adding a blazor hosted test, seems like we don't have one

**Review by phil-allen-msft — APPROVED** [review]
