### PR TITLE
Use project directory as a working directory for Aspire processes

### LINKED ISSUE #9142: Azure Functions project starts with incorrect working directory via `dotnet watch`
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using aspire together with an Azure Functions project and `dotnet watch`, the following issue occurs:

Aspire uses the DCP protocol to instruct `dotnet watch` to start a process. However, `dotnet watch` launches the process using the *current* working directory, not the actual project directory.

This breaks Azure Functions projects, as the `func` CLI tool (Azure Functions Core Tools) **must** run from the correct working directory. Otherwise, it fails to detect and start the project properly. While `func` supports a `--script-root` argument to manually specify the working directory, it is currently not being set.

### Expected Behavior

The Functions project should start correctly, either because:
- `func` is launched from the correct working directory, **or**
- the `--script-root` parameter is explicitly set to the project directory.

### Steps To Reproduce

1. Add an Azure Functions project to an Aspire solution.
2. Start the solution using `dotnet watch`.
3. The Functions project fails to start because `func` is executed from the wrong directory.

### Exceptions (if any)

After starting the host with dotnet watch, you can see the following in the functions app console.
`Unable to find project root. Expecting to find one of host.json, local.settings.json in project root.`

### .NET Version info

_No response_

### Possible Solutions

1. Modify `AddAzureFunctionsProject(...)` to include the `--script-root` argument.
2. Modify `dotnet watch` to always launch processes in the respective project’s working directory. 
3. Extend the DCP protocol to include a working directory parameter that can be passed along to `dotnet watch`.

The problem IMO is that the DcpExecutor sets the "right" working directory on the ExecutionSpec.

https://github.com/dotnet/aspire/blob/38591121f7667cc5c6b9d7e17cd086d4909c1d6c/src/Aspire.Hosting/Dcp/DcpExecutor.cs#L844

However, the DCP Protocol doesn't mention the working directory at all.
This arguably shouldn't be an implementation detail?

### PR DESCRIPTION
**Pull request by tmat**
Fixes https://github.com/dotnet/aspire/issues/9142

### CODE REVIEW

File: src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs [hunk 1]
```diff
@@ -211,7 +211,7 @@ private ProjectOptions GetProjectOptions(ProjectLaunchRequest projectLaunchInfo)
             {
                 IsRootProject = false,
                 ProjectPath = projectLaunchInfo.ProjectPath,
-                WorkingDirectory = _projectLauncher.EnvironmentOptions.WorkingDirectory,
+                WorkingDirectory = Path.GetDirectoryName(projectLaunchInfo.ProjectPath) ?? throw new InvalidOperationException(),
```
Comment (phil-allen-msft) [inline src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs:214]: I understand how this fixes the reported problem.  If a project needed a special working directory besides the root of the project, how could it do so? (thinking for 'web' projects, using wwwroot instead of the project root)

Comment (tmat) [reply src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs:214]: The directory can be specified in launch profile

Comment (tmat) [reply src/BuiltInTools/dotnet-watch/Aspire/AspireServiceFactory.cs:214]: This is handled by dotnet run.

**Review by phil-allen-msft — APPROVED** [review]
