### PR TITLE
Forward FSI help to the actual binary

### LINKED ISSUE #13520: `dotnet fsi --help` does not show option help
**Repro steps**

1. Run `dotnet fsi --help` or `dotnet fsi -?` or `dotnet fsi -h` in the command line

**Expected behavior**

Options should be listed, according to https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-interactive-options

**Actual behavior**

No options are shown, and a sort of recursive suggestion of using the same options that were used is shown.

```powershell
PS > dotnet fsi --help
Description:

Usage:
  dotnet fsi [options]

Options:
  -?, -h, --help  Show command line help.
```

**Known workarounds**

View the options here: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-interactive-options

**Related information**

Provide any related information (optional):

* Operating system: Windows 11 and Ubuntu (via WSL2)
* .NET Runtime kind (.NET Core, .NET Framework, Mono): F# Interactive version 12.0.4.0 for F# 6.0
* Editing Tools (e.g. Visual Studio Version, Visual Studio): n/a

### PR DESCRIPTION
**Pull request by baronfel**
Closes https://github.com/dotnet/fsharp/issues/13520

Unlike other forwarded commands, the `dotnet fsi` command didn't forward help to the forwarded application. As a result, help was what the SDK command had defined, which is very little. This plumbs the help command the same way we've done for other such commands.

### CODE REVIEW

File: src/Cli/dotnet/Parser.cs [hunk 1]
```diff
@@ -279,6 +279,9 @@ public override void Write(HelpContext context)
                 {
                     new DotnetFormatForwardingApp(helpArgs).Execute();
                 }
+                else if (command.Name.Equals(FsiCommandParser.GetCommand().Name)){
```
Comment (kasperk81) [inline src/Cli/dotnet/Parser.cs:282]:
```suggestion
                else if (command.Name.Equals(FsiCommandParser.GetCommand().Name))
                {
```

Comment (baronfel) [reply src/Cli/dotnet/Parser.cs]: Thanks for this! My kingdom for an explicit format step I could run before push.

**Review by marcpopMSFT — APPROVED** [review]

**Comment by bmitc** [comment]
Thanks to @baronfel for such a quick fix and to others for reviewing, approving, and merging so fast! (I was the one who filed https://github.com/dotnet/fsharp/issues/13520.)
