### PR TITLE
Fix not failing when build fails

### LINKED ISSUE #4683: dotnet test build failures are not reported in terminal logger, and run succeeds
## Describe the bug

Running project from https://github.com/microsoft/testfx/issues/4682 leads to dll conflicts. Those conflicts are reported from msbuild but not to screen as errors. Leading to successful run.

## Steps To Reproduce

$env:DOTNET_CLI_TESTINGPLATFORM_ENABLE=1; dotnet test -bl

## Expected behavior

When there is build failure all projects should be reported, and run should fail.

## Actual behavior

Errored projects fail to run, but only successfuly built projects are reported and tests pass.

## Additional context

Image

### PR DESCRIPTION
**Pull request by nohwnd**
When build fails to finish, add error count and fail the run.

This problem is caused by build being "additional" work that is not a test, so we did not report it as failure.

Fix https://github.com/microsoft/testfx/issues/4683

image

Working towards https://github.com/dotnet/sdk/issues/45927

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs [hunk 1]
```diff
@@ -134,15 +134,22 @@ private void InitializeTestApplications(IEnumerable<Module> modules)
         {
             foreach (Module module in modules)
             {
-                if (module.IsTestProject && module.IsTestingPlatformApplication)
+                if (module.IsTestProject)
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs:137]: Nit: Revert condition and remove else part.

File: src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs [hunk 2]
```diff
@@ -134,15 +134,22 @@ private void InitializeTestApplications(IEnumerable<Module> modules)
...
                 {
-                    var testApp = new TestApplication(module, _args);
-                    _testApplications.Add(testApp);
+                    if (module.IsTestingPlatformApplication)
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs:139]: Nit: Revert condition and remove else part.

**Review by Evangelink — APPROVED** [review]
Let's ensure all the changes to `TerminalTestReporter` are backported to testfx repo. It feels like we are already quite out of sync.

**Comment by nohwnd** [comment]
These changes are not really applicable for the terminal logger that is used in MTP (hence having this bug), there the only source of problems is either crash, or failed tests, all of which are already captured by the infra.

**Comment by nohwnd** [comment]
But I will try to make a script to sync. Once my hands a bit free-er.
