### PR TITLE
File watcher: ignore directories, allow watching non-recursively

### LINKED ISSUE #49307: Tracking: dotnet-watch test failures in AutoRestartOnRudeEdit and IgnoredChange
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1063209&view=results
Build error leg or test failing: `dotnet-watch.Tests.dll.1 Work Item` and `dotnet-watch.Tests.dll.6 Work Item`
Pull request: https://github.com/dotnet/sdk/pull/49306

## Error Message

##[error].packages/microsoft.dotnet.helix.sdk/10.0.0-beta.25306.103/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(91,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item dotnet-watch.Tests.dll.1 in job 1964fc66-8585-487e-a4b7-975e8758ce29 has failed.

##[error].packages/microsoft.dotnet.helix.sdk/10.0.0-beta.25306.103/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(91,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item dotnet-watch.Tests.dll.6 in job 1964fc66-8585-487e-a4b7-975e8758ce29 has failed.

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Work item dotnet-watch\\.Tests\\.dll\\.[0-9]+ in job [a-z0-9\\-]+ has failed",
  "BuildRetry": true,
  "ExcludeConsoleLog": true
}
```

### PR DESCRIPTION
**Pull request by tmat**
Preparing directory watcher for watching individual files in some cases when we don't want to watch the entire directory tree (e.g. targets and props files outside of the project dir).

Fixes https://github.com/dotnet/sdk/issues/49307

### CODE REVIEW

**Comment by tmat** [comment]
@phil-allen-msft @DustinCampbell ptal

File: src/BuiltInTools/dotnet-watch/Internal/FileWatcher/EventBasedDirectoryWatcher.cs [hunk 1]
```diff
@@ -65,21 +64,23 @@ private void WatcherRenameHandler(object sender, RenamedEventArgs e)
...
-            Logger?.Invoke($"Renamed '{e.OldFullPath}' to '{e.FullPath}'.");
-
-            NotifyChange(e.OldFullPath, ChangeKind.Delete);
-            NotifyChange(e.FullPath, ChangeKind.Add);
+            Logger?.Invoke($"[FW] Renamed '{e.OldFullPath}' to '{e.FullPath}'.");
 
             if (Directory.Exists(e.FullPath))
             {
-                foreach (var newLocation in Directory.EnumerateFileSystemEntries(e.FullPath, "*", SearchOption.AllDirectories))
+                foreach (var newLocation in Directory.EnumerateFiles(e.FullPath, "*", SearchOption.AllDirectories))
```
Comment (DustinCampbell) [inline src/BuiltInTools/dotnet-watch/Internal/FileWatcher/EventBasedDirectoryWatcher.cs:71]: Did this mean that we would report file and directory changes before, when only file changes were expected?

**Review by DustinCampbell — APPROVED** [review]

File: src/BuiltInTools/dotnet-watch/Internal/FileWatcher/EventBasedDirectoryWatcher.cs (hunk 1 above)
Comment (tmat) [reply src/BuiltInTools/dotnet-watch/Internal/FileWatcher/EventBasedDirectoryWatcher.cs:71]: We would report directory changes and then ignore them on higher layer. 
It's easier to skip them here. Simplifies testing
