### PR TITLE
Default excludes

### LINKED ISSUE #44910: dotnet watch hot reloads for all non-code files - potential infinite reload loop
### Describe the bug

I'm running `dotnet watch` in the directory of an ASP.NET Core 8.0 application using the .NET 9 SDK.

My app generates non-code files in the `~\App_Data` directory as part of a background process (this includes binary, xml, json, and other non code files). When this happens, `dotnet watch` records the files being created or modified and will even hot reload

For example

```
dotnet watch ⌚ Files added: .\App_Data\LuceneSearch\QANDA_SEARCH\i-g0000059-p_False\write.lock, .\App_Data\LuceneSearch\QANDA_SEARCH\i-g0000059-p_False_taxonomy\write.lock
dotnet watch ⌚ Files added: .\App_Data\LuceneSearch\QANDA_SEARCH\i-g0000059-p_False\write.lock, .\App_Data\LuceneSearch\QANDA_SEARCH\i-g0000059-p_False_taxonomy\write.lock
dotnet watch ⌚ No hot reload changes to apply.
```

I have tried [ignoring specific files](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch#ignore-specified-files) but none of the recommendations work. Even if they _did_ work, there's no reason I should have to explicitly ignore some `.txt` files in `App_Data` to keep my app from reloading.

### To Reproduce

1. Clone <https://github.com/seangwright/dotnet-watch-dotnet-sdk9-bug>
2. Run `dotnet watch`
3. See home page load in browser
4. See infinite number of .txt files created in `App_Data\Test` because `dotnet watch` keeps reloading the page

### Exceptions (if any)

`dotnet watch` should not process files that have nothing to do with rebuilding or hot-reloading my .NET application.

### Further technical details

```
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.12.35506.116
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  8.0.404 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  E:\workspace\dotnet\ASPNETMVC8_NET9SDK\global.json
```

This bug negatively impacts _any_ project that generates files in the project during runtime - ASPNET Core apps with client assets, files uploaded/imported to the file system, log files, ect...

### LINKED ISSUE #45539: [dotnet-watch] Consider using DefaultItemExcludes and DefaultExcludesInProjectFolder for directory exclusions
Tracks todo in code.

### LINKED ISSUE #46805: 9.0.200 Hot Reload loading pages with files/folders it should be ignoring
### Describe the bug
Since upgrading to 9.0.200 when I run `dotnet watch run` and my web app writes to the logs folder to a log file it now sees it as a change and the watch process sees it as an event and hot reloads and my browser reloads the page. If I try to run it the way I used to with just the `dotnet watch` command then it goes into an infinite loop with the hot reload. I am using serilog to log to the console and a log file in a folder called logs. I have excluded the logs folder from the project and my project file looks like this now since I have added the `Watch="false"` pieces to it like the documentation states to do.

Image

And here is what the console is showing what dotnet is doing:

Image

Then the browser window reloads. This was not happening in 9.0.100, but I was having the issue of it not hot reloading the changes like other were in 9.0.100. Now with this issue it is worse. Hopefully a hotfix can be put out quickly or a work around.

### To Reproduce
Just have the logger output to a log file within the project folder and run the `dotnet watch run` command and do something that causes it to write to the log file or add or delete files from the log folder.

### PR DESCRIPTION
**Pull request by tmat**
Adds capability to watch individual files to FileWatcher.

If enabled, uses the SDK's `DefaultItemExcludes` globs to exclude files from being watched.
Otherwise, excludes `out` and `bin` directories as previously implemented.

Implement support for project file changes (proj, props, targets).

Fixes https://github.com/dotnet/sdk/issues/46805
Fixes https://github.com/dotnet/sdk/issues/44910
Fixes https://github.com/dotnet/sdk/issues/45539

### CODE REVIEW

**Comment by tmat** [comment]
@DustinCampbell ptal

File: src/BuiltInTools/dotnet-watch/HotReload/FilePathExclusions.cs [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+                    }
+                    catch
+                    {
+                        // ignore
+                    }
+                }
+            }
+        }
+
+        return new FilePathExclusions(globs.Values, outputDirectories);
```
Comment (DustinCampbell) [inline src/BuiltInTools/dotnet-watch/HotReload/FilePathExclusions.cs:68]: Is there any ordering of `Values` that might be deterministic or efficient?

**Review by DustinCampbell — APPROVED** [review]

File: src/BuiltInTools/dotnet-watch/HotReload/FilePathExclusions.cs (hunk 1 above)
Comment (tmat) [reply src/BuiltInTools/dotnet-watch/HotReload/FilePathExclusions.cs:68]: The order doesn't matter for determinism since we check if any of the globs match and we don't care which one did.

Re perf - it's just regex matching underneath. Should be fast enough without any smarts in ordering.

**Comment by willdean** [comment]
Is this going to be backported into 9 or are we too late for that now?

**Comment by tmat** [comment]
I don't think so. This is a significant change and will need more follow up changes to address various issues with updating projects.
