### PR TITLE
Handle error when status runtime information cannot find version in productCollection.

### LINKED ISSUE #26509: dotnet sdk check throws exception when trying to print installed runtimes.
### Describe the bug
When I got to try to run ``dotnet sdk check`` to ensure my SDK is up to date I instead get InvalidOperationException right after it prints ".NET Runtimes:".

### To Reproduce

1. Install the .NET 6.0.400-preview.22301.10 SDK and run ``dotnet sdk check`` in a simple project folder (with a solution file).
2. Install https://github.com/Elskom/EFCore-Installer/releases/tag/6.0.6 and add it's SDK (in github packages) to the project (``<Sdk Name="[package name]" Version="6.0.6" />``).
3. Install https://github.com/Elskom/Serilog-Installer/releases/tag/6.0.6 and add it's SDK (in github packages) to the project (``<Sdk Name="[package name]" Version="6.0.6" />``).
4. Install https://github.com/Elskom/Remora.Discord-Installer/releases/tag/2022.43.0 and add it's SDK (in github packages) to the project (``<Sdk Name="[package name]" Version="2022.43.0" />``).

``dotnet --list-runtimes`` works however.

### Exceptions (if any)

```
.NET SDKs:
Version                       Status
-----------------------------------------
6.0.106                       Up to date.
6.0.203                       Up to date.
6.0.302                       Up to date.
6.0.400-preview.22301.10      Up to date.

Try out the newest .NET SDK features with .NET 7.0.100-preview.5.22307.18.

.NET Runtimes:
Unhandled exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.Tools.Sdk.Check.BundleOutputWriter.BundleIsEndOfLife(INetBundleInfo bundle)
   at Microsoft.DotNet.Tools.Sdk.Check.RuntimeOutputWriter.GetRuntimeStatusMessage(NetRuntimeInfo runtime)
   at Microsoft.DotNet.Tools.Sdk.Check.RuntimeOutputWriter.<PrintRuntimeInfo>b__2_2(NetRuntimeInfo runtime)
   at Microsoft.DotNet.Cli.PrintableTable`1.<>c__DisplayClass9_0.<CalculateColumnWidths>b__0(Column c)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Cli.PrintableTable`1.CalculateColumnWidths(IEnumerable`1 rows)
   at Microsoft.DotNet.Cli.PrintableTable`1.PrintRows(IEnumerable`1 rows, Action`1 writeLine)
   at Microsoft.DotNet.Tools.Sdk.Check.RuntimeOutputWriter.PrintRuntimeInfo()
   at Microsoft.DotNet.Tools.Sdk.Check.SdkCheckCommand.Execute()
   at Microsoft.DotNet.Tools.Sdk.Check.SdkCheckCommand.Run(ParseResult parseResult)
   at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

```
.NET SDK (reflecting any global.json):
 Version:   6.0.400-preview.22301.10
 Commit:    25580ffe7a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.106 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Elskom.Sdk.App 6.0.0-dev [C:\Program Files\dotnet\shared\Elskom.Sdk.App] (I made this)
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.EntityFrameworkCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.EntityFrameworkCore.App] (I made this)
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Remora.Discord.App 2022.43.0 [C:\Program Files\dotnet\shared\Remora.Discord.App] (I made this)
  Serilog.App 6.0.6 [C:\Program Files\dotnet\shared\Serilog.App] (I made this)

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

IDE: Visual Studio 2022 latest preview

### PR DESCRIPTION
**Pull request by AraHaan**
Fixes https://github.com/dotnet/sdk/issues/26509.

Changes:
- Change the ``.First()`` calls that operate on ``productCollection`` to ``FirstOrDefault()`` and use nullable annotate the return value to make them nullable.
- Added a new localizable string resource.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-sdk/check/RuntimeOutputWriter.cs [hunk 1]
```diff
@@ -39,24 +40,31 @@ public void PrintRuntimeInfo()
...
-                return string.Format(LocalizableStrings.MaintenanceMessage, $"{runtime.Version.Major}.{runtime.Version.Minor}");
-            }
-            else if (NewerRuntimePatchExists(runtime))
-            {
-                return string.Format(LocalizableStrings.NewPatchAvailableMessage, NewestRuntimePatchVersion(runtime));
-            }
-            else
-            {
-                return LocalizableStrings.BundleUpToDateMessage;
+                return "No version found to check if this is up to date. Please check for updates manually.";
```
Comment (kant2002) [inline src/Cli/dotnet/commands/dotnet-sdk/check/RuntimeOutputWriter.cs:64]: Message probably should be localized

Comment (AraHaan) [reply src/Cli/dotnet/commands/dotnet-sdk/check/RuntimeOutputWriter.cs]: Done, I was only able to sadly translate one with poedit, so the others will need to be translated by someone else (after verifying the translated one that I was able to do).

Comment (AraHaan) [reply src/Cli/dotnet/commands/dotnet-sdk/check/RuntimeOutputWriter.cs]: Interesting, it thinks to manually updated xlf's are outdated.

**Comment by baronfel** [comment]
Try/Catches obscure the problem - the API in the various `BundleIs*` calls from the [bundle output writer](https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Cli/dotnet/commands/dotnet-sdk/check/BundleOutputWriter.cs) should be changed to return a nullable bool instead so that we can accurately detect the non-existence of the requested runtime in the ProductCollection. Then for those 'not found' cases we can use the message you've provided.

**Comment by AraHaan** [comment]
Alright.

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.cs.xlf [hunk 2]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">Rozhraní .NET {0} se už nepodporuje.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-review-translation">Nebyla nalezena žádná verze, aby bylo možné zkontrolovat, zda je aktuální. Zkontrolujte prosím aktualizace ručně.</target>
+        <note>Translation might not be accurate as Poedit free 3.1.1 was used.</note>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.cs.xlf:58]:
```suggestion
        <target state="needs-translation"></target>
        <note />
```
I do not think that the translation from poedit should be used yet as I feel that Microsoft's translator's might do a better job.

**Comment by AraHaan** [comment]
Alright, about to switch it to using the nullable bools option instead of try/catch. Although I am not sure how to fix the false compile errors with it thinking that the translation files need to be updated (as I updated them manually).

**Comment by AraHaan** [comment]
Now the only thing that is needed is for the translations to be done.

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.cs.xlf [hunk 3]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">Rozhraní .NET {0} se už nepodporuje.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.cs.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.de.xlf [hunk 4]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0} wird nicht mehr unterstützt.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.de.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.es.xlf [hunk 5]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0} no tiene soporte técnico.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.es.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.fr.xlf [hunk 6]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0} n'est plus pris en charge.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.fr.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.it.xlf [hunk 7]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">Il supporto per .NET {0} non è più disponibile.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.it.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ja.xlf [hunk 8]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0} はサポートされていません。</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ja.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ko.xlf [hunk 9]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0}은(는) 지원되지 않습니다.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ko.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.pl.xlf [hunk 10]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">Platforma .NET {0} nie jest już wspierana.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.pl.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.pt-BR.xlf [hunk 11]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">Não há mais suporte para o .NET {0}.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.pt-BR.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ru.xlf [hunk 12]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0} не поддерживается.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.ru.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.tr.xlf [hunk 13]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0} desteği kaldırıldı.</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.tr.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.zh-Hans.xlf [hunk 14]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0} 结束支持。</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.zh-Hans.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.zh-Hant.xlf [hunk 15]
```diff
@@ -52,6 +52,11 @@
         <target state="translated">.NET {0} 已不再支援。</target>
         <note />
       </trans-unit>
+      <trans-unit id="RuntimeVersionCheckFailure">
+        <source>No version found to check if this is up to date. Please check for updates manually.</source>
+        <target state="needs-translation"></target>
```
Comment (AraHaan) [inline src/Cli/dotnet/commands/dotnet-sdk/check/xlf/LocalizableStrings.zh-Hant.xlf:57]:
```suggestion
        <target state="new">No version found to check if this is up to date. Please check for updates manually.</target>
```

File: src/Cli/dotnet/commands/dotnet-sdk/check/RuntimeOutputWriter.cs (hunk 1 above)
Comment (AraHaan) [reply src/Cli/dotnet/commands/dotnet-sdk/check/RuntimeOutputWriter.cs]: I decided to instead have OneLocBuild (or whatever it is called) do all of the translations instead for me as it seems that it can automatically run right after the time this would be merged anyway.

**Comment by AraHaan** [comment]
Looks like the dotnet CLI needs to be changed to compile when nullable is enabled first before this PR can be merged.

**Comment by AraHaan** [comment]
I think nullable annotations on the project should be enabled in a separate PR.

**Comment by AraHaan** [comment]
Hopefully I finally fixed the nullable issues.

**Comment by AraHaan** [comment]
I think the current failures is unrelated.

**Review by joeloff — APPROVED** [review]

**Comment by AraHaan** [comment]
Is this planned to be merged soon before 7.0.100 stable is released?

**Comment by marcpopMSFT** [comment]
Thank you for your contribution. Retargeted to the 7.0.1xx branch and set to automerge. This will be included in 7.0.1xx-rc2.

**Comment by AraHaan** [comment]
When can we see this in the daily builds of the rc.2 sdks? Currently I do not see it in the one listed under dotnet/installer to try it out locally from there.
