### PR TITLE
More workload set fixes

### LINKED ISSUE #40005: Update logic for how workload version is displayed
The workload version can be displayed via `dotnet workload version`, and is also displayed in `dotnet workload --info`.

- If in a context with a workload set version specified in global.json, the version from global.json should be displayed.  If that workload set version isn't currently installed, `dotnet workload --version` should still display it wiithout erroring.
- If a workload set is in use, its version should be displayed
- If not using a workload set, or if the update mode is set to workload sets but no workload set is installed, then display a version based on a hash of the workload manifest versions, which looks something like `8.0.300-manifests.ab95c30`

Also, we should update `dotnet workload --info` to display the workload config settings (currently just the update mode).

FYI @baronfel @marcpopMSFT @Forgind

### PR DESCRIPTION
**Pull request by Forgind**
This aims to resolve #40005 and #37828 as well as one other bug I'd found. More specifically, it:
1. Makes it an error if we resolve a workload set version when you asked for a different one.
2. Adds a message to dotnet workload --info to indicate whether we're trying to use workload sets or not.
3. Removes the version from individual workload manifests if we're configured to use a workload set.
4. Fixes a typo (Manfiest --> Manifest)
5. Ensures that if we have a workload set and some manifests specified in the install state file, that the workload set wins if it came from a global.json or the install state file but loses if it was just the highest-numbered workload set available when we're finding which manifests to use.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs [hunk 1]
```diff
@@ -294,19 +294,23 @@ private string ModifyWorkloadSet(string advertisingPackagePath, InstallAction re
...
 
-            if (plannedAction != InstallAction.None)
+            if (plannedAction == InstallAction.Uninstall)
+            {
+                Elevate();
+
+                // Update the reference count against the MSI.
+                UpdateDependent(InstallRequestType.RemoveDependent, msi.Manifest.ProviderKeyName, _dependent);
+
+                ExecutePackage(msi, plannedAction, msiPackageId);
```
Comment (dsplaisted) [inline src/Cli/dotnet/commands/dotnet-workload/install/NetSdkMsiInstallerClient.cs:304]: Looks like per our discussion with Jacques, this ordering should fix the rollback failures.

File: src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs [hunk 2]
```diff
@@ -94,26 +94,28 @@ public override int Execute()
                     var manifestInfoDict = _workloadListHelper.WorkloadResolver.GetInstalledManifests().ToDictionary(info => info.Id, StringComparer.OrdinalIgnoreCase);
 
                     InstalledWorkloadsCollection installedWorkloads = _workloadListHelper.AddInstalledVsWorkloads(installedList);
+                    var shouldPrintVersionFromInstallState = globalJsonInformation is null &&
```
Comment (dsplaisted) [inline src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs:97]: I'd suggest renaming this, I was originally confused about what it was.  I thought it was referring to the workload version in the install state, ie it would only be true if you had a pinned version in the install state.

Something like `usingWorkloadSetMode` might be clearer.

File: src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs [hunk 3]
```diff
@@ -277,20 +298,9 @@ void ProbeDirectory(string manifestDirectory, string featureBand)
                 }
             }
 
-            //  Load manifests from workload set, if any.  This will override any manifests for the same IDs that were loaded previously in this method
-            if (_workloadSet != null)
+            if (!_workloadSetDominatesInstallState)
```
Comment (dsplaisted) [inline src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs:301]: I don't think we need to change the order of when we load the manifests here.  Rather, if a workload set is specified in global.json, we should ignore the install state entirely.  So you could undo the refactoring of `LoadManifestsFromWorkloadSet` into a separate method, and skip the logic that processes `_manifestsFromInstallState` if a workload set was specified via global.json (and probably also if it was specified by being passed to the constructor).

**Review by dsplaisted — COMMENTED** [review]
I took a first pass at a review here.

I think this should be retargeted onto release/8.0.4xx.

Also, we need to change the path to the install state to include the processor architecture, for example `C:\ProgramData\dotnet\workloads\x64\8.0.300-preview.0\installstate\default.json`.  I think it would make sense to include that change in this PR.

File: src/Cli/dotnet/commands/InstallingWorkloadCommand.cs [hunk 4]
```diff
@@ -133,7 +133,16 @@ public bool TryInstallWorkloadSet(ITransactionContext context, out IEnumerable<M
             if (File.Exists(Path.Combine(advertisingPackagePath, Constants.workloadSetVersionFileName)))
             {
                 // This file isn't created in tests.
-                PrintWorkloadSetTransition(File.ReadAllText(Path.Combine(advertisingPackagePath, Constants.workloadSetVersionFileName)));
+                var version = File.ReadAllText(Path.Combine(advertisingPackagePath, Constants.workloadSetVersionFileName));
+                PrintWorkloadSetTransition(version);
+                if (!version.Equals(_workloadSetVersion) && !version.Equals(_workloadSetVersionFromGlobalJson))
```
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Cli/dotnet/commands/InstallingWorkloadCommand.cs:138]: Great catch!

File: src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs (hunk 2 above)
Comment (Forgind) [reply src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs:97]: I had some issues with this name, to be honest. usingWorkloadSetMode isn't quite right either, as you could still be using workload sets if you specify one in the global.json, but this would be false. I'm not sure what the ideal name is...

File: src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs (hunk 3 above)
Comment (Forgind) [reply src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs:301]: Those are both included from the block before the table (lines 82-90)

File: src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs [hunk 5]
```diff
@@ -94,26 +94,28 @@ public override int Execute()
...
+                    if (shouldPrintVersionFromInstallState)
                     {
-                        var installState = InstallStateContents.FromPath(Path.Combine(WorkloadInstallType.GetInstallStateFolder(_workloadListHelper._currentSdkFeatureBand, _workloadListHelper.DotnetPath), "default.json"));
-                        if (installState.UseWorkloadSets == true)
-                        {
-                            Reporter.WriteLine();
-                            Reporter.WriteLine(string.Format(LocalizableStrings.WorkloadSetVersion, _workloadListHelper.WorkloadResolver.GetWorkloadVersion() ?? "unknown"));
-                        }
+                        Reporter.WriteLine();
+                        Reporter.WriteLine(string.Format(LocalizableStrings.WorkloadSetVersion, _workloadListHelper.WorkloadResolver.GetWorkloadVersion() ?? "unknown"));
```
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs:118]: Those are both included from the block before the table (lines 82-90)

File: src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs (hunk 3 above)
Comment (Forgind) [reply src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs:301]: This is a question of when we know what.

When we're trying to generate _workloadSet, we have all the relevant information at our fingertips, most importantly where it came from. At this point, though, we just know that there is a workload set; it might've come from a global.json (in which case it should be prioritized over an install state file), or it might've just been the highest numbered workload set we could find, in which case it should be prioritized lower. This _workloadSetDominatesInstallState field is intended to disambiguate that.

**Comment by Forgind** [comment]
> I think this should be retargeted onto release/8.0.4xx.

My recollection is that some changes this modified hadn't flowed to 4xx when I made this. No longer true.

File: src/Cli/dotnet/commands/InstallingWorkloadCommand.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (dsplaisted) [reply src/Cli/dotnet/commands/InstallingWorkloadCommand.cs]: I think the best thing to do would be to update `WorkloadManifestUpdater.UpdateManifestWithVersionAsync` so that when it writes the version file and the `packageVersion` is specified, it checks to see whether they match and throws an exception if not.  Then we can remove the logic in `InstallingWorkloadCommand` to handle the difference.

If we ever end up in a situation where that exception is thrown, then we can investigate why and figure out what to do from there (which might include failing more gracefully if it's actually a valid behavior).

File: src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs (hunk 2 above)
Comment (dsplaisted) [reply src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs:97]: How about `shouldShowWorkloadSetVersion`?  I think you could also set it to true if there's a workload set in global.json, because in that case we wouldn't want the manifest version column either.

File: src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs (hunk 5 above)
[the remark this answers is not in the document]
Comment (dsplaisted) [reply src/Cli/dotnet/commands/dotnet-workload/list/WorkloadListCommand.cs:118]: Is there any reason to show the global.json information before the table but the non-global.json workload version after the table?  It seems like we should be consistent.

If we put them before the table, probably we should add an empty line between the message and the table header to visually separate them.

File: src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs (hunk 3 above)
Comment (dsplaisted) [reply src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs:301]: We can still keep a boolean to let us know what we should do.  But there's no reason to load the manifests from the install state and then the manifests from the workload set.  We should load the manifests from the workload set, and then either load the manifests from the install state, or skip it.

I think a name like `_useManifestsFromInstallState` would be clearer in that case.  So we'd have something like this:

```c#
LoadManifestsFromWorkloadSet();

if (_manifestsFromInstallState != null && _useManifestsFromInstallState)
{
    //  Code here to load manifests from the install state
}
```

Then we only have one call to `LoadManifestsFromWorkloadSet`, so we can remove that as a separate method and put the implementation back into `GetManifests` directly.

`_useManifestsFromInstallState` should be set to false if we get a workload version from global.json, or if the workload set version was specified via the constructor.  Otherwise it should be set to true.

Does that make sense?

**Comment by dsplaisted** [comment]
@Forgind I've responded to the comments, and run the tests on the code.  The only one still failing which would be good to fix in this PR is now `UpdateToUnavailableWorkloadSetVersion`, which is failing because the exit code is 0 when you try to update to a workload version that it can't find (`dotnet workload update --version <versionthatdoesntexist>`).

Updating to a workload set from a different band is also failing, but as discussed we'll probably fix that in my refactoring PR.

File: src/Cli/dotnet/commands/InstallingWorkloadCommand.cs (hunk 4 above)
[the remark this answers is not in the document]
Comment (Forgind) [reply src/Cli/dotnet/commands/InstallingWorkloadCommand.cs]: Sounds good to me

File: src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs [hunk 6]
```diff
@@ -340,6 +340,11 @@ private async Task<bool> UpdateManifestWithVersionAsync(string id, bool includeP
                     // Create version file later used as part of installing the workload set in the file-based installer and in the msi-based installer
                     using PackageArchiveReader packageReader = new(packagePath);
                     var downloadedPackageVersion = packageReader.NuspecReader.GetVersion();
+                    if (packageVersion != null && !downloadedPackageVersion.Equals(packageVersion))
+                    {
+                        throw new Exception(string.Format(Update.LocalizableStrings.WorkloadVersionNotFound, packageVersion));
```
Comment (dsplaisted) [inline src/Cli/dotnet/commands/dotnet-workload/install/WorkloadManifestUpdater.cs:345]: I think the exception message should specifically say that a different version was downloaded than we were expecting, and give both versions.

The exception message doesn't need to be localized in this case, as we think it's an internal error.

File: src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs [hunk 7]
```diff
@@ -121,11 +121,12 @@ public void RefreshWorkloadManifests()
             _workloadSet = null;
             _manifestsFromInstallState = null;
             _installStateFilePath = null;
-            _workloadSetDominatesInstallState = false;
+            _useManifestsFromInstallState = false;
```
Comment (dsplaisted) [inline src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs:124]: The value of `_useManifestsFromInstallState` should be inverted from what `_workloadSetDominatesInstallState` was.  So it should default to true and be set to false if the workload version was specified in the constructor or found in global.json.

**Review by dsplaisted — APPROVED** [review]
Looks like we still need a fix for `UpdateToUnavailableWorkloadSetVersion`.

File: src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs (hunk 7 above)
Comment (Forgind) [reply src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs:124]: 🤦 I'm stupid sometimes
