### PR TITLE
correct command model for nuget trust command and subcommands

### LINKED ISSUE #34610: dotnet nuget trust command doesn't work in 8.0.0-preview.7
### Describe the bug
dotnet nuget trust command doesn't work in the latest 8.0.0-preview.7 ( 8.0.100-preview.7.23376.3)

### To Reproduce
Run `dotnet nuget trust certificate MyCompanyCert 788D94235338D9395DA5804905C0B5F20F2AE4D527B5FE356D4E0C1DCF809ABC` command, the output is:
```
Unrecognized command or argument 'MyCompanyCert'.
Unrecognized command or argument '788D94235338D9395DA5804905C0B5F20F2AE4D527B5FE356D4E0C1DCF809ABC'.
```
But this command works well in an older version.

### Further technical details
There is a related change in dotnet/sdk repo: https://github.com/dotnet/sdk/pull/33157, updating the src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs  file. It might be the reason why this command is broken.

### PR DESCRIPTION
**Pull request by baronfel**
Fixes #34610 

This models the various trust commands as of .NET 8.0.100 preview 7 in line with the actual implementations in NuGet.CommandLine.XPlat.dll.

Details of the various trust commands are below:

<details>
<summary>Output from help for each subcommand</summary>

```shell
> dotnet .\NuGet.CommandLine.XPlat.dll trust --help


Usage: dotnet nuget trust [options] [command]

Options:
  --configfile    The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help       Show help information
  -v|--verbosity  Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

Commands:
  author       Adds a trusted signer with the given name, based on the author signature of the package.
  certificate  Adds a trusted signer with the given name, based on the repository signature or countersignature of a signed package.
  list         Lists all the trusted signers in the configuration.
  remove       Removes any trusted signers that match the given name.
  repository   Adds a trusted signer with the given name, based on the repository signature or countersignature of a signed package.
  source       Adds a trusted signer based on a given package source.
  sync         Deletes the current list of certificates and replaces them with an up-to-date list from the repository.

Use "trust [command] --help" for more information about a command.

>  dotnet .\NuGet.CommandLine.XPlat.dll trust author
error: Property 'name' should not be null or empty.


Usage: dotnet nuget trust author [arguments] [options]

Arguments:
  <NAME>     The name of the trusted signer to add. If name already exists in the configuration, the signature is appended.
  <PACKAGE>  The given package should be a local path to the signed .nupkg file.

Options:
  --allow-untrusted-root  Specifies if the certificate for the trusted signer should be allowed to chain to an untrusted root. This is not recommended.
  --configfile            The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help               Show help information
  -v|--verbosity          Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

> dotnet .\NuGet.CommandLine.XPlat.dll trust certificate
error: Property 'name' should not be null or empty.


Usage: dotnet nuget trust certificate [arguments] [options]

Arguments:
  <NAME>         The name of the trusted signer to add. If a trusted signer with the given name already exists, the certificate item is added to that signer. Otherwise a trusted author is created with a certificate item from the given certificate information.
  <FINGERPRINT>  The fingerprint of the certificate.

Options:
  --algorithm             Specifies the hash algorithm used to calculate the certificate fingerprint. Defaults to SHA256. Values supported are SHA256, SHA384 and SHA512.
  --allow-untrusted-root  Specifies if the certificate for the trusted signer should be allowed to chain to an untrusted root. This is not recommended.
  --configfile            The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help               Show help information
  -v|--verbosity          Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

> dotnet .\NuGet.CommandLine.XPlat.dll trust list --help


Usage: dotnet nuget trust list [options]

Options:
  --configfile    The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help       Show help information
  -v|--verbosity  Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

> dotnet .\NuGet.CommandLine.XPlat.dll trust remove
error: Property 'name' should not be null or empty.


Usage: dotnet nuget trust remove [arguments] [options]

Arguments:
  <NAME>  The name of the existing trusted signer to remove.

Options:
  --configfile    The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help       Show help information
  -v|--verbosity  Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

> dotnet .\NuGet.CommandLine.XPlat.dll trust repository
error: Property 'name' should not be null or empty.


Usage: dotnet nuget trust repository [arguments] [options]

Arguments:
  <NAME>     The name of the trusted signer to add. If name already exists in the configuration, the signature is appended.
  <PACKAGE>  The given package should be a local path to the signed .nupkg file.

Options:
  --allow-untrusted-root  Specifies if the certificate for the trusted signer should be allowed to chain to an untrusted root. This is not recommended.
  --configfile            The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help               Show help information
  --owners                Semi-colon separated list of trusted owners to further restrict the trust of a repository.
  -v|--verbosity          Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

> dotnet .\NuGet.CommandLine.XPlat.dll trust source
error: Property 'name' should not be null or empty.


Usage: dotnet nuget trust source [arguments] [options]

Arguments:
  <NAME>  "The name of the trusted signer to add. If only <NAME> is provided without --<source-url>, the package source from your NuGet configuration files with the same name is added to the trusted list. If <NAME> already exists in the configuration, the package source is appended to it."

Options:
  --configfile    The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help       Show help information
  --owners        Semi-colon separated list of trusted owners to further restrict the trust of a repository.
  --source-url    If a source-url is provided, it must be a v3 package source URL (like https://api.nuget.org/v3/index.json). Other package source types are not supported.
  -v|--verbosity  Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].

> dotnet .\NuGet.CommandLine.XPlat.dll trust sync
error: Property 'name' should not be null or empty.


Usage: dotnet nuget trust sync [arguments] [options]

Arguments:
  <NAME>  The name of the existing trusted signer to sync.

Options:
  --configfile    The NuGet configuration file. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see https://docs.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.
  -h|--help       Show help information
  -v|--verbosity  Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
```
</details>

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs [hunk 1]
```diff
@@ -120,22 +120,70 @@ private static CliCommand GetTrustCommand()
...
+                new CliArgument<string>("NAME"),
+                owners,
+                new CliOption<string>("--source-url"),
+            };
+
+            CliCommand CertificateCommand() => new CliCommand("certificate") {
+                new CliArgument<string>("NAME"),
+                new CliArgument<string>("FINGERPRINT"),
+                allowUntrustedRoot,
+                new CliOption<string>("--algorithm")
```
Comment (baronfel) [inline src/Cli/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs:173]: nit: I could implement `FromAmong` here - that would give tab-completion a nicer experience. But it's kind of moot because `help` doesn't come from the SDK, which is the other place that FromAmong is used.

File: src/Cli/dotnet/Parser.cs [hunk 2]
```diff
@@ -271,7 +271,7 @@ public override void Write(HelpContext context)
                     option.EnsureHelpName();
                 }
 
-                if (command.Name.Equals(NuGetCommandParser.GetCommand().Name))
+                if (command.Equals(NuGetCommandParser.GetCommand()) || command.Parents.Any(parent => parent == NuGetCommandParser.GetCommand()))
```
Comment (baronfel) [inline src/Cli/dotnet/Parser.cs:274]: this is not strictly related to this PR, but the nuget help won't show (SDK help hijacks it) unless I add this.

**Review by heng-liu — APPROVED** [review]
Thanks @baronfel !
Looks good to me!
Since there is no auto test,  it might be good if we test the command manually.

**Comment by heng-liu** [comment]
FYI, I use the dotnet.exe from this branch to run some NuGet tests in https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetTrustTests.cs
All tests passed.

**Review by jeffkl — APPROVED** [review]
🎉

**Comment by baronfel** [comment]
re-targeted to 8.0.1xx-rc1 since that branch is now available.
