### PR TITLE
[Static web assets] Account for HintPath when we compute the build assets

### LINKED ISSUE #29561: Microsoft.NET.Sdk.Razor GeneratePackageOnBuild creating folders for random static web assets
### Describe the bug
When generating a nuget package for a blazor class library random files are created as directories. See attached repro.

### To Reproduce

1. Open the attached repro [Blazor5ClassLib.zip](https://github.com/dotnet/aspnetcore/files/5859604/Blazor5ClassLib.zip)
2. Build the project
3. Navigate to bin\Debug\
4. Extract the contents of Blazor5ClassLib.1.0.0.nupkg 
5. Navigate to Blazor5ClassLib.1.0.0\staticwebassets\css\open-iconic
6. The FONT-LICENSE and ICON-LICENSE files have been packaged as a directory rather than the static file in the project. This causes blazor wasm publishes which reference this package to fail with an error similar to https://github.com/dotnet/aspnetcore/issues/29529

```
staticwebassets\css\open-iconic\ICON-LICENSE' is denied.
            at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
            at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
            at System.IO.File.OpenRead(String path)
            at Microsoft.NET.Sdk.BlazorWebAssembly.Tools.BrotliCompressCommand.<ExecuteCoreAsync>b__16_0(Int32 i)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location ---
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

Static assets should be packaged as they are in the project.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- Visual Studio 16.8.4

### LINKED ISSUE #32744: Blazor WebAssembly AOT publiish output contains files that should not be published
Repro steps:

- Install .NET 6 Preview 4 (6.0.100-preview.4.21255.9)
- AOT compile a Blazor WebAssembly app by publishing it
- Inspect the published output

Expected result:

- Only files that should be published with the app are present in the published wwwroot folder

Actual result:

- Published output contains C code, header files, and other implementation files like:
    - corebindings.c
    - driver.c
    - pinvoke.c
    - pinvoke.h
    - emcc-flags.txt
    - emcc-version.txt
    - etc.

@lewing @pranavkm

### LINKED ISSUE #35349: Blazor WebAssembly App does not build when referencing .NET Standard 2.0 assembly.
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WebAssembly-App-does-not-build-wh/1500692)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Preview 2.1]
When referencing a .NET Standard 2.0 (this is the only option I have tried) assembly (versus Project Reference), I am not able to build the Project/Solution.
I have included the basic project, cleaned in order to keep the download small. Build the ClassLibrary first, then the BlazorApp.

---
#### Feedback Bot on 8/12/2021, 02:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### LINKED ISSUE #35561: [.Net 6.0 Preview 7] Microsoft.NET.Sdk.Razor.StaticWebAssets.targets DirectoryNotFoundException
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-60-Preview-7-MicrosoftNETSdkR/1508969)._

---
When building a c# project on the .NET 6.0 Preview 7 SDK, if my .csproj file has "AppendTargetFrameworkToOutputPath" set to false, I get a DirectoryNotFound exception. Note the "net6.0" in the path that cannot be found.

```
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Repos\PangaeaAppliance\src\Service\<myproject>\obj\Debug\net6.0\StaticWebAssets.build.json'.
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.FileStream.. ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at Microsoft.AspNetCore.Razor.Tasks.GenerateStaticWebAssetsManifest.PersistManifest(StaticWebAssetsManifest manifest)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at Microsoft.AspNetCore.Razor.Tasks.GenerateStaticWebAssetsManifest.Execute()
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error : Could not find a part of the path 'C:\Repos\PangaeaAppliance\src\Service\<myproject>\obj\Debug\net6.0\StaticWebAssets.build.json'.
```

---
#### Feedback Bot on 8/20/2021, 02:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/20/2021, 03:49 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by javiercn**
Fixes https://github.com/dotnet/aspnetcore/issues/35349
Fixes https://github.com/dotnet/aspnetcore/issues/32744
Fixes https://github.com/dotnet/aspnetcore/issues/29561
Fixes https://github.com/dotnet/aspnetcore/issues/35561

### CODE REVIEW

File: src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs [hunk 1]
```diff
@@ -200,6 +200,10 @@ private static void ApplyUniqueMetadataProperties(ITaskItem candidate)
                         candidate.SetMetadata("AssetTraitName", "BlazorWebAssemblyResource");
                         candidate.SetMetadata("AssetTraitValue", "runtime");
                     }
+                    if (string.Equals(candidate.GetMetadata("ResolvedFrom"), "{HintPathFromItem}", StringComparison.Ordinal))
+                    {
+                        candidate.SetMetadata("OriginalItemSpec", candidate.ItemSpec);
+                    }
```
Comment (javiercn) [inline src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs:206]: We need this to account for the fact that the assembly was resolved using HintPath, otherwise static web assets thinks the `.csproj` is the original representation of the item and will try to copy that to the output folder.

Will be adding some more unit tests in this area

File: src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs [hunk 2]
```diff
@@ -821,5 +823,398 @@ public void Build_Fails_WhenConflictingAssetsFoundBetweenAStaticWebAssetAndAFile
...
+                    Path.Combine("staticwebassets", "PackageLibraryDirectDependency.bundle.scp.css"),
+                    Path.Combine("build", "Microsoft.AspNetCore.StaticWebAssets.props"),
+                    Path.Combine("build", "PackageLibraryDirectDependency.props"),
+                    Path.Combine("buildMultiTargeting", "PackageLibraryDirectDependency.props"),
+                    Path.Combine("buildTransitive", "PackageLibraryDirectDependency.props")
+                });
+        }
+
+        [Fact]
+        public void Pack_StaticWebAssets_WithoutFileExtension_AreCorrectlyPacked()
```
Comment (javiercn) [inline src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs:885]: https://github.com/dotnet/aspnetcore/issues/29561

GeneratePackageOnBuild doesn't matter (as the issue mentions)

File: src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs [hunk 3]
```diff
@@ -72,15 +65,61 @@ public void Build_Works()
...
             new FileInfo(Path.Combine(buildOutputDirectory, "wwwroot", "_framework", "System.dll.gz")).Should().Exist();
-            
+
             new FileInfo(Path.Combine(buildOutputDirectory, "wwwroot", "_framework", "blazorwasm.pdb")).Should().Exist();
             new FileInfo(Path.Combine(buildOutputDirectory, "wwwroot", "_framework", "RazorClassLibrary.pdb")).Should().Exist();
             new FileInfo(Path.Combine(buildOutputDirectory, "wwwroot", "_framework", "RazorClassLibrary.dll")).Should().Exist();
+        }
+
+        [Fact]
+        public void Build_Works_WithLibraryUsingHintPath()
```
Comment (javiercn) [inline src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmBuildIntegrationTest.cs:75]: dotnet/aspnetcore#35349

File: src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs [hunk 4]
```diff
@@ -103,6 +103,54 @@ public void Publish_WithDefaultSettings_Works()
             VerifyTypeGranularTrimming(blazorPublishDirectory);
         }
 
+        [Fact]
+        public void Publish_Works_WithLibraryUsingHintPath()
```
Comment (javiercn) [inline src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/WasmPublishIntegrationTest.cs:107]: dotnet/aspnetcore#35349

File: src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs [hunk 5]
```diff
@@ -147,6 +147,37 @@ public void StaticWebAssets_Publish_Hosted_Works()
                 intermediateOutputPath);
         }
 
+        [Fact]
+        public void StaticWebAssets_Publish_DoesNotIncludeXmlDocumentationFiles_AsAssets()
```
Comment (javiercn) [inline src/Tests/Microsoft.NET.Sdk.BlazorWebAssembly.Tests/BlazorWasmStaticWebAssetsIntegrationTest.cs:151]: Just a test to validate dotnet/aspnetcore#32744

File: src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs [hunk 6]
```diff
@@ -227,17 +231,25 @@ private static void ApplyUniqueMetadataProperties(ITaskItem candidate)
...
-                ".props" => "extension is .props is not supported.",
+                ".rsp" when fromMonoPackage => "extension is .rsp is not supported.",
+                ".props" when fromMonoPackage => "extension is .props is not supported.",
                 ".blat" when !timezoneSupport => "timezone support is not enabled.",
                 ".dat" when invariantGlobalization && fileName.StartsWith("icudt") => "invariant globalization is enabled",
-                ".json" when fileName == "emcc-props" => $"{fileName}{extension} is not used by Blazor",
+                ".json" when fromMonoPackage && fileName == "emcc-props" => $"{fileName}{extension} is not used by Blazor",
                 ".js" when fileName == "dotnet" => "dotnet.js is already processed by Blazor",
                 ".js" when assetType == "native" => $"{fileName}{extension} is not used by Blazor",
                 ".pdb" when !copySymbols => "copying symbols is disabled",
```
Comment (javiercn) [inline src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs:255]: dotnet/aspnetcore#32744

File: src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsTargetPaths.cs [hunk 7]
```diff
@@ -35,6 +37,11 @@ public override bool Execute()
                         PathPrefix,
                         UseAlternatePathDirectorySeparator ? Path.AltDirectorySeparatorChar : Path.DirectorySeparatorChar);
 
+                    if (AdjustPathsForPack && Path.GetExtension(targetPath) == "")
```
Comment (pranavkm) [inline src/RazorSdk/Tasks/StaticWebAssets/ComputeStaticWebAssetsTargetPaths.cs:40]:
```suggestion
                    if (AdjustPathsForPack && string.IsNullOrEmpty(Path.GetExtension(targetPath)))
```

**Review by pranavkm — APPROVED** [review]

File: src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets [hunk 8]
```diff
@@ -295,7 +295,8 @@ Copyright (c) .NET Foundation. All rights reserved.
 
   <Target Name="ResolveStaticWebAssetsConfiguration">
     <PropertyGroup>
-      <_StaticWebAssetsManifestBase>$(BaseIntermediateOutputPath)$(Configuration)\$(TargetFramework.ToLowerInvariant())\</_StaticWebAssetsManifestBase>
+      <_StaticWebAssetsManifestBase>$(BaseIntermediateOutputPath)$(Configuration)\</_StaticWebAssetsManifestBase>
+      <_StaticWebAssetsManifestBase Condition="'$(AppendTargetFrameworkToOutputPath)' != 'false'">$(_StaticWebAssetsManifestBase)\$(TargetFramework.ToLowerInvariant())\</_StaticWebAssetsManifestBase>
```
Comment (javiercn) [inline src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets:299]: https://github.com/dotnet/aspnetcore/issues/35561

File: src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs [hunk 9]
```diff
@@ -737,6 +737,46 @@ public void PublishProjectWithReferences_NoBuild_GeneratesPublishJsonManifestAnd
             intermediateOutputPath);
         }
 
+        [Fact]
+        public void PublishProjectWithReferences_AppendTargetFrameworkToOutputPathFalse_GeneratesPublishJsonManifestAndCopiesPublishAssets()
```
Comment (javiercn) [inline src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs:741]: https://github.com/dotnet/aspnetcore/issues/35561

File: src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets (hunk 8 above)
Comment (javiercn) [inline src/RazorSdk/Targets/Microsoft.NET.Sdk.Razor.StaticWebAssets.targets:299]:
```suggestion
      <_StaticWebAssetsManifestBase Condition="'$(AppendTargetFrameworkToOutputPath)' != 'false'">$(_StaticWebAssetsManifestBase)$(TargetFramework.ToLowerInvariant())\</_StaticWebAssetsManifestBase>
```

**Comment by VWilcox2000** [comment]
Had this issue after moving a .net 5.0 blazor app to 6.0.  Error went away after navigating to ..\obj\Debug and just an 'md net6.0' to create a net6.0 path.  Simple missing directory check on the MS side.
