### PR TITLE
Fix ignored paths used by binary tool

### LINKED ISSUE #4391: Binaries are not being removed from VMR when building from archive
When building the VMR from archive, the binaries are not removed from the VMR by the prep script.  The binary tool still runs, it just isn't removing any binaries. See [this run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2447398&view=logs&j=a5ccaa14-6811-5159-45fe-06b91679b5f1&t=88f87c3f-10bc-5f04-4d62-16700c86fdcc&l=99) as an example (internal Microsoft link)

### PR DESCRIPTION
**Pull request by ellahathaway**
Closes https://github.com/dotnet/source-build/issues/4391

The binary tool was not detecting binaries in repos where a .git repo was not present, because all files were being ignored upon initialization of said git repo.

Furthermore, some repos have been including binaries in their .gitignore files. This results in those binaries going undetected by the tool. See https://github.com/dotnet/dotnet/blob/8f3d7c26c231d54ad230f427a1005278c815dde6/src/fsharp/.gitignore#L43 as an example.

This PR changes the ignored paths from relying on the .gitignore files to simply hardcoding paths to ignore.

### CODE REVIEW

File: src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs [hunk 1]
```diff
@@ -45,44 +45,24 @@ public static class DetectBinaries
...
-            {
-                Directory.Delete(gitDirectory, true);
-            }
-        }
+            "**/.git/**/*",
+            "**/.dotnet/**/*",
+            "**/.packages/**/*",
+            "**/artifacts/**/*",
+            "**/prereqs/packages/**/*",
+            "src/nuget-client/NuGet.config",
```
Comment (mthalman) [inline src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs:57]: Why is this included since it's not a binary file?

File: src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs [hunk 2]
```diff
@@ -45,44 +45,24 @@ public static class DetectBinaries
         return unmatchedBinaryFiles;
     }
 
-    private static async Task<List<string>> GetIgnoredPatternsAsync(string targetDirectory)
+    private static async List<string> GetIgnoredPatterns(string targetDirectory)
```
Comment (mthalman) [inline src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs:48]: Why can't we also include the content in .gitignore?

File: src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs (hunk 1 above)
Comment (ellahathaway) [reply src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs:57]: Good point, it was in the VMR's ignore file and I did a copy of that here. I'll remove it.

File: src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs (hunk 2 above)
Comment (ellahathaway) [reply src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs:48]: The previous approach had used the .gitignore files. This is not good for three reasons:

1) Some repos have been including binaries in their .gitignore files. This results in those binaries going undetected by the tool. See https://github.com/dotnet/dotnet/blob/8f3d7c26c231d54ad230f427a1005278c815dde6/src/fsharp/.gitignore#L43 as an example.
2) In https://github.com/dotnet/source-build/issues/4391#issuecomment-2101062738, Omair pointed out that they "may not have the original source (and the .gitignore files) to copy over."
3) If there is no git repo but a gitignore file, the files must be added via `git add .` after initializing the git repo in order for the git clean -ndx command to work properly. Adding the files via `git add .` makes the tool run 35x longer.

Comment (omajid) [reply src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs:48]: Complicating it even more, on Fedora, we will have `.gitignore` file in a parent directory of the VMR, and that will be for an unrelated git repository. But I don't think that case needs to be fully handled here right now.

Comment (ellahathaway) [reply src/SourceBuild/content/eng/tools/BinaryToolKit/DetectBinaries.cs]: > Complicating it even more, on Fedora, we will have .gitignore file in a parent directory of the VMR, and that will be for an unrelated git repository. But I don't think that case needs to be fully handled here right now.

Luckily, I think that this case was covered. The old implementation (prior to changes in this PR) used the VMR (or whatever target directory was passed into the tool) as the root repo, so it should have only considered the .gitignore file in the VMR and all child .gitignore files.

**Review by mthalman — COMMENTED** [review]
Why are we ignoring certain binaries anyway? If we're not going to honor the .gitignore files of the repos, then what service are we providing to the developer anyway by keeping some binaries in the repo but not others?

**Comment by ellahathaway** [comment]
> Why are we ignoring certain binaries anyway? If we're not going to honor the .gitignore files of the repos, then what service are we providing to the developer anyway by keeping some binaries in the repo but not others?

My only thought is that we can't rely on the .gitignore files, but we should still ignore certain paths like the git files, artifacts, and downloaded PSB packages. If someone wants to run just the validation for example, it would be unfortunate if the tool removed their build artifacts.

**Comment by MichaelSimons** [comment]
Per an offline discussion w/@Ella, we decided the following:

1. The use case of binary detection/stripping is from a clean environment.  If you run the tool in a built environment, it is alright to detect all the built assets.
2. You can't trust/depend on .gitignore files because they can contain checked in files and we can't depend on the tool running in context of git
3. It is nice to have one place with the exclusions.  Having certain paths hard coded in the tool in addition to the allowed-binaries txt file makes understanding the behavior more difficult.
4. We need to exclude certain well known paths in order for the tool to work correctly from the prep script - .git, .dotnet, .packages, prereqs/packages

**Comment by MichaelSimons** [comment]
> Per an offline discussion w/@ella, we decided the following:
> 
> 1. The use case of binary detection/stripping is from a clean environment.  If you run the tool in a built environment, it is alright to detect all the built assets.
> 2. You can't trust/depend on .gitignore files because they can contain checked in files and we can't depend on the tool running in context of git
> 3. It is nice to have one place with the exclusions.  Having certain paths hard coded in the tool in addition to the allowed-binaries txt file makes understanding the behavior more difficult.
> 4. We need to exclude certain well known paths in order for the tool to work correctly from the prep script - .git, .dotnet, .packages, prereqs/packages

File: src/SourceBuild/content/eng/allowed-sb-binaries.txt [hunk 3]
```diff
@@ -3,6 +3,11 @@
 # This file is used by the Binary Tool to remove binaries from the VMR
 # If importing a file, include the relative path to the file
 
+.git/
```
Comment (MichaelSimons) [inline src/SourceBuild/content/eng/allowed-sb-binaries.txt:6]: Consider adding a comment indicating that this section is for well known non-checked in infrastructure paths created by prep with known binaries.

**Review by MichaelSimons — APPROVED** [review]

**Review by mthalman — APPROVED** [review]

**Review by omajid — APPROVED** [review]

**Review by MichaelSimons — APPROVED** [review]
