### PR TITLE
Use ProjectGraph for DTB

### LINKED ISSUE #49115: dotnet watch fails with large solutions due to locked files.
### Describe the bug
Running `dotnet watch build --project .\MySolution.sln` on a solution with ~30 projects and ~50k lines of code fails to compile due to a file being locked by the same process.

### To Reproduce
I couldn't reproduce it through a minimal sample as my suspicion is due to a race condition with large projects. Also, running the command multiple times yields different number of projects that failed with the same exception, so the failure is non-deterministic.

### Exceptions (if any)
```
dotnet watch ⌚           dotnet watch ⌚    Build FAILED.
dotnet watch ⌚           "D:\Repo\MySolution.sln" (GenerateWatchList target) (1) ->
dotnet watch ⌚           "D:\Repo\ChildProject\ChildProject.csproj" (GenerateWatchList target) (17) ->
dotnet watch ⌚           (GenerateWatchList target) ->
dotnet watch ⌚             C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018: The "FileSetSerializer" task failed unexpectedly. [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018: System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Local\Temp\tmp43s5ay.tmp' because it is being used by another process. [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable1 unixCreateMode) [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable1 unixCreateMode) [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable1 unixCreateMode) [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018:    at System.IO.File.Create(String path) [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018:    at DotNetWatchTasks.FileSetSerializer.Execute() [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute() [D:\Repo\ChildProject\ChildProject.csproj]
dotnet watch ⌚           C:\Program Files\dotnet\sdk\8.0.410\DotnetTools\dotnet-watch\8.0.410-servicing.25266.33\tools\net8.0\any\DotNetWatch.targets(20,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\Repo\ChildProject\ChildProject.csproj] 
```
### Further technical details
- Include the output of `dotnet --info`
.NET SDK:
 Version:           8.0.410
 Commit:            0c2bff86e8
 Workload version:  8.0.400-manifests.5d19dc53
 MSBuild version:   17.11.31+933b72e36

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.410\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.13.36105.23, VS 17.14.36025.13
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      9.0.5
  Architecture: x64
  Commit:       e36e4d1a8f

.NET SDKs installed:
  8.0.410 [C:\Program Files\dotnet\sdk]
  9.0.204 [C:\Program Files\dotnet\sdk]
  9.0.300-preview.0.25177.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  D:\Repo\global.json

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
vscode 1.100.2

### PR DESCRIPTION
**Pull request by tmat**
Remove usage of `MSBuildFileSetFactory` and `DotNetWatch.targets` for design-time build performed by dotnet-watch Hot Reload.
Replace the logic using `ProjectGraph` evaluation. Avoids launching additional `dotnet build` just to perform design-time builds.
The next step would be to switch the implementation to use Roslyn MSBuild host APIs to avoid duplicating DTB logic (both at runtime and implementation details).

Keeps the original implementation around for `dotnet-watch --no-hot-reload` for now.

Implements https://github.com/dotnet/sdk/issues/40214
Fixes https://github.com/dotnet/sdk/issues/49542
Fixes https://github.com/dotnet/sdk/issues/49115

### CODE REVIEW

**Comment by tmat** [comment]
@DustinCampbell ptal

File: src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs [hunk 1]
```diff
@@ -29,4 +31,147 @@ public void WatchFiles(FileWatcher fileWatcher)
         fileWatcher.WatchContainingDirectories(Files.Keys, includeSubdirectories: true);
         fileWatcher.WatchFiles(BuildFiles);
     }
+
+    /// <summary>
+    /// Loads project graph and performs design-time build.
+    /// </summary>
+    public static EvaluationResult? TryCreate(
```
Comment (tmat) [inline src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs:37]: Eventually I'd like to move this over to use Roslyn msbuild host API.

File: src/BuiltInTools/dotnet-watch/Build/ProjectGraphUtilities.cs [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+using Microsoft.DotNet.Cli;
+
+namespace Microsoft.DotNet.Watch;
+
+internal static class ProjectGraphUtilities
+{
+    /// <summary>
+    /// Tries to create a project graph by running the build evaluation phase on the <see cref="rootProjectFile"/>.
+    /// </summary>
+    public static ProjectGraph? TryLoadProjectGraph(
```
Comment (tmat) [inline src/BuiltInTools/dotnet-watch/Build/ProjectGraphUtilities.cs:17]: Moved from MsBuildFileSetFactory

File: src/BuiltInTools/dotnet-watch/Build/ProjectGraphUtilities.cs [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+                {
+                    reporter.Warn(e.Message);
+                }
+            }
+        }
+
+        return null;
+    }
+
+    public static string GetDisplayName(this ProjectGraphNode projectNode)
```
Comment (tmat) [inline src/BuiltInTools/dotnet-watch/Build/ProjectGraphUtilities.cs:74]: Moved from ProjectGraphNodeExtensions

File: src/BuiltInTools/dotnet-watch/Watch/MsBuildFileSetFactory.cs [hunk 4]
```diff
@@ -196,57 +208,5 @@ private static string FindTargetsFile()
             var targetPath = searchPaths.Select(p => Path.Combine(p, WatchTargetsFileName)).FirstOrDefault(File.Exists);
             return targetPath ?? throw new FileNotFoundException("Fatal error: could not find DotNetWatch.targets");
         }
-
```
Comment (tmat) [inline src/BuiltInTools/dotnet-watch/Watch/MsBuildFileSetFactory.cs:199]: Moved.

File: test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs [hunk 5]
```diff
@@ -1009,7 +1009,7 @@ public static void PrintDirectoryName([CallerFilePathAttribute] string filePath
             Directory.CreateDirectory(oldSubdir);
             File.WriteAllText(Path.Combine(oldSubdir, "Foo.cs"), source);
 
-            App.Start(testAsset, [], "AppWithDeps");
+            App.Start(testAsset, ["--non-interactive"], "AppWithDeps");
```
Comment (tmat) [inline test/dotnet-watch.Tests/HotReload/ApplyDeltaTests.cs:1012]: Fixes unrelated intermittent failures.

File: src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs [hunk 6]
```diff
@@ -1,22 +1,24 @@
 // Licensed to the .NET Foundation under one or more agreements.
 // The .NET Foundation licenses this file to you under the MIT license.
 
+using System.Collections.Immutable;
+using System.Xml;
```
Comment (DustinCampbell) [inline src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs]: What's used from `System.Xml` in this file? I couldn't spot anything.

File: src/BuiltInTools/dotnet-watch/Build/BuildNames.cs
Comment (DustinCampbell) [inline src/BuiltInTools/dotnet-watch/Build/BuildNames.cs:1]: It's very helpful to see altogether. Thanks!

**Review by DustinCampbell — APPROVED** [review]

File: src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs [hunk 7]
```diff
@@ -29,4 +31,147 @@ public void WatchFiles(FileWatcher fileWatcher)
...
+        var fileItems = new Dictionary<string, FileItem>();
+
+        foreach (var project in projectGraph.ProjectNodesTopologicallySorted)
+        {
+            var projectInstance = project.ProjectInstance;
+
+            // Skip non-C# projects. Consider supporting other project types.
+            // We could collect Watch items and watch the directory tree of the project for changes.
+            // Any change to these projects would trigger rebuild.
+            if (Path.GetExtension(projectInstance.FullPath) != ".csproj")
```
Comment (tmat) [inline src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs]: Actually need to handle this better, we already have tests validating F#...

File: src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs (hunk 6 above)
Comment (tmat) [reply src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs]: Not needed anymore.

File: src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs (hunk 7 above)
Comment (tmat) [reply src/BuiltInTools/dotnet-watch/Build/EvaluationResult.cs]: Fixed.

**Review by DustinCampbell — COMMENTED** [review]
I went through the latest updates to this PR and it still looks good to me.

✅
