### PR TITLE
[`dotnet list package`]Resolve relative paths

### LINKED ISSUE #12954: `dotnet list package` cannot resolve relative path
### NuGet Product Used

dotnet.exe

### Product Version

dotnet: 8.0.0-rc.2.23479.6, NuGet Command Line 6.8.0.117

### Worked before?

_No response_

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Follow-up https://github.com/dotnet/sdk/issues/36254

### Describe the bug
`dotnet list XXX.sln package` fails to list packages

### To Reproduce
I'm having directory with multiple sln files inside so I have to point direct sln for `dotnet list package`.

### Exceptions (if any)

- `PATH TO SLN DIRECOTRY> dotnet list XXX.sln package`

```
error: Unexpected failure reading NuGet.Config. Path: 'PATH TO SLN DIRECOTRY\XXX.sln\NuGet.Config'.
error:   Cannot create 'PATH TO SLN DIRECOTRY\XXX.sln' because a file or directory with the same name already exists.
```

- `PATH TO SLN DIRECOTRY> dotnet list XXX.sln package --config NuGet.Config`
```
PATH TO SLN DIRECOTRY>dotnet list XXX.sln package --config NuGet.Config
error: MSB0001: Internal MSBuild Error: Quote.sln unexpectedly not a rooted path
```

- Only variant with full path works
`PATH TO SLN DIRECOTRY> dotnet list "PATH TO SLN DIRECOTRY\XXX.sln" package --config "PATH TO SLN DIRECOTRY\NuGet.Config"`

### Further technical details
```
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  6.0.317 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.2.23502.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.2.23479.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  PATH TO SLN DIRECOTRY\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

global.json used for solution
```
{
  "sdk": {
    "version": "8.0.100-rc.2.23502.2",
    "rollForward": "latestMinor"
  }
}

```

### Verbose Logs

_No response_

### PR DESCRIPTION
**Pull request by Nigusu-Allehu**
Fixes : https://github.com/NuGet/Home/issues/12954

This is a fix to a regression that was caused by https://github.com/dotnet/sdk/pull/20449
- It makes sure the SDK resolves relative paths for a solution/project before calling the NuGet API.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs [hunk 1]
```diff
@@ -16,7 +16,13 @@ internal class ListPackageReferencesCommand : CommandBase
...
             ParseResult parseResult) : base(parseResult)
         {
-            _fileOrDirectory = parseResult.GetValue(ListCommandParser.SlnOrProjectArgument);
+            _fileOrDirectory = GetAbsolutePath(Directory.GetCurrentDirectory(),
+                parseResult.GetValue(ListCommandParser.SlnOrProjectArgument));
+        }
+
+        private static string GetAbsolutePath(string currentDirectory, string relativePath)
+        {
+            return Path.GetFullPath(Path.Combine(currentDirectory, relativePath));
```
Comment (donnie-msft) [inline src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs:25]: I'm not sure if it's a real scenario or not, but wanted to point out that this `Path.Combine` will introduce a new possible exception. It will throw `ArgumentException` if `SlnOrProjectArgument` is null.

**Review by donnie-msft — APPROVED** [review]

File: src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs (hunk 1 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs:25]: You are right. But when `SlnOrProjectArgument` is null from the user, we default to the current directory internally so we should be ok.

File: src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs [hunk 2]
```diff
@@ -16,7 +16,13 @@ internal class ListPackageReferencesCommand : CommandBase
         public ListPackageReferencesCommand(
             ParseResult parseResult) : base(parseResult)
         {
-            _fileOrDirectory = parseResult.GetValue(ListCommandParser.SlnOrProjectArgument);
+            _fileOrDirectory = GetAbsolutePath(Directory.GetCurrentDirectory(),
+                parseResult.GetValue(ListCommandParser.SlnOrProjectArgument));
```
Comment (nkolev92) [inline src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs:20]: This means that NuGet side, we require an absolute path. 

We should probably add an absolute path check in the NuGet code that way it's immediately what went wrong when it goes wrong.

File: test/dotnet-list-package.Tests/GivenDotnetListPackage.cs [hunk 3]
```diff
@@ -349,5 +349,51 @@ public void ItRunsInCurrentDirectoryWithPoundInPath()
                 .Should()
                 .Pass();
         }
+
+        [Fact]
+        public void ItRecognizesRelativePathsForAProject()
```
Comment (nkolev92) [inline test/dotnet-list-package.Tests/GivenDotnetListPackage.cs:354]: We also need an equivalent test on the NuGet side as well. 

The issue here is integration between the 2 components/repos, so we should add tests in both repos.

File: test/dotnet-list-package.Tests/GivenDotnetListPackage.cs [hunk 4]
```diff
@@ -349,5 +349,51 @@ public void ItRunsInCurrentDirectoryWithPoundInPath()
...
+            var projectDirectory = testAsset.Path;
+
+            new RestoreCommand(testAsset)
+                .Execute()
+                .Should()
+                .Pass();
+
+            new ListPackageCommand(Log)
+                .WithProject("TestAppSimple.csproj")
+                .WithWorkingDirectory(projectDirectory)
```
Comment (nkolev92) [inline test/dotnet-list-package.Tests/GivenDotnetListPackage.cs:370]: Can we add a test where the relative path is not just a file within the same folder?

File: src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs (hunk 2 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs:20]: That is a good idea! Will work on another PR that does that.

File: test/dotnet-list-package.Tests/GivenDotnetListPackage.cs (hunk 3 above)
Comment (Nigusu-Allehu) [reply test/dotnet-list-package.Tests/GivenDotnetListPackage.cs:354]: What would be testing in the NuGet side though? Currently, the contract is that dotnet SDK should always call NuGet with an absolute path. NuGet is not expected to recognize relative paths.

File: test/dotnet-list-package.Tests/GivenDotnetListPackage.cs (hunk 4 above)
Comment (Nigusu-Allehu) [reply test/dotnet-list-package.Tests/GivenDotnetListPackage.cs:370]: Good catch. Will add one more test for the scenario.

File: test/dotnet-list-package.Tests/GivenDotnetListPackage.cs (hunk 3 above)
Comment (nkolev92) [reply test/dotnet-list-package.Tests/GivenDotnetListPackage.cs:354]: We have tests that integrate a version of the .NET SDK with NuGet.
https://github.com/NuGet/NuGet.Client/tree/dev/test/NuGet.Core.FuncTests/Dotnet.Integration.Test downloads a version of the SDK and patches on top of that, effectively testing NuGet & .NET.

Comment (Nigusu-Allehu) [reply test/dotnet-list-package.Tests/GivenDotnetListPackage.cs:354]: https://github.com/NuGet/Home/issues/13238 Added a tracking issue

File: src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs (hunk 2 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/commands/dotnet-list/dotnet-list-package/ListPackageReferencesCommand.cs:20]: https://github.com/NuGet/Home/issues/13238 Added a tracking issue

**Review by nkolev92 — APPROVED** [review]

**Comment by Nigusu-Allehu** [comment]
@dotnet-cli CI is not running, could you please take a look?

**Comment by Nigusu-Allehu** [comment]
backport to release/8.0.3xx

**Comment by g1df** [comment]
Hello, 

I see the fix is available on release/8.0.3xx and release/8.0.4xx branches (as well as main) but not in the 8.0.3 and 8.0.4 releases which are based on 8.0.2x tags.
Is this normal release behaviour ?
Will this fix be released soon ?

Thanks

**Comment by nkolev92** [comment]
@g1df 
Versions like a single digit at the back are runtime, while this is a fix in the SDK.

**Comment by nkolev92** [comment]
It's currently in late previews, so next month.
