### PR TITLE
Fix forwarding DOTNET_ROOT

### LINKED ISSUE #49436: [NetTestingE2E][Regression] Error "The library hostfxr.dll was found..." will throw when executing "dotnet test --arch x86 --diag:log1.txt".
### Notes:
1.This issue doesn't repro on 10.0.100-preview.5.25263.104.
2.Repro VM: 172.16.195.106

### Repro steps:
1. On Win 10 22H2 x64 VM:
2.Install dotnet-sdk-10.0.100-preview.6.25316.103-win-x64.exe & dotnet-sdk-10.0.100-preview.6.25316.103-win-x86.exe
3. Launch Powershell and execute below commads:
>mkdir c:\hltest\xunit2
>dotnet new xunit
>dotnet restore
>dotnet build
>dotnet test --arch x86 --diag:log2.txt

### Expected Result:
The command will run successfully.

### Actual Result:
Test runs aborted.

Image

### Logs:
PS C:\hltest\xunit2> dotnet test --arch x86 --diag:log2.txt
Restore complete (0.8s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  xunit2 succeeded with 1 warning(s) (0.8s) → bin\Debug\net10.0\win-x86\xunit2.dll
    C:\hltest\xunit2\UnitTest1.cs(18,21): warning CS8602: Dereference of a possibly null reference.
Logging Vstest Diagnostics in file: C:\hltest\xunit2\log1.txt
Failed to load the dll from [C:\Program Files\dotnet\host\fxr\10.0.0-preview.6.25316.103\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\10.0.0-preview.6.25316.103\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
Testhost process for source(s) 'C:\hltest\xunit2\bin\Debug\net10.0\win-x86\xunit2.dll' exited with error: Failed to load the dll from [C:\Program Files\dotnet\host\fxr\10.0.0-preview.6.25316.103\hostfxr.dll], HRESULT: 0x800700C1
The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\10.0.0-preview.6.25316.103\hostfxr.dll failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=798306
. Please check the diagnostic logs for more information.
  xunit2 test failed with 1 error(s) (0.8s)
    C:\hltest\xunit2\bin\Debug\net10.0\win-x86\xunit2.dll : error TESTRUNABORT: Test Run Aborted.

Build failed with 1 error(s) and 1 warning(s) in 3.1s

**Log2.txt:** Detailed info please refer to attached file:
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetDefinedTypes()
   at System.Reflection.RuntimeModule.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[TPluginInfo,TExtension](Assembly assembly, Dictionary`2 pluginInfos, String filePath) in D:\a\_work\1\s\src\vstest\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginDiscoverer.cs:line 159
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args) in D:\a\_work\1\s\src\vstest\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginCache.cs:line 514
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
TpTrace Warning: 0 : 15176, 2, 2025/06/17, 02:51:05.822, 56111809314, vstest.console.dll, LoaderExceptions: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args) in D:\a\_work\1\s\src\vstest\src\Microsoft.TestPlatform.Common\ExtensionFramework\TestPluginCache.cs:line 514
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)

### dotnet --info:
PS C:\Windows\system32> dotnet --info
.NET SDK:
 Version:           10.0.100-preview.6.25316.103
 Commit:            20343176cf
 Workload version:  10.0.100-manifests.dd8061fd
 MSBuild version:   17.15.0-preview-25316-103+20343176c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\10.0.100-preview.6.25316.103\

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
Workloads are configured to install and update using workload versions, but none were found. Run "dotnet workload restore" to install a workload version.

Host:
  Version:      10.0.0-preview.6.25316.103
  Architecture: x64
  Commit:       20343176cf

.NET SDKs installed:
  10.0.100-preview.6.25316.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.0-preview.6.25316.103 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.0-preview.6.25316.103 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 10.0.0-preview.6.25316.103 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

### &'C:\Program Files (x86)\dotnet\dotnet.exe' --info:
PS C:\Windows\system32> & 'C:\Program Files (x86)\dotnet\dotnet.exe' --info
.NET SDK:
 Version:           10.0.100-preview.6.25316.103
 Commit:            20343176cf
 Workload version:  10.0.100-manifests.dd8061fd
 MSBuild version:   17.15.0-preview-25316-103+20343176c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\10.0.100-preview.6.25316.103\

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
Workloads are configured to install and update using workload versions, but none were found. Run "dotnet workload restore" to install a workload version.

Host:
  Version:      10.0.0-preview.6.25316.103
  Architecture: x86
  Commit:       20343176cf

.NET SDKs installed:
  10.0.100-preview.6.25316.103 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 10.0.0-preview.6.25316.103 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 10.0.0-preview.6.25316.103 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 10.0.0-preview.6.25316.103 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x64   [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

[log2.txt](https://github.com/user-attachments/files/20767403/log2.txt)

### PR DESCRIPTION
**Pull request by nohwnd**
Use VSTEST_DOTNET_ROOT_PATH and VSTEST_DOTNET_ROOT_ARCHITECTURE to tell to child vstest.console where the dotnet sdk is, so we can use it to setup dotnet_root for testhost.exe correctly, so testhost can pick up privately instaled dotnet sdk.

Needs https://github.com/microsoft/vstest/pull/15184 to be merged first.

Fix #49436

### CODE REVIEW

File: src/Cli/dotnet/Commands/Test/TestCommand.cs [hunk 1]
```diff
@@ -144,7 +144,9 @@ private static int ForwardToVSTestConsole(ParseResult parseResult, string[] args
             convertedArgs.Add($"--testSessionCorrelationId:{testSessionCorrelationId}");
         }
 
-        int exitCode = new VSTestForwardingApp(convertedArgs).Execute();
+        string archArg = parseResult.ForwardedOptionValues<IReadOnlyCollection<string>>(TestCommandParser.GetCommand(), "--arch")?.SingleOrDefault() ?? null;
```
Comment (Youssef1313) [inline src/Cli/dotnet/Commands/Test/TestCommand.cs]: I know it's probably discouraged practice to do `dotnet test -p:RuntimeIdentifier=...` compared to `dotnet test --arch ...`, but I think it's valid and works today. So, it's better IMO to read `RuntimeIdentifier` from project evaluation rather than figuring out `--arch` from command-line parse result.

File: src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs [hunk 2]
```diff
@@ -38,14 +39,57 @@ private static string GetVSTestExePath()
...
+
+        static string[] GetRootVariablesToInspect(Architecture processArchitecture)
+        {
+            switch (processArchitecture)
+            {
+                case Architecture.X86:
+                    return ["DOTNET_ROOT_X86", "DOTNET_ROOT(x86)"];
+
+                case Architecture.X64:
+                    return ["DOTNET_ROOT_X64", "DOTNET_ROOT"];
```
Comment (Youssef1313) [inline src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]: If user specified `DOTNET_ROOT` already, do we want to set `DOTNET_ROOT_X64` or not?

Same question for X86.

I'm asking because you are returning `DOTNET_ROOT` in this method only for X64.

File: src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs [hunk 3]
```diff
@@ -38,14 +39,57 @@ private static string GetVSTestExePath()
...
+
+                default:
+                    return [$"DOTNET_ROOT_{processArchitecture.ToString().ToUpperInvariant()}"];
```
Comment (nohwnd) [inline src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]:
```suggestion
                    return [$"DOTNET_ROOT_{processArchitecture.ToString().ToUpperInvariant()}", "DOTNET_ROOT"];
```

File: src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs (hunk 2 above)
Comment (nohwnd) [reply src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]: I think no. I want to grab the value from the more specific value, and as well as less specific value and use that if it was specified externally. If it was not specified externally then we set the winapphost_dotnet_root. 

TBH I cannot really test this because it does not work in the dogfooding build because that does not have runtimes for multiple architectures.

File: src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs (hunk 3 above)
Comment (nohwnd) [reply src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]: Here I am not sure if we should try grabbing the more generic one from the environment as well.

File: src/Cli/dotnet/Commands/Test/TestCommand.cs [hunk 4]
```diff
@@ -277,9 +280,11 @@ internal static int RunArtifactPostProcessingIfNeeded(string testSessionCorrelat
             artifactsPostProcessArgs.Add($"--diag:{parseResult.GetValue(TestCommandParser.DiagOption)}");
         }
 
+        string archArg = parseResult.ForwardedOptionValues<IReadOnlyCollection<string>>(TestCommandParser.GetCommand(), "--arch")?.SingleOrDefault() ?? null;
```
Comment (Youssef1313) [inline src/Cli/dotnet/Commands/Test/TestCommand.cs]: Also note that `amd64` might be a valid value for `--arch` but it should be treated as x64.

Comment (Youssef1313) [inline src/Cli/dotnet/Commands/Test/TestCommand.cs]: I'm also not sure of the interaction of setting `--os` without `--arch`. It might be forwarding something to `RuntimeIdentifier` but I don't know how much the logic involved is in there

File: src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs (hunk 2 above)
Comment (Youssef1313) [reply src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]: I thought `dotnet run` just sets `DOTNET_ROOT_<arch>` regardless of whether `DOTNET_ROOT` is set. So I thought it may make sense to follow that behavior. But I'm also not 100% sure.

Comment (nohwnd) [reply src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]: yes, but the consumer of that is the apphost application. for us we set the winapphost, and that is then picked up by vstest.console, and set for the testhosts. So probably we will need to change it on both sides (in sdk and vstest) to set the  winapphost_dotnet_root_<arch>, and in vstest.console pick that up, and set it as dotnet_root_<arch>. This way we avoid pushing dotnet_root (with no arch) and x86 testhosts

Comment (nohwnd) [reply src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]: or x64 on arm64 for that matter.

Comment (Youssef1313) [reply src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]: I'm not following, but let me reword the question. Why are we inspecting `DOTNET_ROOT` under x64 but not under x86

Comment (nohwnd) [reply src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs]: Looking at it with fresh eyes I don't think that logic is correct. We should only set the winapphost_ for the current architecture of the process, and then decide on vstest side what to do, where we hopefully know what version of testhost we have. preferring always the more specific env variable, to avoid setting dotnet_root -> x64 dotnet, for testhost.x86.exe, because that will pick it up and we will get the same error we have now.

File: src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs [hunk 5]
```diff
@@ -38,14 +38,17 @@ private static string GetVSTestExePath()
...
-    internal static (bool hasRootVariable, string rootVariableName, string rootValue) GetRootVariable()
+    internal static Dictionary<string, string> GetVSTestRootVariables()
     {
-        string rootVariableName = Environment.Is64BitProcess ? "DOTNET_ROOT" : "DOTNET_ROOT(x86)";
-        bool hasRootVariable = Environment.GetEnvironmentVariable(rootVariableName) != null;
-        string rootValue = hasRootVariable ? null : Path.GetDirectoryName(new Muxer().MuxerPath);
-
-        // We rename env variable to support --arch switch that relies on DOTNET_ROOT/DOTNET_ROOT(x86)
-        // We provide VSTEST_WINAPPHOST_ only in case of testhost*.exe removing VSTEST_WINAPPHOST_ prefix and passing as env vars.
-        return (hasRootVariable, $"VSTEST_WINAPPHOST_{rootVariableName}", rootValue);
```
Comment (Youssef1313) [inline src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs:49]: I'm double checking, this is fine because this logic isn't going to be used with old vstest.console.exe because it's guaranteed that we use vstest.console.exe that's part of SDK, and we will only merge this PR after inserting the fix on vstest side. Is that correct?

**Review by Youssef1313 — APPROVED** [review]
This feels much better than what I originally had in mind. Hopefully it's going to work the way we expect it to :)

*If* we needed to service this in .NET 9 or 8, I assume we will need to also service the respective vstest versions inserted in 8 and 9?

File: src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs (hunk 5 above)
Comment (nohwnd) [reply src/Cli/dotnet/Commands/Test/VSTestForwardingApp.cs:49]: Yes, the old way of doing this can be removed. It also does not seem that people use that env variable on its own.

**Comment by nohwnd** [comment]
Update merged, let's test it together. https://github.com/dotnet/sdk/pull/49809
