### PR TITLE
Blame switch args should not swallow following arg

### LINKED ISSUE #20241: "dotnet test --blame-crash" swallows first test assembly
The documentation at https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test claims it takes no arguments, but in fact it discards the first test assembly.

This doesn't happen if you use it with a solution, but we're specifying test assemblies because that's considerably faster; the real use case has a much longer command line and it took me a while to realise why some of my tests were missing.

> C:\Users\pclay\foo>dotnet test --blame-crash UnitTests.dll
> Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210518-01
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> No test source files were specified.
> 
> C:\Users\pclay\foo>dotnet test --blame-crash dummyarg UnitTests.dll
> Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210518-01
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.

This also doesn't happen if any other valid argument is present after --blame-crash:

> C:\Users\pclay\foo>dotnet test --blame-crash --logger:nunit;LogFilePath=nunit-result.xml UnitTests.dll
> Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210518-01
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> Starting test execution, please wait...
> A total of 1 test files matched the specified pattern.

Version:

C:\Users\pclay\foo>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes #20241 and [AB#1489335](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1489335)

Given the many changes I did, I went ahead to fix all styling following the in-place `.editorconfig`. Let me know if you prefer to postpone the styling changes to a follow-up PR.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs [hunk 1]
```diff
@@ -1,58 +1,87 @@
...
+                "--testSessionCorrelationId",
+                "--artifactsProcessingMode-collect"
+            );
+
+        /// <summary>
+        /// The expanded (after applying argument mapping) list of arguments to consider
+        /// as switches (i.e., for which we don't expect a non dashed arg). This also
+        /// includes ignored arguments.
+        /// </summary>
+        private static readonly ImmutableHashSet<string> s_switchArguments
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:72]: For all of these arguments, we were always swallowing the dll/exe if it was passed right after.

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs [hunk 2]
```diff
@@ -148,14 +177,39 @@ public List<string> Convert(string[] args, out List<string> ignoredArgs)
...
+                        else
+                        {
+                            newArgList.Add(activeArgument);
+                        }
+
+                        // The only real case where we would end-up here is when the item under test (.dll or .exe)
+                        // is passed as last argument so we could potentially check the extension and for invalid ones,
+                        // either add it to the ignored args or have a specific failure.
+                        newArgList.Add(arg);
+                    }
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:196]: Main change to avoid swallowing the arg when active argument is a switch.

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs [hunk 3]
```diff
@@ -148,14 +177,39 @@ public List<string> Convert(string[] args, out List<string> ignoredArgs)
...
-                        blame.UpdateBlame(activeArgument, arg);
+                        if (!BlameArgs.IsBlameSwitch(activeArgument)
+                            || BlameArgs.IsLegacyBlame(activeArgument, arg))
+                        {
+                            blame.UpdateBlame(activeArgument, arg);
+                        }
+                        else
+                        {
+                            newArgList.Add(arg);
+                        }
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:212]: Main change to avoid swallowing the arg when active argument is a switch (blame switch here).

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs [hunk 4]
```diff
@@ -1,58 +1,87 @@
...
-            "--testSessionId",
-            "--artifacts-processing-mode"
-        };
+        private static readonly ImmutableDictionary<string, string> s_argumentMapping
+            = new Dictionary<string, string>()
+            {
+                ["-h"] = "--help",
+                ["-s"] = "--settings",
+                ["-t"] = "--listtests",
+                // .NET 7 breaking change, before we had ["-a"] = "--testadapterpath",
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:28]: Added a comment here so that we don't have to know or lookup for breaking changes that occurred in the code.

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs [hunk 5]
```diff
@@ -1,58 +1,87 @@
...
+                ["-a"] = "--platform",
+                ["-l"] = "--logger",
+                ["-f"] = "--framework",
+                ["-d"] = "--diag",
+                ["--filter"] = "--testcasefilter",
+                ["--list-tests"] = "--listtests",
+                ["--test-adapter-path"] = "--testadapterpath",
+                // .NET 7 breaking change, before we had ["-r"] = "--resultsdirectory",
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:36]: Same remark about the breaking change note.

**Review by MarcoRossignoli — APPROVED** [review]
Great thx LGTM

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs [hunk 6]
```diff
@@ -148,14 +177,39 @@ public List<string> Convert(string[] args, out List<string> ignoredArgs)
...
+                        // either add it to the ignored args or have a specific failure.
+                        newArgList.Add(arg);
+                    }
+                    else if (s_ignoredArguments.Contains(activeArgument))
                     {
                         ignoredArgs.Add(activeArgument);
                         ignoredArgs.Add(arg);
                     }
-                    else if (blame.IsBlameArg(activeArgument, arg))
+                    else if (BlameArgs.IsBlameArg(activeArgument))
```
Comment (nohwnd) [inline src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:202]: Maybe explain here (if that is the correct place) or in the called method what is the problem with --blame and --blame CollectDump. I know what the problem is, but I still can't see what is going on here.

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs [hunk 7]
```diff
@@ -148,14 +177,39 @@ public List<string> Convert(string[] args, out List<string> ignoredArgs)
...
+                        {
+                            newArgList.Add(activeArgument);
+                        }
+
+                        // The only real case where we would end-up here is when the item under test (.dll or .exe)
+                        // is passed as last argument so we could potentially check the extension and for invalid ones,
+                        // either add it to the ignored args or have a specific failure.
+                        newArgList.Add(arg);
+                    }
+                    else if (s_ignoredArguments.Contains(activeArgument))
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:197]:
```suggestion
		    // When reaching this point, we are sure that activeArgument is not a switch so we
		    // can add it and the arg to the list of ignored arguments.
                    else if (s_ignoredArguments.Contains(activeArgument))
```

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs [hunk 8]
```diff
@@ -148,14 +177,39 @@ public List<string> Convert(string[] args, out List<string> ignoredArgs)
...
                     {
                         ignoredArgs.Add(activeArgument);
                         ignoredArgs.Add(arg);
                     }
-                    else if (blame.IsBlameArg(activeArgument, arg))
+                    else if (BlameArgs.IsBlameArg(activeArgument))
                     {
-                        blame.UpdateBlame(activeArgument, arg);
+                        if (!BlameArgs.IsBlameSwitch(activeArgument)
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:204]:
```suggestion
                        // We know that activeArgument is a blame kind, we now want to see if arg is linked to the
                        // blame or not. 
                        // If activeArgument is a not blame switch (e.g., --blame-crash-dump-type full) or if it is the
                        // legacy blame syntax (e.g., --blame CollectDump;DumpType=full) then we do want to 
                        // update the blame combination based both on activeArgument and arg.
                        // Otherwise, we have a simple blame switch (e.g., --blame some.dll) so we can add it to the
                        // args list.
```

File: src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs (hunk 6 above)
Comment (Evangelink) [reply src/Cli/dotnet/commands/dotnet-test/VSTestArgumentConverter.cs:211]: Let me know if that's clearer now.

**Comment by nohwnd** [comment]
Looks okay, but maybe save the code-style refactorings for a separate pr next time.

**Review by nohwnd — APPROVED** [review]
