### PR TITLE
Handle locked files and logging on workload install rollback

### LINKED ISSUE #17206: dotnet workload install results in file lock error during rollback
```
> dotnet workload install microsoft-net-sdk-blazorwebassembly-aot --skip-manifest-update

Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.0-preview.4.21222.10...
Pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.0-preview.4.21222.10 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.MonoAOTCompiler.Task version 6.0.0-preview.4.21222.10...
Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.0-preview.4.21222.10...
Pack Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.0-preview.4.21222.10 is already installed.
Writing workload pack installation record for Microsoft.NET.Runtime.WebAssembly.Sdk version 6.0.0-preview.4.21222.10...
Installing pack Microsoft.NETCore.App.Runtime.AOT.Cross.browser-wasm version 6.0.0-preview.4.21222.10...
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.netcore.app.runtime.aot.cross.browser-wasm/index.json
[NuGet Manager] [Info]   GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/registrations2-semver2/microsoft.netcore.app.runtime.aot.cross.browser-wasm/index.json
[NuGet Manager] [Info]   NotFound https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/825db618-e3eb-4426-ba54-b1d6e6c944d8/nuget/v3/registrations2-semver2/microsoft.netcore.app.runtime.aot.cross.browser-wasm/index.json 154ms
[NuGet Manager] [Info]   NotFound https://api.nuget.org/v3/registration5-gz-semver2/microsoft.netcore.app.runtime.aot.cross.browser-wasm/index.json 353ms
System.IO.IOException: The process cannot access the file 'D:\temp\dotnet6\metadata\workloads\InstalledPacks\v1\Microsoft.NET.Runtime.MonoAOTCompiler.Task\6.0.0-preview.4.21222.10\6.0.100' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath) in System.IO.FileSystem.dll:token 0x60001ac+0x15
   at System.IO.File.Delete(String path) in System.IO.FileSystem.dll:token 0x60000f3+0xe
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkManagedInstaller.DeletePackInstallationRecord(PackInfo packInfo, SdkFeatureBand featureBand) in dotnet.dll:token 0x60001c7+0x11
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkManagedInstaller.RollBackWorkloadPackInstall(PackInfo packInfo, SdkFeatureBand sdkFeatureBand) in dotnet.dll:token 0x60001bd+0x0
```

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/sdk/issues/17206

### CODE REVIEW

**Review by wli3 — APPROVED** [review]

**Comment by wli3** [comment]
@sfoslund it is good to log. But I think we will still need to clean it up. It is likely anti virus see the new files and want to scan. The right thing should be retry with move to temp directory (now I think we will still need temp directory in the dotnet/ folder, the alternative is left locked file in place). Use move instead of delete since it will either be successful or fail as a whole. And then delete it in the temp directory.

**Comment by wli3** [comment]
File https://github.com/dotnet/sdk/issues/17237 we can do that later

File: src/Cli/dotnet/commands/dotnet-workload/install/NetSdkManagedInstaller.cs [hunk 1]
```diff
@@ -114,7 +117,16 @@ public void InstallWorkloadPack(PackInfo packInfo, SdkFeatureBand sdkFeatureBand
...
-                        RollBackWorkloadPackInstall(packInfo, sdkFeatureBand);
+                        try
+                        {
+                            _reporter.WriteLine(string.Format(LocalizableStrings.RollingBackPackInstall, packInfo.Id));
+                            RollBackWorkloadPackInstall(packInfo, sdkFeatureBand);
+                        }
+                        catch (Exception e)
+                        {
+                            // Don't hide the original error if roll back fails
+                            _reporter.WriteLine(string.Format(LocalizableStrings.RollBackFailedMessage, e.Message));
```
Comment (dsplaisted) [inline src/Cli/dotnet/commands/dotnet-workload/install/NetSdkManagedInstaller.cs:128]: Writing the `Message` property of an exception is often not very helpful.  I'm not sure there's a better option here though.  `ToString()` is generally better for diagnostic logs, but it includes the stack trace so that may be too verbose for here.

File: src/Cli/dotnet/commands/dotnet-workload/install/NetSdkManagedInstaller.cs [hunk 2]
```diff
@@ -230,6 +242,8 @@ private void DeletePack(PackInfo packInfo)
         {
             if (PackIsInstalled(packInfo))
             {
+                GC.Collect();
+                GC.WaitForPendingFinalizers();
```
Comment (dsplaisted) [inline src/Cli/dotnet/commands/dotnet-workload/install/NetSdkManagedInstaller.cs:246]: What's this for?  Do we have any reason to think this will make something more reliable?

**Review by dsplaisted — APPROVED** [review]
I think the GC.Collect calls should probably be deleted.

File: src/Cli/dotnet/commands/dotnet-workload/install/NetSdkManagedInstaller.cs (hunk 2 above)
Comment (sfoslund) [reply src/Cli/dotnet/commands/dotnet-workload/install/NetSdkManagedInstaller.cs:246]: Yes, this change is what actually fixes #17206, I've confirmed that it prevents us from trying to delete a locked file.

**Comment by sfoslund** [comment]
@marcpopMSFT do you have any opinion if this should go in preview 4? It's not a requirement since it's a rollback fix.

**Comment by marcpopMSFT** [comment]
I think we can live with this for p4.  We have a few exception paths when workload install goes off of the mainline path already so I think we should expect to ship some of those.

**Comment by sfoslund** [comment]
> I think we can live with this for p4

So you think it should be ported to prev 4 then?

**Comment by marcpopMSFT** [comment]
Sorry, I meant we can live with the exception shipping in preview 4 so don't port the fix.
