### PR TITLE
Remove custom logic of fetching dotnet dir

### LINKED ISSUE #26837: questionable file name assumptions baked into SDK
### Describe the bug
There are assumptions baked into  Get:DotnetExeDirectory, especially for linux arm64 hosts.

SDK function GetDotnetExeDirectory
contains the line:
            dotnetRootPath = Path.GetFileName(dotnetRootPath).Contains("dotnet") || Path.GetFileName(dotnetRootPath).Contains("x64") || Path.GetFileName(dotnetRootPath).Equals("d") ? dotnetRootPath : Path.Combine(dotnetRootPath, "dotnet");

There are lots of things wrong here:

* The line is too long (too many characters; source code style)
* There's an assumption that the directory holding the executable (we're given the name of the executable) contains "dotnet".  For the latest SDK+runtime, directory names seem to be of the form "net7.0-linux" or "net7.0-Linux-Release-arm64". So why are you looking for "dotnet" rather than just "net"?
* There's an assumption that x64 host is handled differently than arm64.  Why aren't these handled identically, at least for the *nix hosts? I'm  told this is a windows architecture issue)
* You're fishing for substrings in the directory holding the executable.  Perhaps fish for all substrings that are plausibly part of a RID.
* Why the special case assumption for "d" ?  If this is a test harness issue, fix it over there, not in this general code.
* You aren't testing to ensure that the directory name you return is indeed a directory
* You aren't testing to ensure that every intermediate directory on the proposed path is a directory. So you'll return a path like "..../dotnet/sdk" where "..../dotnet" exists and is an executable file, but is *not* a directory like you assume in what is returned.
* Catch the thrown error and make an error message that is a little more appropriate, and perhaps rethrow the error.
* You implement a naming protocol.  Is this protocol documented in "official" docs on the SDK?  If so, please add to the comment a citation of the official filenaming docs for the SDK.

### Further technical details
- I build dotnet runtime in a variety of ways using a variety of gcc versions and a variety of gcc flags.  I compare results on x64 host vs arm64 hosts.

### PR DESCRIPTION
**Pull request by JanKrivanek**
Fixes https://github.com/dotnet/sdk/issues/26837

Proposal of removing custom hardcoded logic of fetching dotnet dir location.
- `EnvironmentProvider.GetDotnetExeDirectory()` now first checks the current process (thus handling the case of xcopy dotnet install) and environemnt after that.
- `CommonOptions.GetCurrentRuntimeId()` now do not have it's custom logic of locating the dotnet folder. It calls the `EnvironmentProvider.GetDotnetExeDirectory()`, but it doesn't intentionally recognize custom MSBuild resolver (defined via `DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR` env var) - so that it's in line with previous logic
- Utils are adjusted to allow injection of env under tests and tests are adjusted to inject mocked env.

Since this is not code I own/maintain, I'd appreciate any insight if there are opposing ideas. Specifically:
- [ ] Is there any issue with switching order of checks in `EnvironmentProvider.GetDotnetExeDirectory()`?
tagging @sfoslund  here as the original author
- [ ] Is the `CommonOptions.GetCurrentRuntimeId()` fine ignoring the custom MSBuild resolver (as it was before)?
tagging @marcpopMSFT as the supposed owner of the code.

### CODE REVIEW

File: src/Cli/dotnet/CommonOptions.cs [hunk 1]
```diff
@@ -233,15 +233,11 @@ internal static string ResolveRidShorthandOptionsToRuntimeIdentifier(string os,
...
-            // However - it first looks on PATH - which can be problematic in environment (e.g. dev) where we have installed and xcopy dotnet versions
-
-            var dotnetRootPath = Path.GetDirectoryName(Environment.ProcessPath);
-            // When running under test the path does not always contain "dotnet".
-			// The sdk folder is /d/ when run on helix because of space issues
-            dotnetRootPath = Path.GetFileName(dotnetRootPath).Contains("dotnet") || Path.GetFileName(dotnetRootPath).Contains("x64") || Path.GetFileName(dotnetRootPath).Equals("d") ? dotnetRootPath : Path.Combine(dotnetRootPath, "dotnet");
-            return dotnetRootPath;
+            // Get the dotnet directory, while ignoring custom msbuild resolvers
+            return Microsoft.DotNet.NativeWrapper.EnvironmentProvider.GetDotnetExeDirectory(key =>
+                    key.Equals("DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR", StringComparison.InvariantCultureIgnoreCase)
```
Comment (marcpopMSFT) [inline src/Cli/dotnet/CommonOptions.cs:238]: I'm not 100% clear on why you want to ignore this environment variable here? Is it basically not supposed to be used when getting dotnet for the common options but should still be used in the EnvironmentProvider (hence the override)?

Comment (JanKrivanek) [reply src/Cli/dotnet/CommonOptions.cs:238]: Great question @marcpopMSFT! I had the exactly same one and I addressed it to you: https://github.com/dotnet/sdk/issues/26837#issuecomment-1197834809

Can you please help identify proper owner in CLI and help find the answer?
