### PR TITLE
Fixing multiple custom properties bug

### LINKED ISSUE #14660: Unrecognized /p: argument with nightly sdk
Using the nightly sdk, I can't pass a custom property with `dotnet publish`:

```
dotnet publish Benchmarks.csproj -c Release -o /tmp/benchmarks-agent/benchmarks-server-1/uu1yclhk.4ia/benchmarks/src/Benchmarks/published /p:MicrosoftNETCoreAppPackageVersion=5.0.0-rtm.20509.6 /p:MicrosoftAspNetCoreAppPackageVersion=5.0.0-rtm.20512.8 /p:BenchmarksNETStandardImplicitPackageVersion=5.0.0-rtm.20512.8 /p:BenchmarksNETCoreAppImplicitPackageVersion=5.0.0-rtm.20512.8 /p:BenchmarksRuntimeFrameworkVersion=5.0.0-rtm.20509.6 /p:BenchmarksTargetFramework=net5.0 /p:BenchmarksAspNetCoreVersion=5.0.0-rtm.20512.8 /p:MicrosoftAspNetCoreAllPackageVersion=5.0.0-rtm.20512.8 /p:NETCoreAppMaximumVersion=99.9 /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-rtm.20509.6 /p:GenerateErrorForMissingTargetingPacks=false /p:MicrosoftNETPlatformLibrary=Microsoft.NETCore.App /p:RestoreNoCache=true --framework net5.0 --self-contained -r linux-x64 
Microsoft (R) Build Engine version 16.9.0-preview-20561-01+56ab63409 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1008: Only one project can be specified.
Switch: MicrosoftAspNetCoreAppPackageVersion=5.0.0-rtm.20512.8

For switch syntax, type "MSBuild -help"
Exit code: 1
```

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes https://github.com/dotnet/sdk/issues/14660

### CODE REVIEW

File: src/Cli/dotnet/OptionForwardingExtensions.cs [hunk 1]
```diff
@@ -17,8 +17,8 @@ public static class OptionForwardingExtensions
 
         public static Option ForwardAsSingle<T>(this Option<T> option, Func<T, string> format) => new ForwardedOption<T>(option).SetForwardingFunction(format);
 
-        public static Option ForwardAsProperty(this Option<string> option) => new ForwardedOption<string>(option)
-            .SetForwardingFunction((o) => new string[] { $"{option.Aliases.FirstOrDefault()}:{o.Replace("roperty:", string.Empty)}" });
+        public static Option ForwardAsProperty(this Option<string[]> option) => new ForwardedOption<string[]>(option)
+            .SetForwardingFunction((optionVals) => optionVals.SelectMany(optionVal => new string[] { $"{option.Aliases.FirstOrDefault()}:{optionVal.Replace("roperty:", string.Empty)}" }));
```
Comment (dsplaisted) [inline src/Cli/dotnet/OptionForwardingExtensions.cs:21]: What would happen if you passed something like `/p:WeirdProperty=property:value`?  Wouldn't this parsing mess up the value?

**Review by dsplaisted — APPROVED** [review]

File: src/Cli/dotnet/OptionForwardingExtensions.cs (hunk 1 above)
Comment (sfoslund) [reply src/Cli/dotnet/OptionForwardingExtensions.cs:21]: Yes, it would. The string replace is a work around for a system command line behavior (bug?) where the first option alias is matched even if a better match exists. So with the property option, we have the aliases `-p` and `-property` but since `-p` is the prefix in both cases it's always the alias that's matched. For example, with the input `-property:prop=true` the token result is option: `-p` and option value: `roperty:prop=true`

cc @jonsequitur

Comment (sfoslund) [reply src/Cli/dotnet/OptionForwardingExtensions.cs:21]: Will track this issue with https://github.com/dotnet/sdk/issues/14461, but in the meantime I don't think it effects this change.

Comment (jonsequitur) [reply src/Cli/dotnet/OptionForwardingExtensions.cs:21]: The System.CommandLine behavior is by design. 

> An option and its argument may or may not appear as separate tokens. (In other words, the whitespace separating them is optional.) Thus, ‘-o foo’ and ‘-ofoo’ are equivalent.

https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html

Comment (dsplaisted) [reply src/Cli/dotnet/OptionForwardingExtensions.cs:21]: I think MSBuild doesn't follow the GNU spec.  It doesn't require two dashes before the long form of an argument (`-property`), and it does require a separator (colon) between the option and the argument.  Does System.CommandLine intend to support that behavior to some degree so we can maintain compatibility with arguments that are passed through to MSBuild?
