### PR TITLE
Fix CA1034 diagnostic when extension members are present

### LINKED ISSUE #51681: CA1034 is incorrectly reported for extension members
### Describe the bug
Adding extension members to any class causes CA1034 (Nested types should not be visible) to be incorrectly reported.

### To Reproduce
https://github.com/ezhevita/CA1034Repro

### Exceptions (if any)
```
Program.cs(9,2): Warning CA1034 : Do not nest type . Alternatively, change its accessibility so that it is not externally visible. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1034)
```

### Further technical details
<details><summary>details of dotnet --info</summary>
<p>
.NET SDK:
 Version:           10.0.100-rc.2.25502.107
 Commit:            89c8f6a112
 Workload version:  10.0.100-manifests.0cee6f9c
 MSBuild version:   18.0.0-preview-25502-107+89c8f6a11

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  15.7
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /nix/store/cal0gw8y2hk29gzj348fi3lqpf4qmgyp-dotnet-sdk-10.0.100-rc.2.25502.107/share/dotnet/sdk/10.0.100-rc.2.25502.107/

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.0-rc.2.25502.107
  Architecture: arm64
  Commit:       89c8f6a112

.NET SDKs installed:
  8.0.415 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/sdk]
  9.0.306 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/sdk]
  10.0.100-rc.2.25502.107 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.21 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.10 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 10.0.0-rc.2.25502.107 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.21 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.10 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.0-rc.2.25502.107 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</p>
</details>
The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: irrelevant since it reproduces in CLI.

### Analysis

This issue is caused due to extension members looking like a type for the analyzer while not being actually one. The fix would be to just filter these out by checking `TypeKind` against `Extension` somewhere around here:
https://github.com/dotnet/sdk/blob/1b7a79f9ed0432fd17b48a64a002f1d8f947445c/src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs#L73-L77

### PR DESCRIPTION
**Pull request by ezhevita**
Fixes https://github.com/dotnet/sdk/issues/51681.

### CODE REVIEW

**Comment by BenjaminBrienen-CanonPP** [comment]
This is a blocker for anyone wanting to use extension members and who has this warning enabled and rejects warnings in CI. I would like to see this merged and released.

File: src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs [hunk 1]
```diff
@@ -148,4 +154,4 @@ private static bool IsDataSetSpecialCase(
                 dataRowType != null && nestedTypeBases.Contains(dataRowType);
         }
     }
-}
```
Comment (BenjaminBrienen-CanonPP) [inline src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs:152]: trailing newline should not be removed

File: src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs [hunk 2]
```diff
@@ -76,6 +76,12 @@ public override void Initialize(AnalysisContext context)
                                 return;
                             }
 
+                            // Do not report diagnostic for extension members
```
Comment (BenjaminBrienen-CanonPP) [inline src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs:80]: This says "what" but not "why".

**Review by BenjaminBrienen-CanonPP — APPROVED** [review]

File: src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs (hunk 2 above)
Comment (quellatalo) [reply src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs:80]: Isn't it the same for line 73?
I feel it's obvious enough that more explanation would just create more confusion.

Comment (BenjaminBrienen-CanonPP) [reply src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs:80]: I couldn't see the comment on line 73 in the diff viewer. Thanks for the clarification. I think the comment here could be slightly improved by saying "compiler-generated code from extension blocks".

**Comment by smaillet** [comment]
Why is this still pending? Is someone waiting on a response? (If so who and what?) This is a major PITA and blocker for adopting the new "extension" keyword for a lot of teams.

**Comment by BenjaminBrienen-CanonPP** [comment]
Is dotnet sdk still maintained?

**Comment by ezhevita** [comment]
> Is someone waiting on a response?

Waiting for a code review by the maintainers. I'd assume this is not prioritized since there is a workaround (just suppress the diagnostic), but I am also frustrated there has been no progress on this for almost three months.

File: src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs [hunk 3]
```diff
@@ -76,6 +76,12 @@ public override void Initialize(AnalysisContext context)
...
+                            if (nestedType.TypeKind == ITypeSymbolExtensions.ExtensionTypeKind)
+                            {
+                                return;
+                            }
```
Comment (stephentoub) [inline src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs:84]: Thanks for the fix. Can you add a test?

Comment (ezhevita) [reply src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/NestedTypesShouldNotBeVisible.cs:84]: Done.

**Review by stephentoub — APPROVED** [review]
Thanks.

**Comment by julealgon** [comment]
Appreciate you resurrecting this one for us @stephentoub 😉

**Comment by irontoby** [comment]
Great! Now if we can just get #51838 merged we can actually use extension blocks 🙃

**Comment by Kumima** [comment]
Can this be backported?
