### PR TITLE
Remove -r parameter for dotnet test, and change -a parameter to be shorthand for --arch, instead of --test-adapter-path

### LINKED ISSUE #21389: [Breaking change] For `dotnet test`, switch `-a` to alias `--arch` instead of `--test-adapter-path`
Check it out ...

```bash
rich@MacBook-Air-M1-2020 tests % dotnet test --help | grep -- -a
  -a, --test-adapter-path <ADAPTER_PATH>  The path to the custom adapters to 
  --blame-crash-collect-always            Enables collecting crash dump on 
  <blame-crash-collect-always>            expected as well as unexpected 
  --arch <arch>                           The target architecture.
rich@MacBook-Air-M1-2020 tests % dotnet run --help | grep -- -a
  -a, --arch <arch>                    The target architecture.
```

Sure would be nice to make `-a` the same everywhere. I doubt that the current usage of `-a` is common.

This is similar to https://github.com/dotnet/sdk/issues/21952.

- https://grep.app/search?q=dotnet%20test%20-a
- https://grep.app/search?q=dotnet%20test%20--test-adapter-path

### LINKED ISSUE #21952: [Breaking change] For `dotnet test`, switch `-r` to alias `--runtime` instead of `--results-dir`
Check it out:

```bash
rich@mazama:~$ dotnet test --help | grep -- -r
                                            See https://aka.ms/vstest-report
                                          testing. Implies --no-restore.
  -r, --results-directory <RESULTS_DIR>   The directory where the test results
  --runtime <RUNTIME_IDENTIFIER>          The target runtime to test for.
  --no-restore                            Do not restore the project before
```

`-r` should be used for `--runtime` for all verbs. 

This is similar to https://github.com/dotnet/sdk/issues/21389.

https://grep.app/search?q=dotnet%20test%20-r
https://grep.app/search?q=dotnet%20test%20--results-directory

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Closes dotnet/sdk#21952
Closes dotnet/sdk#21389

cc: @nohwnd

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs [hunk 1]
```diff
@@ -150,11 +151,11 @@ private static Command ConstructCommand()
             command.AddOption(NoLogoOption);
             command.AddOption(ConfigurationOption);
             command.AddOption(FrameworkOption);
-            command.AddOption(CommonOptions.LongFormRuntimeOption.WithHelpDescription(command, LocalizableStrings.RuntimeOptionDescription));
+            command.AddOption(CommonOptions.RuntimeOption.WithHelpDescription(command, LocalizableStrings.RuntimeOptionDescription));
             command.AddOption(NoRestoreOption);
             command.AddOption(CommonOptions.InteractiveMsBuildForwardOption);
             command.AddOption(CommonOptions.VerbosityOption);
-            command.AddOption(CommonOptions.LongFormArchitectureOption);
```
Comment (nohwnd) [inline src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs:157]: Why is this change neede?

Comment (MarcoRossignoli) [reply src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs:157]: Because we'll support --arch/--a for architecture and no more --a for test adapter or have I misunderstood?

https://github.com/dotnet/sdk/blob/a5dae2aaee040aea5dedc2c16963360a87585e31/src/Cli/dotnet/CommonOptions.cs#L122
