### PR TITLE
make error for workload info clean Fixes #42581

### LINKED ISSUE #42581: [NETSDKE2E][Workload Sets] With manifest mode and workload installed, Unhandled exception occurs when running `dotnet workload --info` using global.json
### Describe the bug
With manifest mode and workload installed, Unhandled exception occurs when running '`dotnet workload --info` using global.json

### To Reproduce
1. Install .NET 8.0.400 SDK
2. Install workload eg. aspire 
`    dotnet workload install aspire`
image

3.  New a global.json and add workloadverion to this file under a new folder
```
    c:\tt\TestWithGloabalJson
    cd c:\tt\TestWithGloabalJson
    dotnet new global.json
```
```
    {
      "sdk": {
        "version": "8.0.400",
        "workloadVersion": "8.0.400"
      }
    }
```
4. Run `dotnet workload --info` and observe

### Expected Result
Proper suggestion without any exception. eg. '`dotnet workload list`'
image

### Actual Result
Unhandled exception:
image

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #42581

dotnet workload list has a special check to ensure that if a global.json file exists that specifies a particular workload set, then that workload set is installed. If not, it informs the user that they should do that first.

dotnet workload --info did not. The result was that it would give an ugly error with a stack trace.

This gives it the clean error message.

The bug didn't mention this, but I believe dotnet --info is also broken in the same case. This resolves that as well.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs [hunk 1]
```diff
@@ -51,9 +45,16 @@ internal static string GetWorkloadsVersion(WorkloadInfoHelper workloadInfoHelper
         internal static void ShowWorkloadsInfo(ParseResult parseResult = null, WorkloadInfoHelper workloadInfoHelper = null, IReporter reporter = null, string dotnetDir = null, bool showVersion = true)
         {
             workloadInfoHelper ??= new WorkloadInfoHelper(parseResult != null ? parseResult.HasOption(SharedOptions.InteractiveOption) : false);
+            reporter ??= Utils.Reporter.Output;
+            var globalJsonInformation = workloadInfoHelper.ManifestProvider.GetGlobalJsonInformation();
+            if (globalJsonInformation?.WorkloadVersionInstalled == false)
```
Comment (joeloff) [inline src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs:50]: probably don't need the `== false`,

Comment (Forgind) [reply src/Cli/dotnet/commands/dotnet-workload/WorkloadCommandParser.cs:50]: globalJsonInformation could be null, and if not, WorkloadVersionInstalled could be true or false, so this is really a bool?, hence the == false.

**Review by marcpopMSFT — APPROVED** [review]
