### PR TITLE
Adjust conditional params tests

### LINKED ISSUE #5647: Conditional parameters are not processed correctly in certain cases
Test cases that are failing at the moment:
https://github.com/dotnet/sdk/blob/64aaea464653b3834b016cd08e4a0a41bc797eff/src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.Approval.cs#L738
https://github.com/dotnet/sdk/blob/64aaea464653b3834b016cd08e4a0a41bc797eff/src/Tests/dotnet-new.Tests/DotnetNewInstantiateTests.Approval.cs#L689

Even if the failure is expected, the error message is not appropriate (cannot add item to a dictionary).

Related or unrelated to this, the following syntax doesn't work
```json
  "symbols": {
    "A": {
      "type": "parameter",
      "datatype": "bool",
      "isEnabled": "B",
      "defaultValue": false
    },
    "B": {
      "type": "parameter",
      "datatype": "bool",
    }
}

```

`> dotnet new template ` and  `> dotnet new template  --B` and fails in this case, as the template engine fails to evaluate `B` as the valid condition.
The issue is not reproduced when:
- using `> dotnet new template  --B true|false`
- using `defaultValue` for parameter `B`.

Additionally: 
https://github.com/dotnet/sdk/blob/69fd7b4a0e43d290ea8c3bcca6d14b53df50ebd6/src/Cli/Microsoft.TemplateEngine.Cli/TemplateInvoker.cs#L210-L211
there were 2 cases that were not handled before - verify if needs the separate processing.

### PR DESCRIPTION
**Pull request by JanKrivanek**
### Problem

Fixes https://github.com/dotnet/templating/issues/5647
Some tests were failing due to issues with conditional params evaluation

### Solution

Conditional params tests now test various combinations of setting/enabling conditional params

### CODE REVIEW

File: src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithConditionalParameters/Test.cs [hunk 1]
```diff
@@ -2,10 +2,10 @@
 // value of paramA: placeholderA
 // value of paramB: placeholderB
 
-//#if( A_enabled )
+//#if( paramA )
```
Comment (vlada-shubina) [inline src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithConditionalParameters/Test.cs:5]: I think it was correct before - it should show up the values of `A_enabled` and `B_enabled`
`paramA` and `paramB` are string parameters and cannot be used this way.

File: src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithConditionalParameters/Test.cs [hunk 2]
```diff
@@ -2,10 +2,10 @@
...
 // A is enabled
 //#endif
```
Comment (vlada-shubina) [inline src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithConditionalParameters/Test.cs:7]: nit

```suggestion
//#if( paramA )
// A is enabled
//#elseif
// A is disabled
//#endif
```

just for clarity

File: src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithConditionalParameters/Test.cs (hunk 1 above)
Comment (vlada-shubina) [reply src/Assets/TestPackages/dotnet-new/test_templates/TemplateWithConditionalParameters/Test.cs:5]: It is reasonable, but on the other hand, it complicates understanding the test:
- maybe it is worth to keep both to check the value of `A_enabled` and `B_enabled` too.
- If you'd like to use `paramA` and `paramB` in condition as the boolean, I suggest tochange `datatype` to boolean.  It is risky: string parameters should not be used in condition as `if (paramA)`, because there is no validation, and user can enter any other string and then condition won't be correct. Or consider putting the comment that it is intentionally incorrect to test it. May also help people who look on tests as the reference.

**Review by vlada-shubina — APPROVED** [review]
Thanks!
