### PR TITLE
dotnet nuget commands show correct help text

### LINKED ISSUE #27833: No help for specific `dotnet nuget` commands
Repro steps:

```
dotnet nuget update --help
```

Expected result: Help text specific to the nuget command

Actual result: Top level \hHelp text for `dotnet nuget`:

```
C:\test> dotnet nuget list -h
NuGet Command Line 6.4.0.53

Usage: dotnet nuget [options] [command]

Options:
  -h|--help  Show help information
  --version  Show version information

Commands:
  add      Add a NuGet source.
  delete   Deletes a package from the server.
  disable  Disable a NuGet source.
  enable   Enable a NuGet source.
  list     List configured NuGet sources.
  locals   Clears or lists local NuGet resources such as http requests cache, packages folder, plugin operations cache  or machine-wide global packages folder.
  push     Pushes a package to the server and publishes it.
  remove   Remove a NuGet source.
  sign     Signs NuGet package(s) at <package-paths> with the specified certificate.
  trust    Manage the trusted signers.
  update   Update a NuGet source.
  verify   Verifies a signed NuGet package.

Use "dotnet nuget [command] --help" for more information about a command.
```

```
C:\test> dotnet --info
.NET SDK:
 Version:   7.0.100-rc.1.22431.12
 Commit:    f1cf61e1c0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: x64
  Commit:       06aceb7015

.NET SDKs installed:
  6.0.303 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22427.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### PR DESCRIPTION
**Pull request by JiaqiWang18**
Fixes #27833 
Pass in the entire `ParseResult` to `NuGetCommand` to forward the entire token stream so the help text displayed as a result of running `dotnet nuget [command] -h` is the correct help text for that specific command.

### Example
Running a specific NuGet command
```
PS C:\Users\Jacky\Documents\workspace\test-proj> dotnet nuget add -h


Usage: dotnet nuget add [options] [command]

Options:
  -h|--help  Show help information

Commands:
  client-cert  Adds a client certificate configuration that matches the given package source name.
  source       Add a NuGet source.

Use "add [command] --help" for more information about a command.
```
Running the NuGet top level command shows the top level help text
```
PS C:\Users\Jacky\Documents\workspace\test-proj> dotnet nuget -h
NuGet Command Line 6.5.0.104

Usage: dotnet nuget [options] [command]

Options:
  -h|--help  Show help information
  --version  Show version information

Commands:
  add      Add a NuGet source.
  delete   Deletes a package from the server.
  disable  Disable a NuGet source.
  enable   Enable a NuGet source.
  list     List configured NuGet sources.
  locals   Clears or lists local NuGet resources such as http requests cache, packages folder, plugin operations cache  or machine-wide global packages folder.
  push     Pushes a package to the server and publishes it.
  remove   Remove a NuGet source.
  sign     Signs NuGet package(s) at <package-paths> with the specified certificate.
  trust    Manage the trusted signers.
  update   Update a NuGet source.
  verify   Verifies a signed NuGet package.

Use "dotnet nuget [command] --help" for more information about a command.
```

### CODE REVIEW

**Comment by baronfel** [comment]
The only thing I would test/change here is that the .NET CLI `help` option is 'broader' than the NuGet one - it supports `-?`, `-h`, and `--help` where the NuGet help option only supports `--help` and `-h` (from my quick check of the nuget CLI's raw help output.

Can you test the behavior of `-?` with this change and if necessary adapt that in your code?

**Comment by JiaqiWang18** [comment]
@baronfel thoughts on the above?

**Comment by baronfel** [comment]
Sorry, I missed the question at the end of your comment. I would prefer -? to be rewritten to --help, just to prevent user confusion. I would time box this to no more than a few hours of work. If it takes too much effort we can put that aside, because the user benefit of the rest of your change is so high.

File: src/Cli/dotnet/commands/dotnet-nuget/Program.cs [hunk 1]
```diff
@@ -29,7 +29,12 @@ public static int Run(string[] args, ICommandRunner nugetCommandRunner)
             {
                 throw new ArgumentNullException(nameof(nugetCommandRunner));
             }
-
+            // replace -? with --help for NuGet CLI
```
Comment (JiaqiWang18) [inline src/Cli/dotnet/commands/dotnet-nuget/Program.cs:32]: Added this code to replace all "-?" with "--help"

**Comment by JiaqiWang18** [comment]
https://github.com/dotnet/sdk/blob/dd9bdd2ee2450fb8983d4c754485d8e74ba83923/src/Cli/dotnet/commands/dotnet-nuget/Program.cs#L32-L37
@baronfel Added this to replace all `-?` with `--help`

**Review by baronfel — APPROVED** [review]
Wonderful, thank you for this!

**Comment by marcpopMSFT** [comment]
Thank you for your contribution
