### PR TITLE
Ensure references added using "Reference" are correctly copied in BlazorWASM projects

### LINKED ISSUE #37574: WebAssembly in .Net 6 RC2: The top level app must directly references to the assemblies used by it's referenced assemblies
### Describe the bug
In WebAssembly in .Net 6 RC2 (I did not test earlier version), if the Blazor app1 references to module M1, and M1 references to another module M2. Then app1 must directly reference to M2, or I get exception in runtime.
This is working fine in .net 5.

### To Reproduce
Run the sample application from https://github.com/jjzhang12/Net6Issue.git
This is a template Blazor wasm app, and one line is added to instantiate the MyClass, and MyClass requires MyAbstractClass.
An exception is logged in runtime.

### Exceptions (if any)
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted) at Microsoft.AspNetCore.Components.Routing.Router.SetParametersAsync(ParameterView parameters) window.Module.s.printErr @ blazor.webassembly.js:1 blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Could not load type of field 'BlazorApp1.Pages.Counter:class1' (1) due to: Could not resolve type with token 0100000c from typeref (expected class 'MyAbstractClass.Disposable' in assembly 'MyAbstractClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:MyAbstractClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:MyAbstractClass.Disposable member:(null) System.TypeLoadException: Could not load type of field 'BlazorApp1.Pages.Counter:class1' (1) due to: Could not resolve type with token 0100000c from typeref (expected class 'MyAbstractClass.Disposable' in assembly 'MyAbstractClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:MyAbstractClass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:MyAbstractClass.Disposable member:(null) at System.RuntimeTypeHandle.CanCastTo(RuntimeType type, RuntimeType target) at System.RuntimeType.IsAssignableFrom(Type c) at Microsoft.AspNetCore.Components.RouteTableFactory.g__GetRouteableComponents|4_0(List`1 routeableComponents, Assembly assembly) at Microsoft.AspNetCore.Components.RouteTableFactory.GetRouteableComponents(RouteKey routeKey) at Microsoft.AspNetCore.Components.RouteTableFactory.Create(RouteKey routeKey) at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable() at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted) at Microsoft.AspNetCore.Components.Routing.Router.RunOnNavigateAsync(String path, Boolean isNavigationIntercepted) at Microsoft.AspNetCore.Components.Routing.Router.<>c__DisplayClass62_0.b__1(RenderTreeBuilder builder) at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

### Further technical details
- ASP.NET Core version: 6.0 RC2
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: 2022 Peview
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

</details>

### PR DESCRIPTION
**Pull request by pranavkm**
As part of .NET6, we rely on OriginalItemSpec to copy items around. Unfortunately there is an issue with ResolveAssemblyReferences, where references added using `Reference` have an incorrect ItemSpec (intentionally so). This change worksaround this case by special casing references from projects where the OriginalItemSpec differs from it's full path.

Fixes https://github.com/dotnet/aspnetcore/issues/37574

### CODE REVIEW

File: src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs [hunk 1]
```diff
@@ -129,6 +128,14 @@ public override bool Execute()
                         candidate.SetMetadata("RelativePath", $"_framework/{destinationSubPath}");
                     }
 
+                    // Workaround for https://github.com/dotnet/aspnetcore/issues/37574.
+                    // For items added as "Reference" in project references, the OriginalItemSpec is incorrect.
+                    // Ignore it, and use the FullPath instead.
+                    if (candidate.GetMetadata("ReferenceSourceTarget") == "ProjectReference")
```
Comment (javiercn) [inline src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs:134]: `ProjectReference` is this the value that `Reference` items set it to? What happens with dlls that come from `ProjectReference` do they also have this property set up with the same value?

**Review by javiercn — APPROVED** [review]
Looks great!

File: src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs (hunk 1 above)
Comment (pranavkm) [reply src/BlazorWasmSdk/Tasks/ComputeBlazorBuildAssets.cs:134]: Both the referenced dll and the app dll have this value. The way MSBuild constructs the Item for the reference is by taking the project's output and updating it's ItemSpec, so it doesn't have any defining properties to differentiate on.

**Review by TanayParikh — APPROVED** [review]

**Comment by RChrisCoble** [comment]
@javiercn glad to hear this got addressed.  How does a Microsoft Partner like ourselves get this fix to unblock the issue we're having?

@jjzhang12

**Comment by javiercn** [comment]
You can get a nightly build of the 7.0.100 SDK once the fix makes it into the nightly build. 

I believe we have marked this issue as a patch candidate, so I'm hoping this will get in for 6.0.101, however, I can't tell you exactly when that will be.

@pranavkm do you have any other thoughts?

**Comment by pranavkm** [comment]
@RChrisCoble we were looking to address this as part of our upcoming patch release (hopefully 6.0.1, but 6.0.2 at the latest). As @javiercn pointed out, installing a 7.0 SDK should address this issue: https://github.com/dotnet/installer#installers-and-binaries until we have a 6.0 fix.

**Comment by budcribar** [comment]
@javiercn  Thanks for checking into this further. Is there a daily build that I can download when there is a fix or do I wait for next release?

**Comment by TanayParikh** [comment]
> Is there a daily build that I can download when there is a fix or do I wait for next release?

Nightly builds are available here: https://github.com/dotnet/installer#installers-and-binaries
