### PR TITLE
`dotnet package list` command should restore first

### LINKED ISSUE #13406: `dotnet list package` doesn't `restore`
This behavior is incorrect, inconsistent, and inconvenient.

We have had implicit restore for `dotnet build` for many years. `dotnet list package` would benefit from this same behavior.

> You first need to build the project in order to have the assets needed for this command to process.

Per [docs](https://learn.microsoft.com/dotnet/core/tools/dotnet-list-package). That's unfortunate.

Observed behavior follows.

```bash
$ dotnet new console -o nugettest
$ cd nugettest
$ rm -r obj
$ dotnet list package
No assets file was found for `/Users/rich/nuget-test/nuget-test.csproj`. Please run restore before running this command.
$ dotnet restore
  Determining projects to restore...
  Restored /Users/rich/nuget-test/nuget-test.csproj (in 52 ms)
$ dotnet list package
Project 'nugettest' has the following package references
   [net8.0]: No packages were found for this framework.
$ dotnet add package System.Text.Json --version 8.0.3
$ dotnet list package                                
Project 'nuget-test' has the following package references
   [net8.0]: 
   Top-level Package       Requested   Resolved
   > System.Text.Json      8.0.3       8.0.3   
$ echo manually add package
manually add package
$ grep PackageRef nuget-test.csproj  

    <PackageReference Include="System.Text.Json" Version="8.0.3" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.0" />
dotnet list package              
Project 'nuget-test' has the following package references
   [net8.0]: 
   Top-level Package       Requested   Resolved
   > System.Text.Json      8.0.3       8.0.3
$ dotnet list package --vulnerable --include-transitive

The following sources were used:
   https://api.nuget.org/v3/index.json

The given project `nuget-test` has no vulnerable packages given the current sources.
```

### PR DESCRIPTION
**Pull request by Nigusu-Allehu**
https://github.com/dotnet/sdk/pull/47400 had to many conflicts. 
Fixes: https://github.com/NuGet/Home/issues/13406

## Description

This PR
* Adds implicit restore to `dotnet package list` command or `dotnet list package` (https://github.com/dotnet/sdk/pull/45384)

### ScreenShots
* `package list --project [project]`
image
* --format json
image
* restore error
image

* restore error: --format json
image

### CODE REVIEW

File: src/Cli/dotnet/commands/Package/list/ListPackageReferencesCommand.cs [hunk 1]
```diff
@@ -30,7 +32,59 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+            {
+                string jsonError =
+    "{\r\n" +
+    "   \"version\": 1,\r\n" +
+    "   \"problems\": [\r\n" +
+    "      {\r\n" +
+    $"         \"text\": \"{String.Format(CultureInfo.CurrentCulture, LocalizableStrings.Error_restore)}\",\r\n" +
+    "         \"level\": \"error\"\r\n" +
+    "      }\r\n" +
+    "   ]\r\n" +
```
Comment (zivkan) [inline src/Cli/dotnet/commands/Package/list/ListPackageReferencesCommand.cs:77]: Line endings are different on Windows and Linux (and in the past Mac too, but I can't remember if Mac is the same as Linux now, or still different to both).  Plus on Windows I'm not sure if `Console.WriteLine` (well, technically `StringWriter`) detects `\n` and converts it to `\r\n`, so maybe there's risk that explicitly putting in `\r\n` will cause the output to contain `\r\r\n`.

Anyway, I'd suggest using [raw string literals](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/raw-string) and assume that the compiler is going to do the right thing

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 2]
```diff
@@ -30,7 +32,60 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+        }
+
+        return restoreExitCode == 0
+            ? NuGetCommand.Run(TransformArgs(projectFile))
+            : restoreExitCode;
+    }
+
+    private int RunRestore(string projectOrSolution, ReportOutputFormat formatOption)
+    {
+        MSBuildForwardingApp restoringCommand = new MSBuildForwardingApp(argsToForward: ["-target:restore", projectOrSolution, "-noConsoleLogger"]);
```
[the remark this answers is not in the document]
Comment (baronfel) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:52]: We should try to align with test and run here and use the same logger configuration - ideally this would use terminal logger by default like every other command in the CLI.

[the remark this answers is not in the document]
Comment (jeffkl) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:52]: I'm not so sure, the output of this command is the information about the packages that a project is referencing. Its not running tests (which are potentially long running) and its not building a project and its dependencies.

The only reason we need to run restore first is because the `project.assets.json` file provides all of the information and we want to make sure its up-to-date. The only reason I propose we have any output at all about restore is in the case that it takes a while, I don't want users to think that `dotnet list package` is hung.

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 3]
```diff
@@ -30,7 +32,72 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+            exitCode = 1;
+        }
+
+        if (exitCode != 0)
+        {
+            if (formatOption == ReportOutputFormat.json)
+            {
+                string jsonError = $$"""
+{
+   "version": 1,
```
Comment (Forgind) [inline src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:87]: What version is this?

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 4]
```diff
@@ -30,7 +32,72 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+   "problems": [
```
Comment (Forgind) [inline src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:88]: "errors"? Or since this doesn't really seem to be an array, can we just make it "error" and have it be the object?

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 5]
```diff
@@ -30,7 +32,72 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+      {
+         "text": "{{String.Format(CultureInfo.CurrentCulture, LocalizableStrings.Error_restore)}}",
+         "level": "error"
+      }
+   ]
+}
+""";
+                Console.WriteLine(jsonError);
```
Comment (Forgind) [inline src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:96]: This feels like it should go elsewhere. Does NuGet normally just write to the console? Seems like there should be some kind of logger, or at least this should go to Console.Error

File: src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx [hunk 6]
```diff
@@ -174,4 +174,11 @@
   <data name="CmdOutputVersionDescription" xml:space="preserve">
     <value>Specifies the version of machine-readable output. Requires the '--format json' option.</value>
   </data>
+  <data name="Error_restore" xml:space="preserve">
+    <value>Restore failed. Run `dotnet restore` for more details on the issue.</value>
+    <comment>Do not translate `dotnet restore`</comment>
```
Comment (Forgind) [inline src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx:179]: nit: use the [locking syntax](https://github.com/dotnet/sdk/blob/main/documentation/project-docs/Localization.md#locking-translations) for pinned translation strings so that the Loc team's tooling helps prevent unintentional translation.

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 7]
```diff
@@ -30,7 +32,72 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+            restoreExitCode = RunRestore(projectFile, formatOption, interactive);
+        }
+
+        return restoreExitCode == 0
+            ? NuGetCommand.Run(TransformArgs(projectFile))
+            : restoreExitCode;
+    }
+
+    private int RunRestore(string projectOrSolution, ReportOutputFormat formatOption, bool interactive)
+    {
```
Comment (Forgind) [inline src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:52]: I was looking this and comparing it with RestoringCommand. I'm not entirely sure why they look so different. This looks correct, as far as I can tell; I just thought it'd would be nice to combine them if possible.

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs (hunk 3 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:87]: It is following the Json schema from https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/ListPackage/ListPackageJsonRenderer.cs#L19

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs (hunk 4 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:88]: This is following this schema: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/ListPackage/ListPackageJsonRenderer.cs#L19. We want to make sure this does not introduce no new changes to the json schema

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs (hunk 5 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:96]: For the dotnet package list command, NuGet writes to Conosle.out

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 8]
```diff
@@ -30,7 +32,73 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+        }
+        else
+        {
+            args.Add("-consoleLoggerParameters:NoSummary");
+            args.Add("-verbosity:minimal");
+        }
+
+        if (interactive)
+        {
+            args.Add("-interactive:true");
```
Comment (zivkan) [inline src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:67]: some customers run `dotnet list package` in CI pipelines, where they are not interactive.  This needs to be toggleable.

Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:67]: I was assuming the fault is false. but upon reading the docs, there is nothing that backs my assumption.

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs (hunk 7 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:52]: I looked into using `RestoringCommand` here as well, but decided against it for a few reasons:

- `RestoringCommand` is primarily looks like it is built for commands like `build`, where restore may need to run either in-process (`-restore`) or as a separate `msbuild -target:Restore` call. In our case, we explicitly want to run only restore, and we already know what MSBuild target to run 

- Even when `--no-restore` is passed, `RestoringCommand` still invokes `MSBuildForwardingApp.Execute()` with the provided arguments. Even if no arguments are passed at all, it could end up building the project unintentionally due to MSBuild's default behavior.

**Review by Forgind — APPROVED** [review]

**Comment by Nigusu-Allehu** [comment]
@dotnet/nuget-team any suggestions? The more time this takes the more conflicts keep coming up

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 9]
```diff
@@ -30,7 +32,78 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+            bool interactive = _parseResult.GetValue((CliOption<bool>)PackageListCommandParser.InteractiveOption);
+            restoreExitCode = RunRestore(projectFile, formatOption, interactive);
+        }
+
+        return restoreExitCode == 0
+            ? NuGetCommand.Run(TransformArgs(projectFile))
+            : restoreExitCode;
+    }
+
+    private int RunRestore(string projectOrSolution, ReportOutputFormat formatOption, bool interactive)
```
Comment (jebriede) [inline src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:51]: Nit: This method does a lot of things to prepare the command to run. Consider adding private helper methods to set up the options and generate the json output and call them from this method.

File: src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx [hunk 10]
```diff
@@ -174,4 +174,11 @@
   <data name="CmdOutputVersionDescription" xml:space="preserve">
     <value>Specifies the version of machine-readable output. Requires the '--format json' option.</value>
   </data>
-</root>
\ No newline at end of file
+  <data name="Error_restore" xml:space="preserve">
+    <value>Restore failed. Run `dotnet restore` for more details on the issue.</value>
```
Comment (jebriede) [inline src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx:178]: Question: Is this wording consistent with other output or was this wording vetted?

**Review by jebriede — APPROVED** [review]

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 11]
```diff
@@ -30,7 +32,78 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+
+        int exitCode = 0;
+
+        try
+        {
+            exitCode = restoringCommand.Execute();
+        }
+        catch (Exception)
+        {
+            exitCode = 1;
```
Comment (aortiz-msft) [inline src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:84]: What are valid exitCodes, and does this have the potential to overwrite a more helpful exitCode with a less helpful one?

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs [hunk 12]
```diff
@@ -30,7 +32,78 @@ private static string GetAbsolutePath(string currentDirectory, string relativePa
...
+        }
+
+        if (interactive)
+        {
+            args.Add("-interactive:true");
+        }
+        else
+        {
+            args.Add("-interactive:false");
+        }
```
Comment (aortiz-msft) [inline src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs:72]: Suggestion: args.add("-interactive:" + Convert.ToString(interactive));

**Review by aortiz-msft — APPROVED** [review]

File: src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx (hunk 10 above)
Comment (Forgind) [reply src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx:178]: On that note, why can't we output the error from dotnet restore without them having to run dotnet restore explicitly?

**Comment by marcpopMSFT** [comment]
@Nigusu-Allehu there are a bunch of conflicts to resolve fyi.

File: src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx (hunk 10 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx]: > Question: Is this wording consistent with other output or was this wording vetted?

This the first adoption of implicit restore for nuget commands. Others like dotnet nuget why will probably follow suit as well.

> On that note, why can't we output the error from dotnet restore without them having to run dotnet restore explicitly?

When the command includes `--format json`, we avoid printing any additional output to ensure the JSON remains valid. To enforce this, I passed `-noConsoleLogger` to MSBuild. Since this operation runs in a separate process, capturing and displaying errors becomes tricky. If we were running the restore in-process, however, we could have easily captured the errors and logged them ourselves.

File: src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs (hunk 11 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs]: 1 - for failure
0 - for success
https://github.com/NuGet/NuGet.Client/blob/ab6b96fd9ba07ed3bf629ee389799ca4fb9a20fb/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/ListPackage/ListPackageCommandRunner.cs#L31

Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/ListPackageReferencesCommand.cs]: These are the exit codes we use for the dotnet package list command

**Review by aortiz-msft — APPROVED** [review]

File: src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx (hunk 10 above)
Comment (Forgind) [reply src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx]: I actually think this is a perfectly valid response, but I'll bang this drum on baronfel's behalf:
Output should go to stdout. Errors (and other incidental output) should go to stderr. That way you can have beautiful, clean output in stdout and still have access to all the information you'd want in stderr.

I'm assuming NuGet doesn't do that historically, so you're sending errors to stdout as well just because that's how it currently works?

Though if you're going to get an error anyway, does the user really still care that the output of --format json is preserved?

**Review by zivkan — APPROVED** [review]

File: src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx (hunk 10 above)
Comment (Nigusu-Allehu) [reply src/Cli/dotnet/Commands/Package/List/LocalizableStrings.resx]: That is good point! Tracking here now https://github.com/NuGet/Home/issues/14239

**Comment by Nigusu-Allehu** [comment]
breaking change doc: https://github.com/dotnet/docs/issues/46103

**Comment by Nigusu-Allehu** [comment]
doc: https://github.com/dotnet/docs/pull/49053
