### PR TITLE
Fix CA1515 diagnostic when extension members are present

### LINKED ISSUE #51683: CA1515 is reported when extension members are present despite being suppressed in .editorconfig
### Describe the bug
CA1515 (Consider making public types internal) is reported when it is silenced in `.editorconfig`, but only if the project has at least a single extension member included.

### To Reproduce
https://github.com/ezhevita/CA1034Repro

This is actually a repro for [another somewhat related issue](https://github.com/dotnet/sdk/issues/51681), but they were mostly the same so I've merged them into one.

### Exceptions (if any)
```
CSC : warning CA1515: Because an application's API isn't typically referenced from outside the assembly, types can be made internal (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1515)
```

### Further technical details
<details><summary>details of dotnet --info</summary>
<p>
.NET SDK: Version: 10.0.100-rc.2.25502.107 Commit: 89c8f6a112 Workload version: 10.0.100-manifests.0cee6f9c MSBuild version: 18.0.0-preview-25502-107+89c8f6a11

Runtime Environment:
OS Name: Mac OS X
OS Version: 15.7
OS Platform: Darwin
RID: osx-arm64
Base Path: /nix/store/cal0gw8y2hk29gzj348fi3lqpf4qmgyp-dotnet-sdk-10.0.100-rc.2.25502.107/share/dotnet/sdk/10.0.100-rc.2.25502.107/

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
Version: 10.0.0-rc.2.25502.107
Architecture: arm64
Commit: 89c8f6a112

.NET SDKs installed:
8.0.415 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/sdk]
9.0.306 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/sdk]
10.0.100-rc.2.25502.107 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 8.0.21 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 9.0.10 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 10.0.0-rc.2.25502.107 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.21 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 9.0.10 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 10.0.0-rc.2.25502.107 [/nix/store/x5s31j5yv843l8shp7ss7v7n4kpvfgq5-dotnet-combined/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
None

Environment variables:
Not set

global.json file:
Not found

Learn more:
https://aka.ms/dotnet/info

Download .NET:
https://aka.ms/dotnet/download
</p>
</details>
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: irrelevant since it reproduces in CLI.

### Analysis

Analyzer checks whether to report the diagnostic here:
https://github.com/dotnet/sdk/blob/1b7a79f9ed0432fd17b48a64a002f1d8f947445c/src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs#L51-L55

Then `GetIdentifier` attempt to extract `Identifier` from the type:
https://github.com/dotnet/sdk/blob/1b7a79f9ed0432fd17b48a64a002f1d8f947445c/src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.CSharp.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/CSharpMakeTypesInternal.cs#L13-L19

`ExtensionBlockDeclarationSyntax` extends from `TypeDeclarationSyntax`, however it doesn't have a valid value for `Identifier`:
https://github.com/dotnet/roslyn/blob/76a39c1a97fe5c73549786fc6944dc188a7b7b3b/src/Compilers/CSharp/Portable/Syntax/ExtensionBlockDeclarationSyntax.cs#L9

Since `Identifier` is not null but doesn't have any information about source file, file filter in `.editorconfig` doesn't have anything to work with and thus the diagnostic is not filtered out as it should be.

### PR DESCRIPTION
**Pull request by ezhevita**
Fixes https://github.com/dotnet/sdk/issues/51683.

### CODE REVIEW

File: src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs [hunk 1]
```diff
@@ -50,7 +50,7 @@ private void AnalyzeType(SymbolAnalysisContext context)
         {
             INamedTypeSymbol namedTypeSymbol = (INamedTypeSymbol)context.Symbol;
             if (namedTypeSymbol.IsPublic()
-                && GetIdentifier(namedTypeSymbol.DeclaringSyntaxReferences[0].GetSyntax()) is SyntaxToken identifier)
+                && GetIdentifier(namedTypeSymbol.DeclaringSyntaxReferences[0].GetSyntax()) is { SyntaxTree: not null } identifier)
```
Comment (stephentoub) [inline src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs]: Please add a test. Thanks.

Comment (ezhevita) [reply src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs]: Done.

Comment (stephentoub) [inline src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs]: @jcouv, is this the right thing to be checking?

**Review by stephentoub — APPROVED** [review]
LGTM. Thanks.

File: src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs (hunk 1 above)
Comment (jcouv) [reply src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs]: I didn't follow why checked whether the SyntaxTree is null would be relevant.

If I understood correctly, the issue is that we're walking through the declared types, we encounter a named type corresponding to the extension block, and that type is public.
A few possible ways to address this:
- there's a public API from the compiler `ITypeSymbol.IsExtension` to tell if a type is an extension (this API was added in roslyn 5.0, and I understand that some analyzer compile against older APIs, I don't know if that's the case here)
- the syntax node should be an ExtensionBlockDeclarationSyntax
- the Name of the INamedTypeSymbol would be blank for an extension

Comment (ezhevita) [reply src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs]: > I didn't follow why checked whether the SyntaxTree is null would be relevant.

This was basically my way to check if the type identifier is "valid" (since the `SyntaxToken` for it is `default` in case of extension block), so probably any other way also could work.

> * there's a public API from the compiler ITypeSymbol.IsExtension to tell if a type is an extension (this API was added in roslyn 5.0, and I understand that some analyzer compile against older APIs, I don't know if that's the case here)
> * the syntax node should be an ExtensionBlockDeclarationSyntax

I think both of these were not available since analyzer was targeting an older version of Roslyn, but it's worth double-checking.

Comment (jcouv) [reply src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs]: > I think both of these were not available since analyzer was targeting an older version of Roslyn, but it's worth double-checking.

A possible solution for that is checking the `Kind` of the syntax node. The value you need is `ExtensionBlockDeclaration = 9079`

Comment (ezhevita) [reply src/Microsoft.CodeAnalysis.NetAnalyzers/src/Microsoft.CodeAnalysis.NetAnalyzers/Microsoft.CodeQuality.Analyzers/Maintainability/MakeTypesInternal.cs]: Done.

**Review by jcouv — APPROVED** [review]
LGTM Thanks! (commit 7)

**Review by stephentoub — APPROVED** [review]
