### PR TITLE
reference-list: Expand includes

### LINKED ISSUE #49127: dotnet list reference returns non expanded paths
### Describe the bug

Calling `dotnet list .\src\coverlet.console\coverlet.console.csproj reference` returns 

```text
Project reference(s)
--------------------
$(MSBuildThisFileDirectory)..\coverlet.core\coverlet.core.csproj
```

and not an expanded path

### To Reproduce

Create a project that references another project using `$(MSBuildThisFileDirectory)` and call `dotnet list reference` on this project and you will get the same issue.

### PR DESCRIPTION
**Pull request by edvilme**
Fixes #49127

Currently, the command lists references without evaluating them, resulting in MSBuild syntax showing up in the command result. 

This attempts to fix that.

### CODE REVIEW

File: src/Cli/dotnet/Commands/Reference/List/ReferenceListCommand.cs [hunk 1]
```diff
@@ -44,7 +44,7 @@ public override int Execute()
         Reporter.Output.WriteLine(new string('-', CliStrings.ProjectReferenceOneOrMore.Length));
         foreach (var p2p in p2ps)
         {
-            Reporter.Output.WriteLine(p2p.Include);
+            Reporter.Output.WriteLine(p2p.EvaluatedInclude);
```
Comment (Forgind) [inline src/Cli/dotnet/Commands/Reference/List/ReferenceListCommand.cs]: I don't think the Project is really evaluated at this point; it looks like it just loaded the XML. You might have to call msbuildProj.GetEvaluatedProject() to get a real Project, from which you can call GetItems("ProjectReference") and iterate through that instead.

**Comment by marcpopMSFT** [comment]
Missed in our May redistribution. @MiYanni mind taking a look at finishing this off?

File: src/Cli/dotnet/Commands/Reference/List/ReferenceListCommand.cs (hunk 1 above)
Comment (MiYanni) [reply src/Cli/dotnet/Commands/Reference/List/ReferenceListCommand.cs]: This was the correct assessment. I added the logic from [sln-add](https://github.com/dotnet/sdk/blob/39c03282e67a91f4e2c71cf56e69271afb860d37/src/Cli/dotnet/Commands/Solution/Add/SolutionAddCommand.cs#L217) that @edvilme suggested and it works as expected.

```
(dogfood) PS D:\Code\sdk> dotnet list 'D:\Code\coverlet\src\coverlet.console\coverlet.console.csproj' reference
Project reference(s)
--------------------
D:\Code\coverlet\src\coverlet.console\..\coverlet.core\coverlet.core.csproj
(dogfood) PS D:\Code\sdk>
```

File: src/Cli/dotnet/Commands/Reference/List/ReferenceListCommand.cs [hunk 2]
```diff
@@ -33,18 +35,27 @@ public override int Execute()
...
+        try
+        {
+            projectRootElement = ProjectRootElement.Open(_fileOrDirectory);
+        }
+        catch (InvalidProjectFileException ex)
+        {
+            Reporter.Error.WriteLine(string.Format(CliStrings.InvalidProjectWithExceptionMessage, _fileOrDirectory, ex.Message));
+            return 0;
+        }
+        ProjectInstance projectInstance = new(projectRootElement);
```
Comment (Forgind) [inline src/Cli/dotnet/Commands/Reference/List/ReferenceListCommand.cs]: tiny nit: blank line after }

**Review by Forgind — APPROVED** [review]
Looks good!

File: src/Cli/dotnet/Commands/Reference/List/ReferenceListCommand.cs (hunk 2 above)
Comment (MiYanni) [reply src/Cli/dotnet/Commands/Reference/List/ReferenceListCommand.cs]: Fixed.

File: eng/restore-toolset.ps1 [hunk 3]
```diff
@@ -105,7 +105,7 @@ function CreateVSShortcut()
   $slnPath = Join-Path $RepoRoot 'sdk.slnx'
   $commandToLaunch = "& '$scriptPath'; & '$devenvPath' '$slnPath'"
   $powershellPath = '%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe'
-  $shortcutPath = Join-Path $ArtifactsDir 'VS with sdk.sln.lnk'
+  $shortcutPath = Join-Path $ArtifactsDir 'VS with sdk.slnx.lnk'
```
Comment (MiYanni) [inline eng/restore-toolset.ps1:108]: This, along with the sdk.slnx changes, were general problems after the change to slnx and the change to the finalizer that weren't addressed. So, I just updated those quickly here.

**Review by baronfel — APPROVED** [review]
TY for getting this closed out!
