### PR TITLE
WorkloadRestoreCommand.DiscoverAllProjects: Return full paths

### LINKED ISSUE #47390: 9.0.200 breaks "dotnet workload restore ..\some.sln"
### Describe the bug

`dotnet workload restore ..\my.sln` fails, because project paths in the sln file are evaluated based on the _current_ directory instead of the sln directory.

### To Reproduce

In an empty directory, run the following commands:

```
md repro
cd repro
dotnet new sln
dotnet new classlib -o lib
dotnet sln add lib
cd lib
dotnet workload restore ..\repro.sln
```

This fails, while `dotnet workload restore` from the sln directory succeeds.

This worked in .NET SDK 9.0.103. It broke in 9.0.200.

### Exceptions (if any)

```
Updated advertising manifest microsoft.net.workload.emscripten.net6.
Updated advertising manifest microsoft.net.sdk.aspire.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.workload.mono.toolchain.current.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net6.
Updated advertising manifest microsoft.net.workload.emscripten.net8.
Updated advertising manifest microsoft.net.workload.emscripten.current.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net8.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net7.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.workload.emscripten.net7.
Warning: Workload garbage collection failed with error: An error occurred trying to start process '"C:\Program Files\dotnet\dotnet.exe"' with working directory 'D:\temp\repro\lib'. The operation was canceled by the user..

Successfully updated workload(s): android aspire ios maccatalyst maui-windows wasm-tools wasm-tools-net7.

Unhandled exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Could not find a part of the path 'D:\temp\repro\lib\lib\lib.csproj'.  D:\temp\repro\lib\lib\lib.csproj
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\temp\repro\lib\lib\lib.csproj'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Build.Internal.XmlReaderExtension..ctor(String file, Boolean loadAsReadOnly)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting, Boolean loadAsReadOnly)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.ThrowInvalidProjectFile(BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting, Boolean loadAsReadOnly)
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCacheBase projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, ProjectRootElementCacheBase projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.GetOrLoad(String projectFile, OpenProjectRootElement loadProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement loadProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.OpenProjectOrSolution(String fullPath, IDictionary`2 globalProperties, String toolsVersion, ProjectRootElementCacheBase projectRootElementCache, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, Nullable`1 projectLoadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory, Boolean interactive)
   at Microsoft.Build.Execution.ProjectInstance..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion)
   at Microsoft.DotNet.Workloads.Workload.Restore.WorkloadRestoreCommand.RunTargetToGetWorkloadIds(IEnumerable`1 allProjects)
   at Microsoft.DotNet.Workloads.Workload.Restore.WorkloadRestoreCommand.<>c__DisplayClass3_0.<Execute>b__1()
   at Microsoft.DotNet.Workloads.Workload.WorkloadHistoryRecorder.Run(Action workloadAction)
   at Microsoft.DotNet.Workloads.Workload.Restore.WorkloadRestoreCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

### PR DESCRIPTION
**Pull request by edvilme**
Fixes #47390

When running `dotnet workload restore ../foo.sln`, the project paths in the sln file are evaluated based on the _current_ directory instead of the sln directory. To avoid this, `WorkloadRestoreCommand.DiscoverAllProjects` should return full paths instead of relative paths

image

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs [hunk 1]
```diff
@@ -1,5 +1,5 @@
 // Licensed to the .NET Foundation under one or more agreements.
-// The .NET Foundation licenses this file to you under the MIT license.
+// The .NET Foundation licenses this solutionFilePath to you under the MIT license.
```
Comment (edvilme) [inline src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs:2]: VS refactoring doing weird things here 😕

**Review by nagilson — APPROVED** [review]
This change looks good to me, nice find! It would be nice to have a test, though I understand this is a small, well-scoped problem and honestly a quirky bug that would not necessarily happen again if coded correctly. Curious what others think on the importance of a test.

**Comment by edvilme** [comment]
> This doesn't look unreasonable, but if this worked in 9.0.100, can you explain what regressed this? I suspect this may paper over a problem instead of resolving one.

It is not related to vs-solutionpersistence itself, but rather to the refactorings done on #45442 to remove `SlnFile` 😟

**Comment by Forgind** [comment]
Can you be more specific on which part of that change led to this issue?

**Comment by edvilme** [comment]
@Forgind yes, instead of resolving the project paths to be absolute paths, the refactoring resolved the relative paths instead. 

image

**Comment by Forgind** [comment]
Do you need to have filtered out SolutionFolders there?

Also, I think that instead of this fix, we should instead make that return absolute paths. Otherwise I'd be concerned that other places may be affected.

**Comment by edvilme** [comment]
> Do you need to have filtered out SolutionFolders there?

In the old parser, a Solution Folder is considered a special type of project. In this case.
```cs
var projects = solutionFilesInOrder.Where(p => p.ProjectType != SolutionProjectType.SolutionFolder);
```
is equivalent to
```cs
var projects = solutionFile.SolutionProjects
```
in the new parser

> Also, I think that instead of this fix, we should instead make that return absolute paths. Otherwise I'd be concerned that other places may be affected.

You mean `p.FilePath`? `SlnFileFactory.CreateFromFileOrDirectory` returns a `SolutionProjectModel` which is owned by the vs-solutionpersistence team

**Comment by Forgind** [comment]
> You mean p.FilePath? SlnFileFactory.CreateFromFileOrDirectory returns a SolutionProjectModel which is owned by the vs-solutionpersistence team. Also, it returns relative paths as they are stored that way in the solution files

Yeah, so instead of p.FilePath, it would be like Path.GetFullPath(p.FilePath) or whatever.
