### PR TITLE
Correctly initialize RefreshBrowserAfterFileChange

### LINKED ISSUE #33655: 'dotnet watch' stops auto-refreshing the browser on Hot Reload edits after a restart after a rude edit
## Repro steps
1. Create a new web: `dotnet new webapp`
2. Start watching: `dotnet watch`
3. Make an edit to `Index.cshtml` that is supported by EnC, e.g. Add `<p>Testing</p>`
4. Observe the output of the `dotnet watch` instance and the browser and see the edit is applied and the browser auto-refreshes
5. Make an edit to `Index.cshtml` that is unsupported by EnC, e.g. add a Tag Helper: `<a asp-page="/Home/">Test Link</a>`
6. When the `dotnet watch` instance asks whether to restart the app answer `a` (for Always)
7. The app is rebuilt and the browser auto-refreshes
8. Perform step 3 again (make a supported edit)

## Expected
The edit is applied and the browser auto-refreshes

## Actual
The edit is applied but the browser doesn't auto-refresh

### PR DESCRIPTION
**Pull request by pranavkm**
dotnet-watch uses a heuristic to determine if it should rely on the app
refreshing vs performing a browser refresh. It decides it should not refresh
the browser for any Blazor app (app with Blazor components). This heuristic
was not being correctly initialized after a rude edit.

Fixes https://github.com/dotnet/aspnetcore/issues/33655

### CODE REVIEW

**Comment by DamianEdwards** [comment]
Let's ask to get this in preview.6 please

File: src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs [hunk 1]
```diff
@@ -44,12 +50,12 @@ public ValueTask InitializeAsync(DotNetWatchContext context, CancellationToken c
...
 
-                // If there's any .razor file, we'll assume this is a blazor app and not cause a browser refresh.
-                if (!SuppressBrowserRefreshAfterApply)
-                {
-                    _refreshBrowserAfterFileChange = !context.FileSet.Any(f => f.FilePath.EndsWith(".razor", StringComparison.Ordinal));
-                }
+            // If there's any .razor file, we'll assume this is a blazor app and not cause a browser refresh.
+            if (!SuppressBrowserRefreshAfterApply)
+            {
+                RefreshBrowserAfterFileChange = !context.FileSet.Any(f => f.FilePath.EndsWith(".razor", StringComparison.Ordinal));
```
Comment (DamianEdwards) [inline src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs:58]: What happens in a Blazor Server app that has a mix of .cshtml and .razor files? We may need to make this decision per edit depending on what files changed.

Comment (pranavkm) [reply src/BuiltInTools/dotnet-watch/HotReload/DefaultDeltaApplier.cs]: Updated it - we tell the browser and it decides to reload based on the presence of Blazor.

**Review by DamianEdwards — APPROVED** [review]
