### PR TITLE
Fix NullReferenceException for `dotnet tool update -g --all`

### LINKED ISSUE #42598: Getting System.NullReferenceException when running `dotnet tool update -g --all`
### Description

When I run `dotnet tool update -g --all` CLI fails with this exception:
> Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Tools.Tool.List.ToolListGlobalOrToolPathCommand.GetPackages(Nullable`1 toolPath, Nullable`1 packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Update.ToolUpdateGlobalOrToolPathCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

### Reproduction Steps

I am not sure, because when I run this command under `8.0.303` I get the following error:
> --all is not found in NuGet feeds https://api.nuget.org/v3/index.json".

I assume it's a new feature, because when I do not specify `--all` for .NET 9 preview, I get this message:
> One must specify either package ID or use the update all option (--all).

I also could not find `--all` [here](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-update)

### Expected behavior

Either runs cucessfully or properly communicates the reason for failure

### Actual behavior

Miserably fails.

### Regression?

I assume so.

### Known Workarounds

_No response_

### Configuration

Here's the output of `dotnet --info`:
```
.NET SDK:
 Version:           9.0.100-preview.6.24328.19
 Commit:            ef4c241666
 Workload version:  9.0.100-manifests.21d7f649
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24328.19\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35201.85, VS 17.10.35122.118
   Manifest Version:    34.99.0-preview.6.340/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.android\34.99.0-preview.6.340\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: SDK 9.0.100-preview.6, VS 17.10.35122.118
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35201.85, VS 17.10.35122.118
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.ios\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35201.85, VS 17.10.35122.118
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maccatalyst\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35201.85, VS 17.10.35122.118
   Manifest Version:    9.0.0-preview.6.24327.7/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maui\9.0.0-preview.6.24327.7\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: SDK 9.0.100-preview.6, VS 17.11.35201.85, VS 17.10.35122.118
   Manifest Version:    9.0.0-preview.6.24327.7/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.6.24327.7\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      9.0.0-preview.6.24327.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]
  8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.6.24328.19 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24327.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

### Other information

Here's the output of `dotnet tool list -g`:
```
Package Id                             Version         Commands
------------------------------------------------------------------------
csharprepl                             0.6.5           csharprepl
dotnet-depends                         0.7.0           dotnet-depends
dotnet-ef                              8.0.7           dotnet-ef
dotnet-grpc                            2.53.0          dotnet-grpc
dotnet-nugetize                        1.0.4           nugetize
dotnet-reportgenerator-globaltool      5.1.10          reportgenerator
dotnet-svcutil                         2.1.0           dotnet-svcutil
microsoft.dotnet-httprepl              8.0.0           httprepl
microsoft.dotnet.apicompat.tool        8.0.204         apicompat
nuke.globaltool                        6.2.1           nuke
upgrade-assistant                      0.4.421302      upgrade-assistant
```

### LINKED ISSUE #43158: Empty package ID in message when running `dotnet tool update -g --all` with up-to-date packages
### Describe the bug
When running `dotnet tool update -g --all` and some packages are already up to date, the message prints an empty ID.

> Tool '' is already installed.

This is a follow-up issue blocked by #42598. That issue must be addressed before the problematic code path for this issue can be reached.

### To Reproduce

(Assuming #42598 already fixed)
1. Install any global dotnet tool. For example: `dotnet tool install csharprepl -g`
2. Immediately perform full global tools update: `dotnet tool update -g --all`
3. Observe that the CLI prints a message with an empty package ID in it

### Exceptions (if any)
Not applicable

### Analysis
This is caused by a new [optimization](https://github.com/dotnet/sdk/blob/f271b05d65e8218d3c276f417d66021692108118/src/Cli/dotnet/commands/dotnet-tool/install/ToolInstallGlobalOrToolPathCommand.cs#L165) where up-to-date packages are no longer reinstalled, introduced by 4a4823d8b9f0f7b3610f47af4ddda82edb6a21e2. The newly added message is formatted with the package ID supplied in the command line, which would be null if `--all` is supplied.

### Further technical details
- Include the output of `dotnet --info`
This is locally produced build from main branch.
<blockquote>
 .NET SDK:
 Version:           10.0.100-dev
 Commit:            f271b05d65
 Workload version:  10.0.100-manifests.2316105a
 MSBuild version:   17.12.0-preview-24407-03+6bc91d5e2

 Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22635
 OS Platform: Windows
 RID:         win-x64
 Base Path:   E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\sdk\10.0.100-dev\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.11.35222.181, VS 17.12.35209.166
   Manifest Version:    8.0.1/8.0.100
   Manifest Path:       E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.1\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      9.0.0-rc.1.24414.5
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  10.0.100-dev [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.7.24406.2 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24414.4 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24405.7 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24412.13 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24414.5 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.7.24405.2 [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_ROOT       [E:\dotnet-sdk\artifacts\bin\redist\Debug\dotnet]

global.json file:
  Not found
</blockquote>

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
CLI is capable of reproduction, no IDE required.

### PR DESCRIPTION
**Pull request by DL444**
Fixes #42598 and fixes #43158.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateCommand.cs [hunk 1]
```diff
@@ -43,16 +44,17 @@ public ToolUpdateCommand(
                         localToolsResolverCache,
                         reporter);
 
+            _global = result.GetValue(ToolInstallCommandParser.GlobalOption);
+            _toolPath = result.GetValue(ToolInstallCommandParser.ToolPathOption);
+            DirectoryPath? location = string.IsNullOrWhiteSpace(_toolPath) ? null : new DirectoryPath(_toolPath);
```
Comment (DL444) [inline src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateCommand.cs:49]: Not sure if this is the right way to handle `--tool-path` scenario. `_store` is not actually used in that case, but I think it would be more correct and future-proof to supply it with the tool path anyway.

**Comment by DL444** [comment]
CI check fails for tests seemingly irrelevant to proposed changes and I'm not sure how to proceed with this.

**Review by nagilson — APPROVED** [review]
Thank you for this change and contributing to .NET Tools. Your fix looks great to me and I appreciate the thorough writeup. I agree with how you handled the --tool-path scenario though I am admittedly unfamiliar with this part of the codebase as well.

It would be ideal to have a test to demonstrate the behavior is fixed and prevent regression, but not a merge blocker. 

Note since this is in `main` only, it would only go into .NET 10 most likely. I think we want this in .NET 9 too.

**Comment by nagilson** [comment]
@dsplaisted Are you ok to merge this without a test and do you agree this is a good candidate for rc2?

**Comment by nagilson** [comment]
> @DL444 We would be happy to merge this and we are going to merge this fix in 8.0.400 and 9.0.100 rc2 now but it wont be in any of the future releases until we merge it into `9.0.1xx`. Would you mind retargetting this to the `release/9.0.1xx` branch and adding a test? If you can do that, we'd be happy to merge it.

Bumping this to the top so it's more visible.

For 8.0.4xx, the code is significantly different so some time will have to be spent to backport it. I will try to take a look at this if it's not done when I have finished some other work items.

**Comment by DL444** [comment]
> Would you mind retargetting this to the `release/9.0.1xx` branch

Sure, I'll see what it takes soon, and I assume it should be relatively straightforward. Backporting to .NET 8 probably can't be done automatically, but it shouldn't be too complicated since I originally developed this fix for .NET 8 and then ported to main.

> and adding a test

Tests are currently not added because of testability problems I see, and I may need some guidance to proceed. To reproduce the problem, tools have to be actually installed into the runner's global store. Any mocking using an alternative store location will mask the problematic code path, which is why the issue wasn't caught by existing tests. I'm not sure test this way is acceptable, or if there are better ways to approach this.

**Comment by nagilson** [comment]
Thank you for your help. You can keep this PR as is and change the merge target. Any changes in 9.0.1xx will automatically get merged into the main branch as well. We appreciate your contribution in improving .NET. 😊 Sorry it took a bit for me to get to the review.

I will go through the process to get it approved in RC 2 as well as 8.0.400 once the PR is created. 

To add tests, I see what you mean now and how the original test did not cover this case. I will have to look and see if there is any possible way for us to test this well, so dont worry about that.

**Comment by DL444** [comment]
Changing target branch directly resulted in conflicts and accidental review requests. Will manually resolve conflicts later and apologies for anyone bothered.

**Comment by DL444** [comment]
Related backport PR:
#43516 .NET 9 RC 2
#43550 .NET 8

**Comment by nagilson** [comment]
The failures are an unrelated repo issue. Will check in on this again later to rerun

**Comment by baronfel** [comment]
The 8.0.4xx backport merged and was servicing approved - @nagilson was this one approved at the same time?

**Comment by DL444** [comment]
The changes were previously approved but merging was blocked by irrelevant CI problems.

**Comment by baronfel** [comment]
@DL444 they are PR code approved, but we also have a .NET process requirement to get changes approved by our management because of how close we are to release.
