### PR TITLE
Permit workload restore to work with new global.json

### LINKED ISSUE #42582: [NETSDKE2E][Workload Sets] Running `dotnet workload restore` should install the workload set when using global.json
### Describe the bug
Running dotnet workload restore` should install the workload set when using global.json

### To Reproduce
1. Install .NET 8.0.400 SDK
2. Install workload within manifest mode. eg. aspire workload
image

4. New global.json and add workloadverison
`     dotnet new global.json`
```
    {
      "sdk": {
        "version": "8.0.400",
        "workloadVersion": "8.0.400"
      }
    }
```
5. Try to run` dotnet workload restore` to install the workload set.

### Expected Result
Run `dotnet workload restore` should install the workload set eg. 'dotnet workload list'
image

### Actual Result
Unhandled exception:
image

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #42582

Specifying a workload set version in the global.json file is a supported scenario. If that workload set has not yet been installed, and the user tries to take an action that relies on workloads, we should error and indicate that they should make sure that workload set is installed first via update, install, or restore. We do that correctly, but when the user subsequently restores, we do not escape from the error case and instead direct the user to run restore. We should handle it properly, essentially installing the workload set before we discover which workloads the user needs and installing those.

I haven't tested this properly yet.

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs [hunk 1]
```diff
@@ -31,15 +33,46 @@ public WorkloadRestoreCommand(
...
+                                   creationResult.UserProfileDir,
+                                   null));
+            recorder.HistoryRecord.CommandName = "restore";
+
+            recorder.Run(() =>
+            {
+                // If there's a workload set version specified in the global.json file, we need to make sure the workload set is installed before we try to discover workload ids.
+                if (!string.IsNullOrWhiteSpace(workloadSetVersionFromGlobalJson))
+                {
+                    if (creationResult.WorkloadResolver.GetWorkloadManifestProvider() is SdkDirectoryWorkloadManifestProvider provider && provider.WouldThrowException())
```
Comment (dsplaisted) [inline src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs:59]: Rather than casting to the implementation class, if we need a new method we should add it to the interface.

**Review by dsplaisted — COMMENTED** [review]
We definitely need to fix this (so this should be retargeted to release/9.0.1xx now), but I wonder if there's a way to do it without so much code change.  We are going to update the workloads anyway after we discover which ones are needed, so would it make sense to just run an update command before doing the discovery?  That seems like it would be a lot simpler.

Also, for testing, consider writing a VM/MSI installation test for this.  I think it would work well :-)

**Comment by Forgind** [comment]
> We definitely need to fix this (so this should be retargeted to release/9.0.1xx now), but I wonder if there's a way to do it without so much code change. We are going to update the workloads anyway after we discover which ones are needed, so would it make sense to just run an update command before doing the discovery? That seems like it would be a lot simpler.

That's what it does? And note that most of the code changes are just taking a bunch of code out of one place in update/install and putting it in a helper method instead so I can call it in two places depending on whether I want to capture the result of the command in a workload history record.

> Also, for testing, consider writing a VM/MSI installation test for this. I think it would work well :-)

Yeah; that should be doable.

**Comment by dsplaisted** [comment]
>    dotnet-watch.Tests: [Long Running Test] 'Microsoft.DotNet.Watcher.Tests.NoDepsAppTests.RestartProcessOnFileChange', Elapsed: 00:43:28
['dotnet-watch.Tests.dll.1' END OF WORK ITEM LOG: Command timed out, and was killed]

This looks similar to the failure on #42978, though it's a different test that's timing out.

File: test/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs [hunk 2]
```diff
@@ -275,23 +275,35 @@ void SetupWorkloadSetInGlobalJson(out WorkloadSet originalRollback)
         }
 
         [Fact]
-        public void UpdateWorkloadSetViaGlobalJson()
+        public void RestoreWorkloadSetViaGlobalJson()
         {
+            InstallSdk();
```
Comment (dsplaisted) [inline test/dotnet-MsiInstallation.Tests/WorkloadSetTests.cs:280]: I think you need to remove the call to `InstallSdk` from `SetupWorkloadSetInGlobalJson`, and add it back in `UseGlobalJsonToSpecifyWorkloadSet`.

**Review by dsplaisted — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@dsplaisted looks like I couldn't just backport this as too much has changed. Let's sync tomorrow in standup and decide if we want to take this or not for servicing. CC @baronfel

**Comment by marcpopMSFT** [comment]
Per offline chat, the owrkaround is to run a workload update first (confirmed). We'll document this for now and revisit if we get feedback: https://github.com/dotnet/core/pull/9491
