### PR TITLE
dotnet test, Only check test projects for mixed mode

### LINKED ISSUE #4676: Non-test projects are blocking test execution
## Describe the bug

adding any non-test project prevents tests from running with the new dotnet test experience.

## Steps To Reproduce

make project with mstest.sdk based project, and class lib

run ` $env:DOTNET_CLI_TESTINGPLATFORM_ENABLE=1; dotnet test `

## Expected behavior

test projects run

## Actual behavior

Image

## Additional context

Looks like the check is too strict, and considers absence of TestingPlatformApplication to be a vstest project rather than any project.

### PR DESCRIPTION
**Pull request by nohwnd**
Fix https://github.com/microsoft/testfx/issues/4676

Working towards https://github.com/dotnet/sdk/issues/45927

### CODE REVIEW

File: src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs [hunk 1]
```diff
@@ -134,15 +134,22 @@ private void InitializeTestApplications(IEnumerable<Module> modules)
         {
             foreach (Module module in modules)
             {
-                if (module.IsTestProject && module.IsTestingPlatformApplication)
+                if (module.IsTestProject)
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs:137]: Nit: I would revert the condition and avoid the `else`.

File: src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs [hunk 2]
```diff
@@ -134,15 +134,22 @@ private void InitializeTestApplications(IEnumerable<Module> modules)
...
                 {
-                    var testApp = new TestApplication(module, _args);
-                    _testApplications.Add(testApp);
+                    if (module.IsTestingPlatformApplication)
```
Comment (Evangelink) [inline src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs:139]: Same nit comment here

**Review by Evangelink — APPROVED** [review]

File: src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs (hunk 2 above)
Comment (nohwnd) [reply src/Cli/dotnet/commands/dotnet-test/MSBuildHandler.cs]: done and done

**Review by Evangelink — APPROVED** [review]
