### PR TITLE
Fix dotnet test hang when the test app process exits but a child process of it remains alive

### LINKED ISSUE #51507: [MTP][dotnet test] Add test for a test app that starts a child process where the child process doesn't terminate
We need to add a test for a test application that starts a child process, let the test application process terminate, but keep the child process open.

We should have at least two test cases for that, with and without redirected stdout/stderr.

Does this scenario hang today? Is it acceptable? Do we have differences between Windows/macOS there?

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #51507

### CODE REVIEW

**Review by Evangelink — APPROVED** [review]

File: src/Cli/dotnet/Commands/Test/MTP/TestApplication.cs [hunk 1]
```diff
@@ -84,6 +116,41 @@ public async Task<int> RunAsync()
         }
     }
 
+    private static async Task WaitForExitWithoutOutputAsync(Process process)
+    {
+        // Mostly copied from WaitForExitAsync from dotnet/runtime, with adjustments to match our needs here.
```
Comment (Evangelink) [inline src/Cli/dotnet/Commands/Test/MTP/TestApplication.cs]: Nit: would be interesting for readers (and maybe also future you) to specify in what we are diverging from the `WaitForExistAsync` API.

File: src/Cli/dotnet/Commands/Test/MTP/TestApplication.cs [hunk 2]
```diff
@@ -56,14 +57,45 @@ public async Task<int> RunAsync()
...
+            {
+                await Task.WhenAll(stdOutTask, stdErrTask).WaitAsync(TimeSpan.FromSeconds(5));
+            }
+            catch (TimeoutException)
+            {
+            }
 
             var exitCode = process.ExitCode;
-            _handler.OnTestProcessExited(exitCode, outputAndError[0], outputAndError[1]);
+            _handler.OnTestProcessExited(exitCode, string.Join(Environment.NewLine, stdOutBuilder), string.Join(Environment.NewLine, stdErrBuilder));
```
Comment (Evangelink) [inline src/Cli/dotnet/Commands/Test/MTP/TestApplication.cs:100]: Are we having prefix for std out and std err before printing the content?

Comment (Youssef1313) [reply src/Cli/dotnet/Commands/Test/MTP/TestApplication.cs:100]: Yes, handled by the TerminalTestReporter.

File: src/Cli/dotnet/Commands/Test/MTP/TestApplication.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Cli/dotnet/Commands/Test/MTP/TestApplication.cs]: Revising again, I think that might even not be needed since we are not using `BeginOutputReadLine`/`BeginErrorReadLine`, and we can probably safely use the `WaitForExitAsync` provided by runtime.

Comment (Youssef1313) [reply src/Cli/dotnet/Commands/Test/MTP/TestApplication.cs]: Removed this helper. Waiting to see if all good in CI.

I also made the necessary test infra that lets us be able to test the broken scenario here. Confirmed the test hangs on main via #52980
